### ISSUE TITLE
Combine regions

### ISSUE THREAD

**Issue by FuIcrum** [NLthijs48/AreaShop#101]
I think it would be great if we could create several regions and group them, so that when we buy/rent them it would buy/rent all of them at the same time (the group itself). For example, let's say I create a region called "test1" and a region called "test2" a few blocks away. After typing a command, I could combine them into one group, let's say, for example, a group called "test". Then, when I went to buy/rent the regions, I could just put the name of the group instead of the region's and it would buy regions test1 and test2 at the same time, without interfering with the blocks in the middle.

**Comment by NLthijs48** [comment]
With some trickery in the `eventCommandProfiles` section you can already do grouping, it is however not as clean as it could be:

1. Make a region `test1` and a region `test1-plus`.
2. Make sure that players cannot directly rent/buy `test1-plus` by using the `limitGroups` section and setting the limit for regions in a group with all the extension regions to 0.
3. Make a `eventCommandProfiles` profile for the base regions (`test1`, `test2`, etc.) that when it is rented will also assign the player to the plus region, using a command like this: `/as setowner %player% %region%-plus`. This is where it is important that the extension region has a name that contains the base region, and has some static prefix/suffix.
4. Also make sure that the player is removed from the extension region when the region is sold/unrented and when the region is sold to another player by resell (similar commands as the one above).

Another thing to note is that you might not need 2 regions, you might get a way with using the polygon regions that WorldGuard offers (use `//sel poly`, then use left/right click as described in the message you get in chat).

It might still be a good idea for me to add something to AreaShop to support this better, maybe I could add something inside the region files that indicates that some other WorldGuard regions are linked to it, and should also get the region flags applied.

**Comment by FuIcrum** [comment]
Thanks for the detailed explanation, it will have to do for now. It would be great if you could make that functionality easier to use, but anyways, I love your plugin, great work!

Date: Thu, 10 Dec 2015 11:42:35 -0800

**Comment by NLthijs48** [comment]
Closed in favor of #131 (describes the same thing)
