### ISSUE TITLE
setting rent via sign not working

### ISSUE THREAD

**Issue by frizzbee30** [NLthijs48/AreaShop#103]
Something we have been experiencing since the last few updates to the latest version is that it isnt possible to set a region to rent or buy just by placing a sign in the region.
All our regions have to be set by command, and then /as addsign works perfectly

However using [asrent] produces an inactive sign in a region. We did have problems with (if i recall) preciousstones preventing [buy] signs in our market, which the dev fixed, is it likely to be cross plugin interference, or could there be another issue? We were able to place signs up to a point to rent a region out.

Thanks

**Comment by NLthijs48** [comment]
Placing signs to add a region works for me, do you get any feedback from AreaShop when placing the sign? Does the sign change to the layout specified in the config? Does `/as info region <region>` list the region info?

Also adding by command (`/as stack` for generating WorldGuard region + adding to AreaShop or `/as add`+WorldEdit selection) is faster usually, because you can generate/add a lot of regions at once. And then for linking signs you can use `/as linksigns`, which is way quicker than placing the signs one by one.

**Comment by frizzbee30** [comment]
thanks for the reply, placing the sign just sets it as a 'normal' format text sign, so no feedback.

 I'm using the stack option which is great, can't get it to behave with vertical stacking though (which is a shame) and the option to 'undo' the changes if a mistake is made would be great. However, I do love the functionality!!

**Comment by NLthijs48** [comment]
Then AreaShop does not seem to do anything indeed, are you sure you have the sign tags set to `[asrent]` and `[asbuy]`? In previous versions they were `[buy]` and `[rent]` so you might still have that in your config file.

An undo option for the stack command is on my TODO list, that is something handy to have when it screws up haha. Vertical stacking should work correctly, I'll check to see if there is something wrong with that.

**Comment by NLthijs48** [comment]
Found out that vertical stacking is indeed not a thing, currently I do not detect if a player is facing up or down. Although most of the times you want horizontal stacking, I could of course add it. I have created an issue for that: #105.

**Comment by frizzbee30** [comment]
Thanks, I did notice the [buy] and [rent] earlier when looking through the config, i edited it thinking potentially buy was intererfering with [buy] in essentials, but havent tried it since  (was enjoying the stack set up too much!  :)  ). I'm guessing it's worth recreating the config file anyway, or are those the only changes?

I'll try the signs now they have been edited. Thanks for raising the changes  :+1:

**Comment by NLthijs48** [comment]
Okey good, I'll close this issue assuming that the signs work for you now.
