### ISSUE TITLE
I cant make any sign

### ISSUE THREAD

**Issue by Gew00nNiels** [NLthijs48/AreaShop#106]
Describe the feature with as much detail as possible: command, permissions, messages in chat, etc. Also indicate for which situations you would use it and why it should be added.

**Comment by NLthijs48** [comment]
What did you try to type on the sign? Does '/as' correctly show a list of commands or does it show that the plugin has not started correctly? Do you get any feedback from AreaShop when placing the sign?

PS: Je kunt ook gewoon Nederlands praten als je dat gemakkelijker vind.

**Comment by Gew00nNiels** [comment]
ik had gwn nagedaan zoals het op de videos staat etc. en kreeg geen
feetback van plugin zelf ofzo


2015-12-22 21:47 GMT+01:00 Thijs Wiefferink <notifications@github.com>:

**Comment by NLthijs48** [comment]
Start AreaShop wel goed op dan? Als je `/as` gebruikt, komt er dan de lijst met commando's te staan of geeft hij aan dat de plugin niet goed gestart is? Als hij geen lijst met commando's toont dan moet je even kijken in `logs/latest.log`, daar staat dan in wat er fout gaat.

**Comment by vice313** [comment]
Having an issue, am unable to get the plugin to work full stop. will place image of log issue hopefully you can help.
![error](https://cloud.githubusercontent.com/assets/16528930/12080298/40f84ee0-b24e-11e5-96cb-1b8714e1bcbb.jpg)

**Comment by NLthijs48** [comment]
You have a configuration issue in the `config.yml` file, can you paste that here using pastebin.com? The problem is at line 244, maybe you can find the error already yourself.

**Comment by Gew00nNiels** [comment]
Hij laat wel alle commands etc. zien maar zodra ik een sign maak gebeurt er
niets


2016-01-03 20:31 GMT+01:00 Thijs Wiefferink <notifications@github.com>:

**Comment by NLthijs48** [comment]
@Gew00nNiels Kun je dan je config sturen via pastebin.com? Misschien gebruik je de verkeerde tag op de signs. In de `signTags` sectie staat welke tag je hebt ingesteld voor de verschillende signs, misschien is dit anders dan in de documentatie (het is recentelijk veranderd).

**Comment by Gew00nNiels** [comment]
Ik wilde het gebruiken voor minetopia ._.


Op 3 januari 2016 20:47 schreef Thijs Wiefferink <notifications@github.com>:

**Comment by NLthijs48** [comment]
Is het gelukt of niet? Ik snap niet precies wat je met je laatste bericht wil aangeven.

**Comment by Gew00nNiels** [comment]
Nee lukte niet had hoop opgegeven als je info wilt over mijn server :
Citypvp.xinsh.nl


2016-01-21 23:39 GMT+01:00 Thijs Wiefferink <notifications@github.com>:

**Comment by NLthijs48** [comment]
Was ff gejoined, volgens mij moet je wat meer anti-hacker tools installeren lol.
