### ISSUE TITLE
need help the player can do want he want he have ascess to all

### ISSUE THREAD

**Issue by MaDeireiroGame** [NLthijs48/AreaShop#107]
any player can do all commands from plugin and i did't give any permissions

**Comment by NLthijs48** [comment]
You can find the default permissions on [this page](https://github.com/NLthijs48/AreaShop/wiki/Commands-and-Permissions), those are the things that players have access to by default. OPs can do all commands, so that is probably why you can do all commands yourself. `/as` lists all commands that the player can do, commands he does not have permissions for are not displayed there, so that is what you can use to check if your permissions are correct.

**Comment by MaDeireiroGame** [comment]
i want to block averything less use the sign to buy how can i do that becaus e didn't give any permission and he have some permmissions

**Comment by NLthijs48** [comment]
Then add negated permissions to the player for the commands that you do not want them to have. You cannot remove the `/as buy` permission though, then they would also not be able to use the sign. But you can force them to be inside the region when buying it (`default.yml`, `restrictedToRegion`).

**Comment by MaDeireiroGame** [comment]
ok tanks you one more thing im portugues and i will make the tranlation you want tranlation for portuguese language?

**Comment by NLthijs48** [comment]
It would be nice to have a Portuguese translation, check [this page](https://github.com/NLthijs48/AreaShop/wiki/Language-support#translating-on-transifex) for translation instructions. It can be done through Transifex so that it is easy to collaborate with other Portuguese people.

**Comment by MaDeireiroGame** [comment]
i dont undertand the pop up or something like that i will translate manually

**Comment by NLthijs48** [comment]
I don't know what you are talking about, can you send a screenshot of it or something like that?

**Comment by MaDeireiroGame** [comment]
![image](https://cloud.githubusercontent.com/assets/5786991/12010759/6eeb3b9e-acab-11e5-8832-7c265767c95a.png) that text

**Comment by NLthijs48** [comment]
Basically just go to [here](https://www.transifex.com/evolution-coding/areashop/), register an account and login, then click on Portuguese, and click on EN.yml, then click on Translate. At some point you need to ask access to the Portuguese language, so then I need to accept you as translator.

**Comment by MaDeireiroGame** [comment]
![image](https://cloud.githubusercontent.com/assets/5786991/12010800/21a0348c-acad-11e5-8932-33ff9e4a7ca3.png)
i cant find portuguese

**Comment by NLthijs48** [comment]
It looks like you already found it, I have accepted you for Portuguese.

**Comment by MaDeireiroGame** [comment]
i found

**Comment by MaDeireiroGame** [comment]
hello again i had a new problem your plugins doesnt add any owner to region why ? im playing with regions priority

**Comment by MaDeireiroGame** [comment]
solved!
