### ISSUE TITLE
Config.yml Issue

### ISSUE THREAD

**Issue by vice313** [NLthijs48/AreaShop#108]
So I am having a Problem with my Config.yml and have been told to give a copy of the config.yml using pastebin? And also told to make new issue. 

So problem Areashop Does not load on a 1.7.10 Pixelmon server made using spigot/cauldren.
I am ok with programming, but not great with C#,C or C++

so here is a pic of the problem 
![error](https://cloud.githubusercontent.com/assets/16528930/12081838/19a4c622-b27e-11e5-92a4-b2c0ef22625d.jpg)

and here is a copy of the programming from paste bin. 
[ChMB5DBs.txt](https://github.com/NLthijs48/AreaShop/files/76802/ChMB5DBs.txt)

Any help is greatly appreciated :)

(English)

**Comment by NLthijs48** [comment]
You have 2 errors in your config file:

1. On line 262 you have a line with `- "say An AreaShop region is being &aPurchased: %region%"`, but this line is not in the `before` or `after` section, move it to one or two lines below. It is also not properly indented, it should have 2 extra spaces in front of it.
2. On line 335 you need to have 2 extra spaces in front of the line.

Basically remember that all lists (consisting of lines with a `-` in front) should have the same indentation as the section they are in. Using an [Online YAML Parser](https://yaml-online-parser.appspot.com/) might also help in the future, it will indicate the line that the error is on (but also search around the spot).

**Comment by vice313** [comment]
Thank you so much for your time to help me with this issue and I am very grateful that you took the time to respond to my problem. I will promote for your plugin at this current time as money is scarece but as soon as I can I will make a donation. again thank you so much.  
Date: Tue, 5 Jan 2016 03:02:07 -0800

**Comment by NLthijs48** [comment]
Glad I could help you :)
