### ISSUE TITLE
worldguard region issues

### ISSUE THREAD

**Issue by Ac3dUd3** [NLthijs48/AreaShop#113]
I have a prison server and i have cells i want to rent out, ive already created flags for pvp and use both on deny. when a member rents the region he cant use items like crafting table etc. but if i change the region to allow or take the flag away everyone can use the items in the cell which defeats the purpose of the cell.

any idea how to fix this? spigot 1.8.8, and the latest areashop version

**Comment by NLthijs48** [comment]
Check [this FAQ item](https://github.com/NLthijs48/AreaShop/wiki/Frequently-Asked-Questions#how-to-prevent-players-from-opening-chests-in-regions-that-other-players-boughtrented), it explains what you need but then for the `chest-access` flag. You can apply the same thing to the `use` and `pvp` flags.

**Comment by Ac3dUd3** [comment]
oh i didnt see this section, thank you :)
