### ISSUE TITLE
I have no problem, but i was wondering

### ISSUE THREAD

**Issue by MrKiller01** [NLthijs48/AreaShop#115]
, when making an area and i forget to put the name down for owner and/or landlord, is there not a way to select every area and give them the rightfull owner/landlord? Now i buy my selfmade house for 100000 credits, and i do not get the money.... where does that go? Maybe __global__ needs a bank that owns all the land and sells area's to people who want to build on a piece, calculating the number of blocks it takes for the build.... Is that an idea???

**Comment by NLthijs48** [comment]
You can set the landlord by using `/as setlandlord <player> [region]` (no need for the region argument if you stand inside it). You can also set it in the `default.yml` file to be active for all regions at once, or if you only want it for a group of regions then use the `groups.yml` file and assign a landlord to a group of regions.

If there is no landlord set then the money is gone forever, it does not go anywhere. I'm not sure what you mean with your last sentence, but maybe a price depending on the region size is what you are looking for? For that there is already a request ticket: #23.

**Comment by NLthijs48** [comment]
I'm assuming your problem is solved.
