### ISSUE TITLE
How to disable the greeting messages that AreaShop regions for players individually 

### ISSUE THREAD

**Issue by Etunien** [NLthijs48/AreaShop#119]
Hello, i want users to be able to deactivate these messages manually for themselves. Is there any way of doing so?
Cause in your FAQ i only found a way of disabling it for everyone.

**Comment by NLthijs48** [comment]
There is not really a way to let players turn off these messages themselves. You could as an admin turn them off per region, for example by adding those regions to a certain group, and giving that group a flagprofiles section that does not have the greeting messages.

**Comment by Etunien** [comment]
The problem is, the main problem with the messages is, that if players have multible regions and build one hous on them, when you walk through them you always get the message of who the owner is as soon as you change region, and that can be pretty annoying, Would there be a possible way of disabling the message for purchased regions? So the users still know if you can buy a region, but if the region is purchased the message of who the owner is wont show up.

**Comment by NLthijs48** [comment]
If you only want to disable it for sold regions then simply follow the instructions in [this FAQ item](https://github.com/NLthijs48/AreaShop/wiki/Frequently-Asked-Questions#how-to-disable-the-greeting-messages-that-areashop-regions-have), but then only for the `sold` state.

**Comment by Etunien** [comment]
Ok, thank you for the answer
