### ISSUE TITLE
Werkt niet

### ISSUE THREAD

**Issue by donleo123** [NLthijs48/AreaShop#121]
Yo ik weet dat je nederlands bent.
De plugin werkt niet, kan je helpen?
Skype: mijnbaja

**Comment by TheRealExus** [comment]
Translation for anyone who is not dutch:

Yo I know you're Dutch.
The plugin does not work, can you help ?

**Comment by EvilOlaf** [comment]
Without further information not possible.
Describe your exact issue.
If needed provide your config files
Any errors in console? If needed provide a *full* startup log

**Comment by NLthijs48** [comment]
Added you on Skype, it is better to provide the information right here in the ticket though, then I could have already answered your question.
