### ISSUE TITLE
I cant get my Areashop work all can go in my cells

### ISSUE THREAD

**Issue by HYPRIX** [NLthijs48/AreaShop#122]
Can some one help me ?

**Comment by NLthijs48** [comment]
Do you want to block people from walking into the cell or prevent them opening doors? Both can be done by changing the `flagProfiles` section in the `config.yml` file. Add a flag like the `interact` flag [here](https://github.com/NLthijs48/AreaShop/blob/master/AreaShop/src/main/resources/config.yml#L261), but then of course replace interact by `entry` to prevent walking into the region. Use the `interact` flag as in the link to get doors for only the members.

**Comment by HYPRIX** [comment]
Can you help me on skype or teamspeak?

2016-02-06 21:07 GMT+01:00 Thijs Wiefferink <notifications@github.com>:

**Comment by NLthijs48** [comment]
If you send me your skype name I'll add you, or you can join my teamspeak server at ts.go-craft.com.

**Comment by NLthijs48** [comment]
Assuming this has been fixed.
