### ISSUE TITLE
Question about tellraw

### ISSUE THREAD

**Issue by EvilOlaf** [NLthijs48/AreaShop#124]
As these shops are  highly frequented at our place player often asking when a shop will be available again.

So I thought about how to annouce that and ended up at the `expirationWarningProfiles:` section.

I know from a while ago using tellraw could be a bit tricky with the receiver of these messages (`%clicker%`, `%player%` ...).
My question is what value should I use if I want every player on the server to receive this tellraw message?

Best regards
Olaf

**Comment by NLthijs48** [comment]
For this you would need a `/broadcast`-like command that accepts JSON messages, and use that in the `expirationWarningProfiles` section. It might also work if you use `minecraft:tellraw @a <JSON message>`. The @a should cause the message to be send for each player on the server, like command blocks work. I did not test this though, heard some things about the @ things being broken in Spigot/Bukkit.

**Comment by EvilOlaf** [comment]
I already use tellraw at the `signProfiles:` section (you might remember) and as there were a few issues with this I wanted to ask before I try something.
Well if you did not try that by yourself guess I have to do so =)

**Comment by NLthijs48** [comment]
If a command with `@a` works in your console, then it also works in the AreaShop configs, so it might be best to try that first. Putting JSON strings in YAML files is a bit annoying indeed, because of the special characters in it. Let me know if it works :)

**Comment by EvilOlaf** [comment]
Looks good so far
```
    "5 minutes":
      warnPlayer: true
      commands:
      - 'tellraw @a ["",{"text": .................... }}]'
```
