### ISSUE TITLE
Hey areashop doors bug

### ISSUE THREAD

**Issue by math481c** [NLthijs48/AreaShop#125]
I got Areashop installed, but normal player can open other doors?
And when the region is rented normal players can also open other doors?

**Comment by math481c** [comment]
I am using all the newest versions 
And this is my config to Areashop: https://raw.githubusercontent.com/NLthijs48/AreaShop/master/AreaShop/src/main/resources/config.yml

**Comment by NLthijs48** [comment]
This is the default WorldGuard region setup, there are some flags that you need to change to prevent others opening doors. You can simply replace the `flagProfiles` section in your `config.yml` file with [this one](https://github.com/NLthijs48/AreaShop/blob/master/AreaShop/src/main/resources/config.yml#L253-L280) to get what you want (this will be the default for the next version of AreaShop). After that use `/as reload` to reload the config and update the regions.

**Comment by NLthijs48** [comment]
I'm assuming that my message above fixed the problem.
