### ISSUE TITLE
Breaking blocks inside a Region doesnt drop an entity

### ISSUE THREAD

**Issue by DraksterAU** [NLthijs48/AreaShop#141]
Hi NLThisj48,

Not sure if I've made a mistake with config, but when a player breaks a block inside an areashop region they rent, the block doesn't drop.

Using WG 6.1, AreaShop 2.2.1 and 1.7.10.

Doing a testbreak with WG doesn't fail...

**Comment by NLthijs48** [comment]
AreaShop does not change anything about block breaking or entities dropping, so I don't think that it is the cause of your problem. AreaShop only changes the WorldGuard flags as you specified in the `config.yml` file.

First you could try breaking blocks outside a region and see if that works, if that works then try to manually create a region and break a block. If that works then it should also work for the AreaShop region.

**Comment by NLthijs48** [comment]
I'm assuming your problem has been fixed

**Comment by DraksterAU** [comment]
Think this is an issue with WG 6.1 and my server version. WG regions from 5.7 don't seem to play up.

**Comment by NLthijs48** [comment]
I'm using WorldGuard 6.1 on my server myself, but I don't think I have this problem, might be possible it depends on configuration though. I'm running the latest Spigot 1.8.8 build by the way, maybe if you are running something older it does not work.

**Comment by DraksterAU** [comment]
1.7.10. It's a cauldron compatibility issue.

**Comment by NLthijs48** [comment]
Aha that would explain it, not much I can do then.

**Comment by DraksterAU** [comment]
Yeah world guard dropped support with v6 ;(

**Comment by NLthijs48** [comment]
Cauldron is also not really active anymore right? I don't think they have a 1.8 version at least. Maybe sometime soon Sponge would be a good solution for you ;)

**Comment by DraksterAU** [comment]
Cauldron is now thermos (and being updated daily) https://GitHub.com/tcpr/thermos

Sponge has nowhere near enough plugins (and 1.9 hasn't got enough mods) to update.

**Comment by NLthijs48** [comment]
I did not know it was taken over, not using it myself :)

Sponge has a major disadvantage with plugin availability indeed, it is still very young.
