### ISSUE TITLE
Impossible to join French Translator Team on Transifex

### ISSUE THREAD

**Issue by jewome62** [NLthijs48/AreaShop#144]
Hello,

I want to help you to translate the plugin to French
But when i try to join French team, French is not proposed in language select

And when i try to show the current translation in French, I have a error in Transifex

Bye

**Comment by NLthijs48** [comment]
There was a request from you on Transifex to join the French language, I have accepted that request now. You should be able to check the French language now and translate messages, let me know if that works.

I have to approve people manually after they request to join, so it takes some time to do that.

**Comment by jewome62** [comment]
Thanks.

I start to translate.

How you push in the project? I need poke you when I finish ?

**Comment by jewome62** [comment]
I finish to translate :dancers:

**Comment by NLthijs48** [comment]
Cool! Then next AreaShop update will include your translations. There will be some updates to the messages before the next update, so then some more translations would need to be done (most of them are probably just reusing your current translation and editing a few words).

**Comment by jewome62** [comment]
Hi !

I finish all curent translation for French.

:smile_cat:

**Comment by NLthijs48** [comment]
Great, thank you for translating!

I have released AreaShop V2.3.1 which includes the French, German and Norwegian translations, it can be found here on Github, on BukkitDev and Spigot.

**Comment by jewome62** [comment]
Hello @NLthijs48,

After update plugin in my server, i have some members who doesn't understand some commands.
And i was it because, some contributors was modify French translation with word which doesn't exist or gramatical error or translation which say the opposite !

Sometime, they modify good translation from you ( @NLthijs48 ) or other, to rewrite with error ! 
I just want say LOL ...

I modify the bad translation what i see but i think : we need a reviewer for this.
Can you release new translation in next bugfix release ?

Thanks

**Comment by NLthijs48** [comment]
I cannot really check if the translations are correct, since I do not speak French myself (or at least not good enough), so sadly there is not much I can do. If you tell me which messages got wrongly translated I could try and find the person who did that and message them.

Thank you for fixing the problems, I appreciate it!

Before I upload a new AreaShop version I always get the latest translations from Transifex, so any changes you make will always be included in the next patch.
