### ISSUE TITLE
Adventure Mode

### ISSUE THREAD

**Issue by CooperCraft** [NLthijs48/AreaShop#148]
My server is a cityrp and uses AreaShop for houses where people can buy and build inside (obviously)
we have changed to AdventureMode by default to reduce Block-Glitching and other glitch abuses. Is there a way so they are in adventure mode and when they buy the house they are in survival inside the property, (just inside the house). Thanks.

**Comment by Defnder** [comment]
Maybe you can use a WorldGuard flag for that. 
There is a flag called "game-mode":
"The gamemode (survival, creative, adventure) that will be applied to players that enter the region"

**Comment by NLthijs48** [comment]
The suggestion of @Defnder should work, you can even add this in the `flagProfiles` section of the `config.yml` file as follows:
```yaml
flagProfiles:
  default:
    rented:
      game-mode: "survival"
```

Let us know if that works.

**Comment by NLthijs48** [comment]
Assuming this have been solved, I'm closing the ticket.
