### ISSUE TITLE
add door?

### ISSUE THREAD

**Issue by ownerstoner** [NLthijs48/AreaShop#151]
Can you do so you can add a door to the claim?

**Comment by NLthijs48** [comment]
What do you mean with this? Of course you can place a door in a WorldGuard regions, but I assume you mean something different? Please describe what you want to achieve.

**Comment by JonasAlb** [comment]
I think he means if he have a prison, he need iron doors outside the claim.
That can be used

**Comment by NLthijs48** [comment]
@JonasAlb Any reason they need to be outside of the claim? You probably don't want them to break the doors, but this can easily be solved by having another region cover the row where the door is, with a higher priority than the AreaShop region. That would allow the player to use the door, build in the reset of the claim. but not break the door.

**Comment by NLthijs48** [comment]
Closing the issue, assuming it has been solved.
