### ISSUE TITLE
AreaShop with Towny

### ISSUE THREAD

**Issue by Tanman421** [NLthijs48/AreaShop#154]
Hello. So on the server I play on, we use Towny as well as World Guard. I set the plot permissions to where the players can build/destroy "anywhere" in the plots where the mall is located. I created a parent region over the entire region overriding the players to have permission to build. I created 6 sample shops inside the mall, and set them up for rent using the [asrent] signs. Everything was created and players have the ability to rent the shops out. After renting out the plots, they do not have the ability to build/destroy in these shops. Do I need to have somthing configured in the plugin configuration, or change something with the parent region or plots? When I want to have a player build in their shop, I need to select the region and manually add the region flags block-place and block-destroy.

**Comment by NLthijs48** [comment]
By default AreaShop sets the `build` flag of WorldGuard regions, which should allow only the owner of the shop to build there, but that seems like the thing you want so I'm not sure what is going wrong in your case.

For the flags that AreaShop sets check the `flagProfiles` section of the `config.yml` file. Check if WorldGuard is blocking the block breaking or if another plugin is doing it, WorldGuard should always send a message.

Let me know if you manage to solve it.

**Comment by Tanman421** [comment]
We got it figured out. Since the plugin doesn't set a priority, I need to manually set the priority so players can build in their shops.

**Comment by NLthijs48** [comment]
Okey, you can also set the priority of the WorldGuard region using the `flagProfiles` section in `config.yml`, so then you do not need to do it by hand. Check the [new default config](https://github.com/NLthijs48/AreaShop/blob/master/AreaShop/src/main/resources/config.yml#L253-L280) file for an example.
