### ISSUE TITLE
How do i enable/disable permissions?

### ISSUE THREAD

**Issue by JonasAlb** [NLthijs48/AreaShop#156]
I don't know how to set the permissions to 'false'
I use Groupmanager. I want to set /as tp to 'false' and also /as find to 'false'

Hope you answer!

**Comment by NLthijs48** [comment]
Normally with permission plugins you can add the permission with an extra dash `-` in front to negate the permissions (take the permission away). So you would need to add the following permissions to the group you want to stop using `/as tp`:

* `-areashop.teleport`
* `-areashop.teleportsign`
* `-areashop.teleportfriend`
* `-areashop.teleportfriendsign`

Permissions for all commands can be found on this [wiki page](https://github.com/NLthijs48/AreaShop/wiki/Commands-and-Permissions).
