### ISSUE TITLE
Permission areashop.unrentown does not seem to work with signs

### ISSUE THREAD

**Issue by HollishKid** [NLthijs48/AreaShop#158]
Hello,

The title is quite explicit.
It does work for me as op.

Any ideas on this? 
Thanks!

**Comment by Spidev46** [comment]
I will test this on my server soon.

**Comment by EvilOlaf** [comment]
So basically you are trying to unrent an area which belonged to you before using a sign and this does not work for you?

**Comment by HollishKid** [comment]
For me as operator, Shift Right click works just fine. I can unrent anybody's region.

Players cannot unrent their own regions though.

**Comment by EvilOlaf** [comment]
Then you may have an issue with your permission setup. I use AreaShop completely without player commands. Everything can be done using a sign. Unrenting own areas as well. So this works for me.

**Comment by NLthijs48** [comment]
The signs simply execute the `/as unrent` command, so signs and commands use the same permissions. So you can simply let your players try the unrent command and see if that works. To check if they have permission for it you can let them use `/as help` and check if the unrent command is in the list.

**Comment by NLthijs48** [comment]
Closing the issue, assuming it has been solved.

**Comment by HollishKid** [comment]
Sorry for forgetting to close the issue.

It has been solved, seemed to be interference from ModifyWorld permissions.

Thanks for your help (and the awesome plugin of course!)
