### ISSUE TITLE
A person hired but can't build

### ISSUE THREAD

**Issue by MrKiller01** [NLthijs48/AreaShop#160]
Indicate the steps you did while encountering the problem, the expected outcome, and the actual outcome. Provide links to your config.yml, default.yml and groups.yml files (use pastebin.com or similar). Also provide a full startup log of your server (this indicates the plugin versions used).

I have a few times the issue where i can't let anyone who rented or bought a property to build inside it. This person has a higher priority if areas overlap, and also is a owner and member of that property, still he can't build in the designated area he rented...
I had this several times, and everytime i did the groundwork for them. It is tiresome... What am i missing here....

**Comment by NLthijs48** [comment]
Try to fix the problem using the WorldGuard commands, once you have figured out the problem you can automate it using the `flagProfiles` section of `config.yml` in AreaShop. You probably have some intefering region, but that is hard to tell without much information. Could you send me screenshots of all region you have at the place of the region that is not working correctly? (including `__global__`).

**Comment by NLthijs48** [comment]
Closing the issue, assuming it has been solved.

**Comment by MrKiller01** [comment]
Thijs, i am sorry for the very late reaction on my count, but i am still in the process of testing things out. I hope that when i am member of the lowest class and no OP, i should be able to buy a house and build in it... 
If i stumble into trouble, i'll get back at you, ok?

**Comment by NLthijs48** [comment]
If you have trouble figuring it out just create a new issue and I'll help you with it :)
