### ISSUE TITLE
Support PlotSquared regions

### ISSUE THREAD

**Issue by Mwthorn** [NLthijs48/AreaShop#163]
> Describe the feature with as much detail as possible: command, permissions, messages in chat, etc. Also indicate for which situations you would use it and why it should be added.

The short idea is to restrict AreaShop to only be used on your own PlotSquared plot.

Recently I have seen players made their own prison style plots (pretty much like roleplaying) and I feel the need to support that idea. By letting them setup their own shops or rent rooms/cells, this adds a lot more element and tools to players on a creative plot world. 
The current problem is, it needs to be restricted to your own plot or plots you are trusted on.

If this was added, I would use it on my creative server to allow players create their own gamemodes on their plots with rooms/cells. I have already allowed them to create their own sign-shops and many more commands to allow them create some kind of "server" on their plots. Gamemodes I've seen have been; Prison, KitPvP and RolePlay

Commands:
- Event: On plot clears (This should also clear any shops that is on the plot)
- Event: When kicked from plot (This should clear the player's shops, who got kicked)
- /plot shop (Maybe this could be the command, but "/as" would probably be better)
- /plot shop allow (A command for an owner of a plot, to allow trusted players to create shops)

Messages:
- Denied to create areashop. (When you try to create a shop not in your region/plot)
- Denied to edit areshop (When you try to edit a shop that you do now own)

Permissions:
- areashop.plots.bypass (Bypasses regions and lets you modify/remove/create shops anywhere)
- areashop.plots.member (Allows access if you are just member to the plot) (default is only owner of the plot)

**Comment by NLthijs48** [comment]
A feature to let players create their own AreaShop regions with some restrictions (like restricting to PlotSquared regions) would be a good thing to add. Some preparation has already be done to get to things like this (the landlord system).

No idea when something like this will be added, it does not have priority since this is a very niche feature.

**Comment by NLthijs48** [comment]
Merged into #175
