### ISSUE TITLE
LimitGroups not working reliable

### ISSUE THREAD

**Issue by kikelkik** [NLthijs48/AreaShop#164]
Hey!
Could you please test your "limitGroups" feature? I'm not sure if it's working correctly because on my server, different ranks with different limit-permissions receive the same limit-msg (in my case its 4 by default) although I testet both negating "default" permission and giving another groups permission and without negating "default" permission with inheritances of ranks.

AreaShop config: http://pastebin.com/d9yhyTK1 (I only use forsale-regions)
permissions (shortened): http://pastebin.com/Nrua6gVZ

Please let me know if I did a mistake!

**Comment by NLthijs48** [comment]
Could you show the exact message that the player gets? And the output of `/as me` of the player to see how many regions he already has? Then I should be able to tell a bit more, since your config and permissions file look fine.

**Comment by kikelkik** [comment]
/as me + Msg Without negating previous limitpermissions (just -areashop.limits.legende):
http://prntscr.com/bbkoof

With -areashop.limits.legende and - -areashop.limits.*
http://prntscr.com/bbkokj

Don't be confused about the name "legende", in my explanation I translated it to legend but in case, I do call it "legende" everywhere. 
If you wish, I can translate the msgs into english

**Comment by NLthijs48** [comment]
You do not need to negate any permissions, if a player gets the `default` and `legend` limitgroup the highest numbers apply. So giving them the permission for the `legend` limit group should do the trick. Please check that the player correctly has the permission with `/pex user <player> check areashop.limits.legend`.

**Comment by kikelkik** [comment]
> as me + Msg Without negating previous limitpermissions (just -areashop.limits.legende)

I did give the permission for legend and also checked it.

**Comment by NLthijs48** [comment]
Okey, then which case is going wrong still?

- What group is the player in?
- How many regions does he already have?
- What message do you get?
- What is wrong about it?

**Comment by kikelkik** [comment]
- Player is in group 'Legende'
- Already has '4 regions'
- gets the 'total-maximum' msg (in english: 'You can't rent and buy more than 4 region(s) in total (you already have 4 in group 'default').')
- He can't buy the region although his limit is set to a higher value

**Comment by NLthijs48** [comment]
Could you give me a raw permissions file and config file? I cannot reproduce this. It still looks like he does not have the permission for the `legend` limit group.

**Comment by kikelkik** [comment]
AreaShop config: http://pastebin.com/3MsWT2E9

Permissions (PEX): http://pastebin.com/pafPtzPp

Limits are set in 'Member', 'EhrenMember', 'SuperMember', 'Elite', 'Legende'

**Comment by NLthijs48** [comment]
In your permissions file you used `areashop.limits.Legende`, it should be `areashop.limits.legende` (note the capital `L` in `legende`). That should fix your problem :)

**Comment by kikelkik** [comment]
Oh shit .. Ok bad example :D
What about elite ? It doesnt work with any ranks

**Comment by NLthijs48** [comment]
Can't see anything wrong with elite, which player are you testing with? And which rank does he have?

**Comment by kikelkik** [comment]
I also tested it by myself - /deop , relog, /pex user kikelkik group set Elite , click buy sign (enough money)

**Comment by kikelkik** [comment]
But it is interesting that the error message is changing when negating the default/previous limits. 
Without negating it always says I was in default group
With negating it says that I was in the group I belong to (the right one, e.g. 'elite') but still leaves the limot value by default 4 in the msg

**Comment by NLthijs48** [comment]
Are you on the latest version of AreaShop? Because your config still says 2.1.2, I might have changed the implementation since then because 2.1.2 is close after releasing the limit groups features.

**Comment by kikelkik** [comment]
I'm running AreaShopv2.2.2 (latest). But you may be right with config version because it doesnt update itself. I will paste the new config later and we will see :)

**Comment by kikelkik** [comment]
I updated the config and adapted it to my settings. But it results in the same problem..
http://prntscr.com/bbvlna
Did you test it on your server? If yes, could you give me your preferences? (config, permissions)

**Comment by kikelkik** [comment]
Any idea?

**Comment by NLthijs48** [comment]
I have already tested this before my second comment on the ticket.

My `limitGroups`:
```yaml
limitGroups:
  default:
    total: 1
    rents: 0
    buys: 1
  other:
    total: 5
    rents: 0
    buys: 5
```

My permissions (using PermissionsEx):
```yaml
users:
  e8ac3370-cd53-4a96-9489-b0b019481f92:
    options:
      name: NLThijs48
    permissions:
    - areashop.limits.other
```

If you still have trouble please give me the full `/plugins/AreaShop` folder and permissions file.

**Comment by kikelkik** [comment]
I send you my AreaShop folder an permissions file via PM on dev.bukkit.org

**Comment by NLthijs48** [comment]
Replied on BukkitDev

**Comment by kikelkik** [comment]
dito

**Comment by kikelkik** [comment]
You recieved it via PM

**Comment by NLthijs48** [comment]
Answered to your PM, you accidentally specified the number of buys with the `buy` key, instead of the `buys` key, added console warnings for that now.
![screenshot_1](https://cloud.githubusercontent.com/assets/6951068/17038663/11579c90-4f97-11e6-8b98-9b25fd1c5415.png)
