### ISSUE TITLE
world guard dev #1672 onwards causes issues with Area Shop region updates

### ISSUE THREAD

**Issue by frizzbee30** [NLthijs48/AreaShop#170]
spigot 1.9.4 currently
latest AS build #35 

WG version 1672 upwards

The new flag system? (I suspect) appears to be causing issues after server load as the regions are updating?

Thanks

http://pastebin.com/aV3ijujp

**Comment by NLthijs48** [comment]
WorldGuard indeed changed their flag system, I'll try to check how I can properly integrate it into AreaShop again later today. Looks like I only need to call another method to go from a line like `chest-access: deny` to flags to be used in WorldGuard.

I might also open a ticket at WorldGuard to see if they can add back the method that has been removed in a backward compatible way.

**Comment by NLthijs48** [comment]
I submitted [an issue](http://dev.enginehub.org/youtrack/issue/WORLDGUARD-3709) to WorldGuard to find out why the latest version of WorldGuard is not in their Maven repository, which I would like to have to make a fix for this problem.

**Comment by frizzbee30** [comment]
That's great, thanks for all the effort put into a fantastic plugin! :)

**Comment by NLthijs48** [comment]
Maven repository of WorldGuard is fixed, now it is possible for me to make a fix. I hope to do that this weekend, cannot guarantee that though.

**Comment by frizzbee30** [comment]
great  :)

**Comment by NLthijs48** [comment]
Dev build which works with the latest WorldGuard dev build can be found here: http://wiefferink.me:8080/job/AreaShop/

**Comment by frizzbee30** [comment]
Thanks :)
