### ISSUE TITLE
Delete all items in a rent region when ends

### ISSUE THREAD

**Issue by JamesHooks90** [NLthijs48/AreaShop#173]
Delete all items in a rent region when rent time ends.

**Comment by EvilOlaf** [comment]
This is already a feature. Check the schematics config.

**Comment by JamesHooks90** [comment]
Facedesk sry!

**Comment by NLthijs48** [comment]
Schematics will only change blocks, not entities/items so maybe you also need [this](https://github.com/NLthijs48/AreaShop/issues/28)? Let me know if you found what you need, then the issue can be closed.
