### ISSUE TITLE
Need Support on Region Permissions

### ISSUE THREAD

**Issue by kc9ryt** [NLthijs48/AreaShop#176]
Hello,

I have made some shops all of which are rentals that all sit inside of a mall. The mall is protected using world guard with a Priority of 0 and the shops all should have the priority of 10 as i have not changed any of the defaults but when the renter goes to put down a block in the area it says that they can not place it there.

**Comment by NLthijs48** [comment]
Check `/region info <region>` for all regions at the spot your AreaShop region is. Check that the AreaShop has the highest priority of them all, and that `block-break`, `block-place` and `build` are not set to `deny` in any of them (except with a `non_members` group).

If you cannot figure it out then please send me your `config .yml` file and screenshot of the outputs of all regions at the AreaShop region spot using `/region info <region>`
