### ISSUE TITLE
invisible text on signs build #35 plus spigot 1.10.2

### ISSUE THREAD

**Issue by frizzbee30** [NLthijs48/AreaShop#177]
#### Current behavior
Hi, when I set up our region signs they were fine under 1.10, however I have just noticed they have all lost their text. They are still present and can be R+L clicked etc, but have no text.

I can only figure this may be a bug related to 1.10.2,which we have updated to earlier today,I have another plugin that seems to have some signs missing (billboards), but all the others eg warp, sell etc seem ok.

if i delete and recreate the signs,the text is still missing.

I'm going to try a later dev build of AS in case it's one you already know about :)

There are no errors in console, and the plugin works as normal.

**Comment by frizzbee30** [comment]
Hi, seems this is a known spigot issue with latest version  :(

**Comment by NLthijs48** [comment]
Updating Spigot now should fix the problem, this has been reported as a fix by two other AreaShop users. Thanks for the report though, could of course have been AreaShop.
