### ISSUE TITLE
Overview list suggestion

### ISSUE THREAD

**Issue by Defnder** [NLthijs48/AreaShop#180]
We are using AreaShop for shops in a city.

It would be great, if there would be a command (e.g. /as list) that will list all rented areas with the renters name.
E.g.:
Shop1 -> Playername1
Shop2 -> Playername2
...
Maybe also vice versa:
Playername1 -> Shop1

**Comment by NLthijs48** [comment]
I could improve `/as info` with information like this, it can already list all regions with certain filters (rented, for rent, certain player, certain group, etc.) so including some more information like who rented it can easily be added. In the next update `/as me [player]` can also list the me page of another player, which already takes care of your second example.

Thanks for the input on this feature.

**Comment by NLthijs48** [comment]
In AreaShop 2.3.0 this is solved, `/as info rented` will list all rented regions with the player that rented it and how long is left. It also uses pages, so it will show you 18 of them and you can click `previous` and `next` buttons to go to the other pages.

So I'm closing the ticket.
