### ISSUE TITLE
Cannot Start AreaShop

### ISSUE THREAD

**Issue by BlackwingTFD** [NLthijs48/AreaShop#184]
Will not start AreaShop at all. Error log as attachment.

AreaShop should start whenever I start the server.

In my eyes, it's not a bug. It's probably something with the config file based on the error. (Then again, everything was working fine up until a few minutes ago (As of me writing this, it's 9:50 AM)).

* Server platform (Bukkit, Spigot, etc.): Bukkit
* Server version: 1.10.2
* AreaShop version: 2.2.2
* WorldEdit version: 6.1.3
* WorldGuard version: 6.1.2
* Vault version: 1.5.6

[Error Log.txt](https://github.com/NLthijs48/AreaShop/files/359464/Error.Log.txt)

**Comment by EvilOlaf** [comment]
Your config file is messed up. Did you try to back them up and let AS generate new ones?

**Comment by BlackwingTFD** [comment]
@EvilOlaf No I didn't. Would I have to re-download AreaShop and get a fresh new config?

**Comment by EvilOlaf** [comment]
No. Stop your server, rename your `AreaShop` folder in your `/plugins/` directory to something else and restart it again. AS will create a new folder with fresh config files.

**Comment by BlackwingTFD** [comment]
AreaShop has started up again. Thank you @EvilOlaf for helping me with AreaShop.
