### ISSUE TITLE
Owners of rented regions can't build in them

### ISSUE THREAD

**Issue by DarthPossom** [NLthijs48/AreaShop#189]
#### Current behavior
Well, it used to work out fine, before I updated to 1.10, however now when
players attempt to build in their set regions they can't. (I have set the player to owner of the region both in world guard and in area shop, and set the priority higher on the plot region than the other region it is inside of in-game and in the area shop config file.)

#### New behavior
They should be able to build in their regions

#### Steps to reproduce (for bugs)
1. I run the server
2. players attempt to build in region
3. players get denied

#### Your environment
* Server platform (Bukkit, Spigot, etc.):  Spigot
* Server version: 1.10
* AreaShop version: 2.2.2
* WorldEdit version: 6.0
* WorldGuard version: 6.0
* Vault version: 1.5.6

(Server log:)

http://pastie.org/private/gnmmxlfrzhiiqfynylhfa

**Comment by panos3500** [comment]
i have the same problem

**Comment by DarthPossom** [comment]
I'm not sure if he'll really help you out unless you make your own thread, but it would be nice to get some help here. :P

**Comment by NLthijs48** [comment]
Could you post the `config.yml` and `default.yml` files of AreaShop? Especially the `schematicProfiles` section of the config is important since that is where the flags to use for the WorldGuard regions are defined.

**Comment by panos3500** [comment]
I solved it
shelter6:
        min: {x: -46.0, y: 56.0, z: -177.0}
        flags:
            allowed-cmds: [/deny]
            chest-access: deny
            use: deny
            allowed-cmds-group: NON_MEMBERS
            use-group: NON_MEMBERS
            chest-access-group: NON_MEMBERS
            blocked-cmds: [/respawn, /rspawn wild]
        max: {x: -42.0, y: 58.0, z: -173.0}
        priority: 0
        type: cuboid
        owners: {}
        members: {}

I hadnt put the NON_MEMBERS at the flag use and chest-access
that was the problem TY tho


2016-07-23 1:34 GMT+03:00 Thijs Wiefferink <notifications@github.com>:

**Comment by Roadhog360** [comment]
How did you do the Chest-Access-roup thing?
