### ISSUE TITLE
Overlapping Regions 

### ISSUE THREAD

**Issue by panos3500** [NLthijs48/AreaShop#190]
Hello!
I have a server that is 1.8 i am using WG 6.0 and areashop 2.2.2
Let me explain what i want to do 
So i have the Main region and i want to let players to be able to Open doors and buttons and i also want them to be able to open Furnaces and chests and i want the to can PVP within the main region BUT not Build or break within it.
So in that region i have setup 
1)Use allow 
2)Chest-Access allow
3)PvP Allow
4)Passthrough Deny

Now the "buggy" part is that i have a 2nd region lets call it a home for now 
in that home i want to be buyable and ONLY the owner of the Home can Build Break Use doors buttons,Fence gates etc and open Chests & Furnaces.And the NON members can open and use nothing 

I have set up the priorities to the main region to -1 and home's to 0
i have set parent Parent(town) and child(home) with the right order 

And now i have 
1) Non members cant Use Open chests doors ect BUT THEY can in main region{What's how i want it so its OK that part}
2)the Owner of the Home CANT use/open chests doors fencegates buttons etc {That's BAD this isnt how i want it}

And i have stuck there since the UUID introduction
(I had Dropped MC for a while)

I Need some help i have tried everything that i know if you can help me i would appriciate that 

THANK YOU! for reading this

**Comment by NLthijs48** [comment]
Could you show me the output of `/region info <regionName>` for the town and home region? There might be some flags set incorrectly that cause this problem. 

I don't think you want to set the `passthrough` flag to deny on the town region, the `block-break` and `block-place` flags are probably a better choice and might fix the problem.

**Comment by panos3500** [comment]
I solved it
shelter6:
        min: {x: -46.0, y: 56.0, z: -177.0}
        flags:
            allowed-cmds: [/deny]
            chest-access: deny
            use: deny
            allowed-cmds-group: NON_MEMBERS
            use-group: NON_MEMBERS
            chest-access-group: NON_MEMBERS
            blocked-cmds: [/respawn, /rspawn wild]
        max: {x: -42.0, y: 58.0, z: -173.0}
        priority: 0
        type: cuboid
        owners: {}
        members: {}

I hadnt put the NON_MEMBERS at the flag use and chest-access
that was the problem TY tho

2016-07-23 1:36 GMT+03:00 Thijs Wiefferink <notifications@github.com>:

**Comment by NLthijs48** [comment]
Great :)
