### ISSUE TITLE
How to give a permission for certain groups of regions.

### ISSUE THREAD

**Issue by Kiryllp** [NLthijs48/AreaShop#192]
I am making a plot server using this plugin, and i have it so that each plot is in a district and each district has their own pallet that only they can get.(through a shop) I was wondering if it is possible to give someone a permission when they join a plot or plot group.

**Comment by NLthijs48** [comment]
If you want to limit a player to only buying/renting certain regions, then check [this wiki page](https://github.com/NLthijs48/AreaShop/wiki/Limitgroups-information-and-examples).

I'm not entirely sure how you are getting them to join a plot/plot group so I'm not sure how you want to automatically give them the permission required for the stuff described on the wiki page. Let me know if the wiki page helps you out or if there are still things you did not manage to do.

**Comment by Kiryllp** [comment]
Hmmm, I read that wiki page and it doesnt seem to be what im looking for. Im looking for a way in the plugin or an external plugin that makes it so when you rent or buy a plot it gives you a permission. And when you leave the plot it takes away the permmsion.

**Comment by NLthijs48** [comment]
Aha then I misunderstood you, with AreaShop you can simply execute a list of commands when someone buys/rents a plot, so you should be able to give them permissions at that point. Check the [`eventCommandProfiles`](https://github.com/NLthijs48/AreaShop/blob/816d136a62dc20951c56d8d4241bb83134fcdf45/AreaShop/src/main/resources/config.yml#L179-L210) section of the `config.yml` file for more details.

The above applies assuming that you do not mean they should get permissions when physically walking into the region, for that there are WorldGuard plugins though.

**Comment by Kiryllp** [comment]
No you are correct, Thankyou. I will go test this now.

**Comment by Kiryllp** [comment]
Hmm, Is there a way to make this per Plot or per region group

**Comment by NLthijs48** [comment]
Depends how you want the player to select their group, if you let them select with a command, or any other way that will simply set their permission group, then you can simply added permissions to your permission groups and limit the plots correctly.

It would help if you could explain how you want players to choose between the groups and why that is important.

**Comment by NLthijs48** [comment]
I'm assuming you have solved the issue
