### ISSUE TITLE
Change the /as command

### ISSUE THREAD

**Issue by Tjockototo** [NLthijs48/AreaShop#194]
So im having a problem with the /as command

I have a AreaShop plugin that also uses /as

how do i change the command?.

**Comment by EvilOlaf** [comment]
Use bukkits command.yml

**Comment by NLthijs48** [comment]
The actual command of AreaShop is `/areashop` and `/as` is just a convenience thing. If you for sure want to reach AreaShop you can also use `/areashop:areashop`. Using the [commands.yml](https://wiki.bukkit.org/Commands.yml) file like @EvilOlaf suggests you can create another short command to be used for AreaShop.
