### ISSUE TITLE
Lang file resets itself.

### ISSUE THREAD

**Issue by Roadhog360** [NLthijs48/AreaShop#195]
On latest version of 1.8 plugin version, language file resets itself no matter what I do and will always be default.
Even if I just delete one character from a line, it doesn't work and resets as soon as the plugin starts up in any way.

**Comment by NLthijs48** [comment]
You failed to read the information in the header of the language file: [language file](https://github.com/NLthijs48/AreaShop/blob/816d136a62dc20951c56d8d4241bb83134fcdf45/AreaShop/src/main/resources/lang/EN.yml#L1-L10)
