### ISSUE TITLE
Change the update checker to look at Spigot or GitHub

### ISSUE THREAD

**Issue by NLthijs48** [NLthijs48/AreaShop#201]
Spigot is getting more popular every day, while Bukkit is getting quieter, it is best to let the update checker look at Spigot or Github. This will also reduce the delay between uploading and the update checker firing, since BukkitDev first needs to approve the upload.

**Comment by Androkai** [comment]
I'm searching for an example how this could look like and see you already planed it. I read a bit about possibilities GitHub and Maven give to achieve this and want to share it with you. Maybe it helps you to create this feature which helps me.

pom.xml - Maven-[plugin](http://www.mojohaus.org/buildnumber-maven-plugin/index.html) which get the build-hash and save it into ${buildNumber}
```
    <scm>
  	<connection>scm:git:https://github.com/NLthijs48/AreaShop.git</connection>
	<url>https://github.com/NLthijs48/AreaShop/</url>
    </scm>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>buildnumber-maven-plugin</artifactId>
                <version>1.4</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>create</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <doCheck>true</doCheck>
                    <doUpdate>false</doUpdate>
                </configuration>
            </plugin>
        </plugins>
    </build>
```
This can be for example used within plugin.yml:
` version: ${project.version}-${buildNumber}`

**Check for GitHub-API status**
https://status.github.com/api/status.json
```
{"status":"good","last_updated":"2016-09-07T10:46:15Z"}
```
*Possible status: `"good"=green`, `"minor"=yellow` or `"major"=red`*

**Validate sha**
https://api.github.com/repos/NLthijs48/AreaShop/commits/[sha_of_build]
_If invalid returns as JSON-text:_
```
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```

**Get sha of latest commit from master**
https://api.github.com/repos/NLthijs48/AreaShop/git/refs/heads/master
```
{
  "ref": "refs/heads/master",
  "url": "https://api.github.com/repos/NLthijs48/AreaShop/git/refs/heads/master",
  "object": {
    "sha": "7aa786f4cefa329434cf8d99c7fdc8efe73a256f",
    "type": "commit",
    "url": "https://api.github.com/repos/NLthijs48/AreaShop/git/commits/7aa786f4cefa329434cf8d99c7fdc8efe73a256f"
  }
}
```

**Compare builds against each other**
https://api.github.com/repos/NLthijs48/AreaShop/compare/[sha_of_latest_version/master]...[sha_of_build]
*e.g.:*
https://api.github.com/repos/NLthijs48/AreaShop/compare/7aa786f4cefa329434cf8d99c7fdc8efe73a256f...82b340ce1a43e5f1bf4ae2b9e1897789a665965e
*returns:*
```
{
...
  "status": "behind",
  "ahead_by": 0,
  "behind_by": 6,
...
}
```

**Comment by NLthijs48** [comment]
Thank you for the nice information to work with, I should definitely be able to pull this off soon.

The method you describe above would be good for checking how many commits you are behind, for example if you are running a development version. Normally I would want to check the [releases ](https://github.com/NLthijs48/AreaShop/releases)section though and suggest updates that have been pushed to there. I can get the releases with the [api described here](https://developer.github.com/v3/repos/releases/), so that should be [easy enough](https://api.github.com/repos/NLthijs48/AreaShop/releases).

I for sure want to implement this for the next version, when I do I'll update this issue.
