### ISSUE TITLE
Delete the info-entryforsale and the greeting-forsale text.

### ISSUE THREAD

**Issue by Hansjoerg1** [NLthijs48/AreaShop#203]
#### Current behavior
When i enter my Region I got spammed by the info-entryForsale and the greeting-forsale text.

#### New behavior
I tried to delete the messages in the Language config by many ways but when i started the server again it came back.

#### Steps to reproduce (for bugs)
1. Delete the messages in the Language config.

#### Your environment
* Server platform Spigot
* Server version: 1.7.10: 
* AreaShop version: 2.3.1
* WorldEdit version: 6.3.1
* WorldGuard version: 6.1.2
* Vault version:

**Comment by Hansjoerg1** [comment]
Its solved, it was a region flag

**Comment by NLthijs48** [comment]
Yes indeed, for reference: https://github.com/NLthijs48/AreaShop/wiki/Frequently-Asked-Questions#how-to-disable-the-greeting-messages-that-areashop-regions-have
