### ISSUE TITLE
Rent Region per Group

### ISSUE THREAD

**Issue by Cruwzky** [NLthijs48/AreaShop#204]
Is it possibly to make it so that the user can rent 1 region from one group, and 1 region from another group?

Cause I need the users to rent a "Build" region, but also have the ability to rent a "shop" region. But they should not be able to rent two "shop" regions, or two "build" regions.. is this possibly?

**Comment by NLthijs48** [comment]
[This page](https://github.com/NLthijs48/AreaShop/wiki/Limitgroups-information-and-examples) is what you need, basically you can setup two region groups, one for the Build type regions and one for the Shop type regions, and then allow players to get one from each of them.

Let me know if you need more help with it.

**Comment by NLthijs48** [comment]
I'm assuming you have solved the issue
