### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by XxPoNaGeXx** [NLthijs48/AreaShop#207]
I am having a few issues with this. All players can break blocks inside of someone elses shop and once they dont own the shop anymore it dosent clear I have it enabled in config

**Comment by XxPoNaGeXx** [comment]
ok i fixed the region reset. But I still cant fix how other players can place and destroy blocks in the area shop.

**Comment by NLthijs48** [comment]
Normally players should not be able to do that, are you sure that the player you are testing with does not have OP or all permissions? Please show me the output of `/region info` of all regions that are at the spot that you have the problem.
