### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by MysticCity** [NLthijs48/AreaShop#209]
10.08.2016 18:17:52 [WARN] [AreaShop] Task #62 for AreaShop v2.3.1#CUSTOM generated an exception
10.08.2016 18:17:52 java.lang.NoClassDefFoundError: me/wiefferink/areashop/managers/FileManager$2
10.08.2016 18:17:52 at me.wiefferink.areashop.managers.FileManager.sendRentExpireWarnings(FileManager.java:442) ~[?:?]
10.08.2016 18:17:52 at me.wiefferink.areashop.AreaShop$6.run(AreaShop.java:600) ~[?:?]
10.08.2016 18:17:52 at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
10.08.2016 18:17:52 at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
10.08.2016 18:17:52 at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:734) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
10.08.2016 18:17:52 at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
10.08.2016 18:17:52 at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
10.08.2016 18:17:52 at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
10.08.2016 18:17:52 at java.lang.Thread.run(Unknown Source) [?:1.8.0_20]
10.08.2016 18:17:52 Caused by: java.lang.ClassNotFoundException: me.wiefferink.areashop.managers.FileManager$2
10.08.2016 18:17:52 at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_20]
10.08.2016 18:17:53 at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_20]
10.08.2016 18:17:53 at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_20]
10.08.2016 18:17:53 at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_20]
10.08.2016 18:17:53 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
10.08.2016 18:17:53 at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
10.08.2016 18:17:53 at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_20]
10.08.2016 18:17:53 at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_20]
10.08.2016 18:17:53 ... 9 more

* Server platform (Bukkit, Spigot, etc.):  Spigot
* Server version: 1.9.4 r0.1 spnapshot
* AreaShop version: newest
* WorldEdit version: newest
* WorldGuard version: newest
* Vault version: newest

**Comment by NLthijs48** [comment]
Did you change the AreaShop jar while the server was running? Does this still happen after a restart? Because the most likely reason is that you removed the .jar file while the server is running. 

*Please don't use `newest` as version, because that is not correct, AreaShop has a 2.3.2 version so for AreaShop it is already wrong.*

**Comment by MysticCity** [comment]
Nop i downloade the version from spigot stop the server uploade the jar und start this server, an then i got many many times round about all 1-2 minutes this error

**Comment by EvilOlaf** [comment]
It is meant to not answer the question about a version with `newest` at all. Post the actual output of `/version <plugin name>` here. For WE/WG `/we version` and `/wg version` would be even more useful.

**Comment by NLthijs48** [comment]
Could try V2.3.2 of AreaShop, and restart your server again, based on this error I can't help you more than that.

**Comment by NLthijs48** [comment]
I'm assuming you have solved the issue
