### ISSUE TITLE
Players Being able to break Blocks

### ISSUE THREAD

**Issue by certaininbound** [NLthijs48/AreaShop#211]
#### Current behavior

We have a WorldGuard region protection our entire shop area.Playes can buy and rent without any problems BUT anyone can break blocks in the Shop plots. I have tried a number of things like setting the priority of the shops higher but this does not work.

#### Your environment

* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.10.2
* AreaShop version: AreaShop V2.3.1
* WorldEdit version: NA
* WorldGuard version: NA
* Vault version: NA

**Comment by NLthijs48** [comment]
Please show me the output of `/region info <regionname>` for each region at the spot of the AreaShop region, most likely you have set an incorrect flag on one of the regions or the priority of the AreaShop regions is too low.

**Comment by certaininbound** [comment]
Sorry to have bothered you. I seemed to have figured it out there was a missing line in the congfig
build: 'deny g:non_members'

**Comment by NLthijs48** [comment]
aha that works
