### ISSUE TITLE
I don't understand how to make it so a player can buy 1 plot and 1 cell, not 2 cells.

### ISSUE THREAD

**Issue by T0xicPanda** [NLthijs48/AreaShop#212]
#### Current behavior

I don't understand how to make it so a player can buy 1 plot and 1 cell, not 2 cells.

#### New behavior

I want players to be able to buy 1 cell, and 1 plot
#### Steps to reproduce (for bugs)

1. ?
2. ?
3. ?
4. ?

#### Your environment

* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.8.8
* AreaShop version: latest
* WorldEdit version: 6.1.13
* WorldGuard version: 6.1.2
* Vault version: 1.5.6

**Comment by NLthijs48** [comment]
Use the [limitGroups](https://github.com/NLthijs48/AreaShop/wiki/Limitgroups-information-and-examples) feature.

Basically: In the default group set the number behind `buys` to 2, `rents` to 0 and `total` to 2. Then create two extra groups, both with buys, rents and total on 1, 0 and 1 respectively. Then add all plot type regions to a regiongroup with `/as groupadd` and add all cell type regions to a group. Then add a `groups:` part to the limitgroups with the group you added them to. As last give your players `areashop.limits.<group>` for both groups you created.

**Comment by NLthijs48** [comment]
I'm assuming you have solved the issue
