### ISSUE TITLE
Help with marking

### ISSUE THREAD

**Issue by JoHnnYY01** [NLthijs48/AreaShop#213]
Hello,
Is there a way to make region with placing 2 block on same Y? I mean I don't need to create a room, I need to create a area that player can use form Y = 0 to Y = 256. I saw that in a few servers but I can't do it on mine.
Example:
![2016-08-19_15 30 57](https://cloud.githubusercontent.com/assets/21125585/17811303/48cf7f52-6622-11e6-889f-4f1ff32b3c7c.png)

Thanks in advance!

**Comment by NLthijs48** [comment]
You can simply select the two blocks (with the WorldEdit wand leftclick the first block, rightclick the second), and then use `//extend vert`, this will extend the selection to all `y` values. So after that you can use `/region define` to create the region and add it to AreaShop.

**Comment by JoHnnYY01** [comment]
Thanks a lot!!!
