### ISSUE TITLE
Use signprofile

### ISSUE THREAD

**Issue by R0bstar** [NLthijs48/AreaShop#217]
Hallo Thijs,

Weet niet zeker of dit in NL of EN moet, dus ik type maar in EN.

#### Current behavior
I read https://github.com/NLthijs48/AreaShop/wiki/Advanced-regions-setup about signprofiles.

I created a second profile in config.yml. Copied the original, changed the name and some text to be put on the sign. No errors when loading the config.

I then edited a groups.yml file that was created, as was written on the webpage, but it doesn't specifiy what to actually put in there. I randomly tried the following two things, but those didn't work:
minibooths:
  name: minibooths
  signprofiles: mbooths

minibooths:
  name: minibooths
  signprofile: mbooths

(removed the rest of the config).

Interestingly I didn't see any error messages So what should I do?

PS In the config file it says the following, but I have no idea how to do that: "## Set 'general.signProfile' in default.yml, groups or individual regions to set the profile."

#### Your environment

* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.10.2
* AreaShop version: v2.3.1#CUSTOM (not sure why it says CUSTOM)
* WorldEdit version: v6.1.3;7a097ca
* WorldGuard version: v6.1.2;e38d98d
* Vault version: v1.5.6-b49

Thank you very much for your help!!!

**Comment by NLthijs48** [comment]
Je mag het wel in het Nederlands schrijven als je dat gemakkelijker vind.

Wat is de reden dat je een ander signProfile maakt? Als de signs van alle regions wil aanpassen kun je gewoon het `default` profiel aan passen.

Als je alleen de signs van een groep regions wil aanpassen dan heb je `groups.yml` wel nodig. In dat geval doe je het volgende:

1. Voeg de regions toe aan een region groep door een WorldEdit selectie te maken met alle regions erin en dan `/as groupadd <groepnaam>` te doen, of `/as groupadd <groupnaam> <regionnaam>` te gebruiken.
2. Stop de server of gebruik `/as reload`
3. Open `groups.yml`, hierin staat nu de groep die je hebt aangemaakt. Stel de signProfile setting in op het profiel dat je hebt aangemaakt (alleen de regel met `general:` en `signProfile` hoef je zelf toe te voegen):
```yaml
survival-shops:
  name: Survival-Shops
  priority: 0
  general:
    signProfile: 'naam van nieuwe profiel'
  regions:
  - shop-001
  - shop-002
  - shop-003
  - shop-004
  - shop-005
  - shop-006
  - shop-007
```

PS: Dat er 'CUSTOM' in de versie staat is een fout van mij, dit heb ik er per ongeluk in laten staan in de release versie.

**Comment by R0bstar** [comment]
Late reactie van mij, maar bedankt! Dit werkt. De crux zat hem dus in:
  general:
    signProfile: 'naam van nieuwe profiel'

Dat werkt nu.

De reden was dat ik niet die tekst: "Shop 1, shop 2, shop 3" wou zien, maar gewoon: Shop. En omdat er ook plots zijn, en "Shopping booths" had ik dus meerdere signprofiles nodig!

Wat heel handig zou zijn is een soort van voorbeeld config die echt vol zit met voorbeelden. Misschien iets ooit voor de toekomst. Bijvoorbeeld dat voorbeeld waarbij de eerste periode duurder is dan de rest, dat was heel handig.

Waar ik nu aan zit te denken is dat als er niet meer betaald wordt voor een shop, deze tijdelijk niet meer te verhuren is. Ik wil niet dat de chests worden leeggehaald door een andere speler die de plot voor een minuut huurt, maar omdat het een vergissing kan zijn van de eigenaar van de winkel wil ik ook niet meteen heel de shop resetten.

Heb je daar misschien een tip voor? Automatisch rented by admin of iets dergelijks?

**Comment by R0bstar** [comment]
Ik krijg net een brainwave en vraag me af of het mogelijk is om een schematic te bewaren bij "unrented" met een naam van de eigenaar in verwerkt zit. Als de eigenaar dan komt huilen omdat zijn chests met diamanten en mooie spullen verdwenen is, zouden we de schematic kunnen laden (voor een prijs) en dan heeft ie al zijn spullen weer terug. Zou dat kunnen werken?

**Comment by NLthijs48** [comment]
Ik ben sowieso bezig met het kijken naar een manier om de config duidelijker te maken, ik hoop daar binnenkort een plan voor te hebben en dit te gaan uitvoeren voor de volgende AreaShop versie. Voorbeelden wil ik wel meer toevoegen aan de wiki (met name de FAQ), daar staan er nu ook al een aantal (elke keer als ik een vraag voor de 2x keer hoor zet ik het in de FAQ).

Cool idee met het Ocean monument, hoeveel shops ze kunnen huren kun je oplossen met [limitgroups](https://github.com/NLthijs48/AreaShop/wiki/Limitgroups-information-and-examples). Hiermee kun je zorgen dat ze maximaal 1 Ocean monument kunnen huren en maximaal 1 andere shop bijvoorbeeld.
