### ISSUE TITLE
Plot owners cannot access their chest in the plots they purchase and some cannot build as well.

### ISSUE THREAD

**Issue by richmondc** [NLthijs48/AreaShop#218]
Indicate the steps you did while encountering the problem, the expected outcome, and the actual outcome. Provide links to your config.yml, default.yml and groups.yml files (use pastebin.com or similar). Also provide a full startup log of your server (this indicates the plugin versions used).

steps: 
1. Added the chest access to flagprofile
2. Added chest access manually in world guard
3. Added the player as an owner manually in world guard

Expected Outcome
Players can create their own chest shop and have access to their chest

Actual Outcome
Players don't have access to chest shop

Config File:
http://pastebin.com/DZgCqpTS

Startup Log (I believe its this but it has the plugin version)
http://pastebin.com/nQvJgbKN

**Comment by NLthijs48** [comment]
Your `config.yml` file looks broken, you are missing a `'` at the end of line `167`.

Please show me the output of `/region info <regionname>` for the region you are testing with and all regions that cover the same blocks. Either the player is not added correctly to the WorldGuard region or another regions is overriding the AreaShop region.

You don't want to set `chest-access` to `allow`, this will cause that anyone can use chests, instead of only the owner.

**Comment by richmondc** [comment]
Hey thanks for the reply! I actually fixed it just now. Can you look at the config to see if I did it right please? 

http://pastebin.com/q5xMjzQf

What I pretty much did was change the interact to allow g:owners instead of deny g:non_members. I'm testing to make sure it's only the owner of the plot that can access the chest.

**Comment by NLthijs48** [comment]
Should be correct, I doubt if the `allow g:owners` will work though, assuming you have the latest WorldGuard version I think you need it to be `deny g:non_members`. You might also have to set `chest-access: 'deny g:non_members'`.

**Comment by richmondc** [comment]
Well hopefully it's working how I want it to be. I just set it to that and it's working to only allow owners to access the chest and no one else can access the chest. It's working right now like that.

When I put it to deny g:non_members it didn't allow the owner to access the chest. 

What would be the proper way to config this? My ultimate goal is to allow players to purchase the plot, build their own shop, set up their own chests. 

Thanks so much for the help!

**Comment by NLthijs48** [comment]
Are you sure you are using the latest WorldGuard version? The `g:non_members` stuff has changed at some point.

The default config should already work correctly if you use the latest WorldGuard. If you have any more problems, of course let me know.

**Comment by richmondc** [comment]
Yup, I'm using the latest version of WorldGuard. Just checked for updates and I'm up to date on it. 

I mean the good thing is that it's working but I just don't want to run into any problems in the future :)
