### ISSUE TITLE
[break] in lang not working for 1.7 servers

### ISSUE THREAD

**Issue by evernife** [NLthijs48/AreaShop#222]
#### Current behavior
I want to break line *****\n***** but it is not working

#### Steps to reproduce (for bugs)

1. set [break] in the message you want to break
2. reload plugin
3. see your fail T.T

#### Images

-------***Ingame***-------
![image](https://cloud.githubusercontent.com/assets/11357801/18195830/3f953b96-70c4-11e6-916e-c389b938b1e2.png)

-------***lang-cofing***-------
![image](https://cloud.githubusercontent.com/assets/11357801/18195867/7f89e4d6-70c4-11e6-940b-d7144caf6025.png)

-------***random-default-command-with-original-lang***-------
![image](https://cloud.githubusercontent.com/assets/11357801/18196282/e8c72bfa-70c6-11e6-9858-6f12403a2e7b.png)

-------
#### My environment

* Server platform: ***Thermos***
* Server version: ***1.7.10***
* AreaShop version: ***AreaShop V2.3.2***
* WorldEdit version: ***worldedit-6.1.1***
* WorldGuard version: ***worldguard-6.1.1***
* Vault version: ***Vault-1.4.1***

**Comment by NLthijs48** [comment]
Thanks for your detailed report.

I have tested this message with a couple different server versions, only on 1.7.x it is broken, 1.8/1.9/1.10 all work correctly. The `/tellraw` feature these messages use has been introduced in 1.7, so apparently there was a bug with the `\n` in there.

I'll have to see how I can fix this nicely. The solution would be to use a new `/tellraw` for each line (after a `\n`), but for that I will need to rewrite some parts of the message handling code. Because the usage of 1.7 is still [7.3%](http://mcstats.org/plugin/AreaShop#Game+Version) (mostly modded servers probably) among AreaShop users I would also like to have this fixed.

Until I have a fix ready you could either stop using the fancy messages (set `useFancyMessages` in `config.yml` to `false`) or remove all `[break]` tags from the messages.

PS: It looks like there is a line break after the `< AreaShop >` part of your first image, any idea how that happened?

**Comment by evernife** [comment]
i used a lot of spaces :V

Life calls us to do hard things :D

**Comment by NLthijs48** [comment]
I have implemented the solution for this problem, you can use a [development build](http://wiefferink.me:8080/job/AreaShop/) if you want to use it immediately. If you find any other issues please let me know :)

**Comment by evernife** [comment]
ok, i will test it

**Comment by evernife** [comment]
***First_try***
I tried to break the line at it start; The result is that hid the previous line.
![image](https://cloud.githubusercontent.com/assets/11357801/18226312/6de61992-71dd-11e6-888e-715d1697382d.png)
-----

***Second_try***
Break the line in the middle make it to hide until the "**place_holder**" (If i can call it that...)
![image](https://cloud.githubusercontent.com/assets/11357801/18226431/fbe2dfda-71df-11e6-9c9b-d59a0e8cf692.png)

-----

***Sequel***
I tried with a lot other manners, like using a single line to break, etc
Also I tried to [break] the line in the prefix, did not work too. (make the prefix desappear) 

In fact, it seems to hide the part that shows the information from the ***region***
In my case, the "**Public_Shop01**"

Anyway, sorry for the horrible english, i am brazilian T.T

**Comment by NLthijs48** [comment]
A `[break]` needs to be at the end of a line, so after that you need to continue the text on a new line. Let me know if that works.

**Comment by evernife** [comment]
![image](https://cloud.githubusercontent.com/assets/11357801/18226582/4a528384-71e3-11e6-8440-c870a5e7ef16.png)

The prefix has spacebars to "break" line

If use the *[break]* after the ***region_info*** it hide it.

**Comment by NLthijs48** [comment]
Do you get any errors in the log file? because there might be a problem there. I'll test your message myself to see if I find something.

**Comment by evernife** [comment]
Here it is: ***[HasteBin](http://hastebin.com/igohirilop.dos)***

I will see for errors

**Comment by evernife** [comment]
Getting this error when **/as reload**
> 03.09 13:49:49 [Server] INFO Invalid json: Unexpected value at line 1 column 980
Full lang: ***[HasteBin](http://hastebin.com/laxiricuvi.dos)***

Dont know if it is related :D

**Comment by NLthijs48** [comment]
It took me a while to figure it out, but I found the error and pushed a fix, a new build can be found on web page I linked above.

![screenshot_4](https://cloud.githubusercontent.com/assets/6951068/18227068/5f147eae-7219-11e6-84a3-d2205fc281a5.png)

**Comment by evernife** [comment]
Thank You, working well now :D

![image](https://cloud.githubusercontent.com/assets/11357801/18227393/036ea716-71f9-11e6-89cb-4e4d3a135688.png)

**Comment by evernife** [comment]
Sorry, i had not tested in all parts...

This first one is normal, but this one not  : /


![image](https://cloud.githubusercontent.com/assets/11357801/21504044/dd0a13d6-cc42-11e6-952b-e8b676f1e924.png)


![image](https://cloud.githubusercontent.com/assets/11357801/21503984/6ca19f9c-cc42-11e6-9227-368a8b0c7f34.png)

**Comment by NLthijs48** [comment]
You cannot use it in greeting messages, those are simply strings that I pass to the `greeting` flag in WorldGuard. So I have no idea if that flag of WorldGuard support multiple lines or not, you could try to experiment with `/region flag greeting <region> <message...>` to see if you can find a way to add new lines to it.

**Comment by evernife** [comment]
ty

**Comment by evernife** [comment]
![image](https://cloud.githubusercontent.com/assets/11357801/21506887/e150ef6a-cc5a-11e6-9ba7-5e33a87592b7.png)



> Normal " \n " would take care of the problem

**Comment by evernife** [comment]
![image](https://cloud.githubusercontent.com/assets/11357801/21506912/1d2f61ec-cc5b-11e6-8476-98d0c212d93c.png)
![image](https://cloud.githubusercontent.com/assets/11357801/21506921/2bf26b84-cc5b-11e6-9bc0-ebe9029809c3.png)

I changed my code, so it is working now

**Comment by NLthijs48** [comment]
Okey cool. I did some tests with the development version of AreaShop (which has some changes to the message system), and there it actually already works with `[break]`, so the next release version this will be working as intended.
