### ISSUE TITLE
The signs keep going Blank!

### ISSUE THREAD

**Issue by LucaByForce** [NLthijs48/AreaShop#223]
The signs keep going Blank!

Server: Spigot 1.10
Version: 1.10 Minecraft
Plugin V: Current
WG: Current Version
WE: Current Version

**Comment by EvilOlaf** [comment]
Do not use "latest" or "current" for describing your used versions. 
If in doubt use the output of /version and /version pluginname

**Comment by LucaByForce** [comment]
Type: Spigot 1.10
MC: 1.10.2
WG: 6.1
WE: 6.1;no_git_ID
AS: 2.3.2#CUSTOM

**Comment by LucaByForce** [comment]
Type: Spigot
MC: 1.10
WG: 6.1
WE: 6.1;no_git_ID
AS: 2.3.2#CUSTOM

**Comment by NLthijs48** [comment]
I'm assuming you have solved the issue
