### ISSUE TITLE
My signs are all blank D;

### ISSUE THREAD

**Issue by ONIXTurtle** [NLthijs48/AreaShop#224]
#### Current behavior
When i create a region and then the Sign , the sign is blank D:

* Server platform (Bukkit, Spigot, etc.): Spigot , Bungee Cord 
* AreaShop version: Newest
* WorldEdit version: Newest
* WorldGuard version: Newest
* Vault version: Newest

**Comment by EvilOlaf** [comment]
Do not use "newest" or "current" as description for your used software versions.
If in doubt use `/version` and `/version [plugin name]` to get useful values.
Also make sure to check your logs for any errors related to AS.

**Comment by NLthijs48** [comment]
I'm assuming you have solved the issue
