### ISSUE TITLE
Restoring regions

### ISSUE THREAD

**Issue by rubota** [NLthijs48/AreaShop#228]
#### Current behavior

Is there a video of how to set up auto restore after a region is no longer rented?
The tutorial is quite confusing 
#### Steps to reproduce (for bugs)

1. 
2. 
3. 
4. 

#### Your environment

* Server platform (Bukkit, Spigot, etc.): 
* Server version: 
* AreaShop version: 
* WorldEdit version: 
* WorldGuard version: 
* Vault version:

**Comment by NLthijs48** [comment]
Which tutorial are you referring to? Did you check [this page](https://github.com/NLthijs48/AreaShop/wiki/Region-blocks-save-restore)? If you have not yet added the WorldGuard regions to AreaShop then you only have to set the `enableRestore` setting in `default.yml` to `true` to enable it, if you already added your regions then you also need to change your `flagProfiles` section in the `config.yml` file to the one displayed on the page I linked above.

**Comment by NLthijs48** [comment]
I'm assuming you have solved the issue
