### ISSUE TITLE
Add prices depending on a formula

### ISSUE THREAD

**Issue by NLthijs48** [NLthijs48/AreaShop#23]
Makes it possible to depend the price on for example square or cubic meters. Also add variables for times region is extended, can still be extended, etc.

Keep in mind possibility of mortgage, paying X times before the price drop to zero. Also keep in mind other payment plans.

**Implementation:**
Either use a simple expression parser + the current formulas or use Javascript evaluation. Both described [here](http://stackoverflow.com/questions/3422673/evaluating-a-math-expression-given-in-string-form).

_Suggested by paedda2 (BukkitDev)_

**Comment by M9GLiquid** [comment]
I approve this one :)
Would be a great addition
