### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by Serux18** [NLthijs48/AreaShop#230]
Today has appeared this error in console

http://pastebin.com/i1RfKGEG

* Server platform (Bukkit, Spigot, etc.):  Spigot
* Server version:  1.8.8
* AreaShop version: 2.3.2
* WorldEdit version: 6.1.4 #3623
* WorldGuard version: 6.1
* Vault version: 1.5.6-b49

**Comment by NLthijs48** [comment]
This error has been fixed in the [development builds](http://wiefferink.me:8080/) of AreaShop, either install one of those or wait for the next release of AreaShop.
