### ISSUE TITLE
Building a shop together

### ISSUE THREAD

**Issue by R0bstar** [NLthijs48/AreaShop#232]
Hi Thijs,

One person rented a shop, but this person plays together with another.
The other is then added as a friend to the shop. Not sure what this does, but we tried that anyway.
However, this person has no permissions to change anything to the shop.

I then used /as setowner to move ownership to the other as a temporary workaround (so he could set up shop), and noticed that they got a free month of rent. Every time I type /as setowner username shopname, that shops rent is extended for another default period (in our case a month).

What am I doing wrong?

**Comment by NLthijs48** [comment]
The problem with `/as setowner` extending the rent has been fixed. The intention is that if you use setowner with the same players that already is the owner, it extends the rent. But by accident this always happened.

If you add players as friend they also get added as a member of the region, so they should be able to build in the region. Make sure that your `flagProfiles` section uses the `%friendsuuids%` variable to put the friends in the `members` or `owners` list of the region. The [default configuration](https://github.com/NLthijs48/AreaShop/blob/master/AreaShop/src/main/resources/config.yml#L163-L182) should work for sure.

If you cannot figure it out, please send me your `config.yml` file.
