### ISSUE TITLE
/as find cause teleportation between worlds

### ISSUE THREAD

**Issue by doodzio** [NLthijs48/AreaShop#234]
#### Current behavior

As topic says.
When player write e.g. /as find buy  and there are multiple worlds player can be teleported to region in other world.
#### New behavior

I can suggest to add in config files option to disable teleport to other world.
Good option will be also to allow to TP if aren't any regions to teleport on current world 
1. Option in config.yml files (with override by region.yml etc)
2. Permission system (allow tp to other world if necessary )
3. Prompt with question to tp or find on current map
#### Steps to reproduce (for bugs)

1. Create multi-world config
2. On at least 2 world create regions using AreaShop 
3. Use /as free  or /as free rent 
4. If you dont get tp to other world  then tp to other world and repeat instruction in point 3
5. U will be at-least once tp to other world  
#### Your environment

- Server platform (Bukkit, Spigot, etc.): Bukkit
- Server version: 1.9.4
- AreaShop version: 2.2.2
- WorldEdit version: 6.1.3
- WorldGuard version: 6.1.2
- Vault version: 1.5.6-b49

**Comment by NLthijs48** [comment]
I get which changes you would like to see, however I don't exactly understand for which purpose you want this. Do you simply want AreaShop to give priority to regions that are in the same world, or do you want to block players going to other worlds with the `/as find` command?

A simple setting to enable/disable same-world priority and enable-disable teleporting to other worlds at all might do the trick, let me know if that is suitable for your situation.
