### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by Alkano764** [NLthijs48/AreaShop#235]
Hi, I do not see how (if possible) add permissions to a plot that only one group server (PEX) can rent / buy the plot. Thank you in advance and if this is not possible, there is an addon for pouvroir do this?

(I use the lastet version of the plugin)

**Comment by EvilOlaf** [comment]
Not sure but you might be able to use the limit feature for this: https://github.com/NLthijs48/AreaShop/wiki/Limitgroups-information-and-examples

**Comment by NLthijs48** [comment]
The limitgroups that @EvilOlaf mentions are indeed what should be used for this, simply give normal players a limit of 0 (so they cannot buy any regions), and give the group you want to be able to buy/rent the region a higher limit.
