### ISSUE TITLE
Multilanguage support for timestamps

### ISSUE THREAD

**Issue by Loapu** [NLthijs48/AreaShop#244]
#### Current behavior
The renting duration does not extend if I want to extend it. 

#### New behavior
Multilanguage Support for timestamps

#### Steps to reproduce (for bugs)

1. Change any timestamp in the config file (ex. day -> Tag)
2. Reload Areashop
3. Try to extend ur rent

#### Your environment

* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.10.2
* AreaShop version: 2.3.2
* WorldEdit version: 6.1.3
* WorldGuard version: 6.1.2
* Vault version: 1.5.6-b49

**Comment by NLthijs48** [comment]
What timestamp in the config file did you actually change? Do you mean you have edited the `duration` in the `default.yml` file to use `Tag`? The proper way to let AreaShop know about time indicators of other languages is in the `config.yml` [file](https://github.com/NLthijs48/AreaShop/blob/master/AreaShop/src/main/resources/config.yml#L56-L62), you can easily add more words to the `seconds`, `minutes`, `hours`, `days`, `weeks`, `months` and `years` lists. After you have added them there, they should work everywhere, for example writing them on the sign or using them in the `default.yml` or region files.

Let me know if you have any trouble using that.

**Comment by Loapu** [comment]
It works, thanks ^^
