### ISSUE TITLE
config resetting

### ISSUE THREAD

**Issue by ToxicLette** [NLthijs48/AreaShop#245]
hello! so, yea, my config.yml and default.yml is resetting everytime i save it. If I make a region and link it with /as add rent (region) and a player rents it, he still wont be able to build in it. i have tried many things to fix it. i tried changing priority, added flags like build allow, and allow-shop allow, removing all files and reinstalling it, remaking all regions, checked permissions, and much much more.. and some of it works, but only until i reload or restarts the server. i've checked for typos and tabs many times so im pretty sure its not because i write something wrong in there. i dont know what else i am doing wrong though, im very new at this and the 'group' section is a bit confusing for me. 
i am running spigot 1.10.2 with vault, essentials, permissionsEx, WorldGuard, WorldEdit, and ShopChest (i have been looking around to see if it was this plugin that messed it up, but i cant find any answers.)
thanks!

**Comment by NLthijs48** [comment]
AreaShop will only save the config.yml and default.yml files when they do not exist, so after they are saved at first startup it will never override them again. So make sure you are not making a mistake while editing and saving those files (are you using FTP? download the files after you saved them and check if they are edited properly).

Using [these](https://github.com/NLthijs48/AreaShop/blob/064b129205487215374f7e71e938c744dd3f3c00/AreaShop/src/main/resources/config.yml#L159-L177) `flagProfiles` settings in your `config.yml` file should already work, if it does not then send me the output of `/region info <region>` for the region you added to AreaShop and for all other regions that cover the save area (`__global__` and maybe spawn regions etc.).

**Comment by ToxicLette** [comment]
This is my mistake. I did not see that I had to edit them before they are "existing" is there a guide somewhere on how to do that?
Thanks a lot for your time.
Mvh Tulle

Den 13. nov. 2016 kl. 23.59 skrev Thijs Wiefferink <notifications@github.com<mailto:notifications@github.com>>:


AreaShop will only save the config.yml and default.yml files when they do not exist, so after they are saved at first startup it will never override them again. So make sure you are not making a mistake while editing and saving those files (are you using FTP? download the files after you saved them and check if they are edited properly).

Using these<https://github.com/NLthijs48/AreaShop/blob/064b129205487215374f7e71e938c744dd3f3c00/AreaShop/src/main/resources/config.yml#L159-L177> flagProfiles settings in your config.yml file should already work, if it does not then send me the output of /region info <region> for the region you added to AreaShop and for all other regions that cover the save area (__global__ and maybe spawn regions etc.).

-

**Comment by NLthijs48** [comment]
Your comment only makes sense to me when you are talking about the language files, because those cannot be edited directly and need to be copied first, that is not the case for the `config.yml` and `default.yml` files though.

**Comment by ToxicLette** [comment]
I'm hosting from a website using their ftp to edit the plugin files, after uploading them with FileZilla. I don't know how to edit before putting them in the server. Im going to read a lot more on this. I'm sorry for taking your time, and thanks a lot.

Mvh Tulle

Den 19. nov. 2016 kl. 18.29 skrev Thijs Wiefferink <notifications@github.com<mailto:notifications@github.com>>:


Your comment only makes sense to me when you are talking about the language files, because those cannot be edited directly and need to be copied first, that is not the case for the config.yml and default.yml files though.

-
