### ISSUE TITLE
Testing on 1.11

### ISSUE THREAD

**Issue by Sprungente** [NLthijs48/AreaShop#251]
Hello 
We have tested our server network on 1.11 and have this error

24.11 20:58:46 [Server] ERROR Could not pass event RegionUpdateEvent to AreaShop v2.3.2#CUSTOM
24.11 20:58:46 [Server] INFO org.bukkit.event.EventException
24.11 20:58:46 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 20:58:46 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 20:58:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 20:58:46 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 20:58:46 [Server] INFO at me.wiefferink.areashop.regions.GeneralRegion.update(GeneralRegion.java:214) [AreaShop%20(1).jar:?]
24.11 20:58:46 [Server] INFO at me.wiefferink.areashop.managers.FileManager$3.run(FileManager.java:476) [AreaShop%20(1).jar:?]
24.11 20:58:46 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 20:58:47 [Multicraft] Skipped 178 lines due to rate limit (30/s)
24.11 20:58:47 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 20:58:47 [Server] INFO ... 12 more

**Comment by Sprungente** [comment]
And later:

24.11 21:00:55 [Server] INFO Wildestier issued server command: /as find buy 50909
24.11 21:00:55 [Server] ERROR null
24.11 21:00:55 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'as' in plugin AreaShop v2.3.2#CUSTOM
24.11 21:00:55 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 21:00:55 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 21:00:55 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:649) ~[spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 21:00:55 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1335) [spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 21:00:55 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1170) [spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 21:00:55 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 21:00:55 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 21:00:55 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 21:00:55 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
24.11 21:00:55 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
24.11 21:00:55 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 21:00:55 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 21:00:55 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 21:00:55 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 21:00:55 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot1110.jar:git-Spigot-31fef09-c3d951d]
24.11 21:00:55 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
24.11 21:00:55 [Server] INFO Caused by: java.lang.NullPointerException
24.11 21:00:55 [Server] INFO at com.sk89q.worldguard.bukkit.WorldConfiguration.getBoolean(WorldConfiguration.java:219) ~[?:?]
24.11 21:00:55 [Server] INFO at com.sk89q.worldguard.bukkit.WorldConfiguration.loadConfiguration(WorldConfiguration.java:344) ~[?:?]
24.11 21:00:55 [Server] INFO at com.sk89q.worldguard.bukkit.WorldConfiguration.<init>(WorldConfiguration.java:211) ~[?:?]
24.11 21:00:55 [Server] INFO at com.sk89q.worldguard.bukkit.ConfigurationManager.get(ConfigurationManager.java:228) ~[?:?]
24.11 21:00:55 [Server] INFO at com.sk89q.worldguard.bukkit.WorldGuardPlugin.getRegionManager(WorldGuardPlugin.java:1016) ~[?:?]
24.11 21:00:55 [Server] INFO at me.wiefferink.areashop.regions.GeneralRegion.getRegion(GeneralRegion.java:448) ~[?:?]
24.11 21:00:55 [Server] INFO at me.wiefferink.areashop.regions.GeneralRegion.getWidth(GeneralRegion.java:460) ~[?:?]
24.11 21:00:55 [Server] INFO at me.wiefferink.areashop.regions.GeneralRegion.getAllReplacements(GeneralRegion.java:527) ~[?:?]
24.11 21:00:55 [Server] INFO at me.wiefferink.areashop.regions.GeneralRegion.applyAllReplacements(GeneralRegion.java:582) ~[?:?]
24.11 21:00:55 [Server] INFO at me.wiefferink.areashop.messages.Message.replaceArgumentVariables(Message.java:307) ~[?:?]
24.11 21:00:56 [Multicraft] Skipped 8 lines due to rate limit (30/s)

**Comment by NLthijs48** [comment]
With Spigot 1.11, the latest AreaShop build and WorldGuard 6.1.2 (build 1653) I cannot reproduce this issue. Can you tell me the versions of WorldGuard, WorldEdit and AreaShop you are using? Are you sure all your worlds and regions exist, because it looks like a world/region might be missing, but I cannot tell exactly. Could try to restart the server or use `/as reload` and check the startup log, AreaShop should inform about missing worlds/regions.

Next time please get the error messages from the `latest.log` file instead of the Multicraft console (it hides a bunch of lines) and put it in a code block (paste error, select it, click <> button in the editor).

**Comment by Sprungente** [comment]
It's fixed. The problem was the old LWC Database. After deleting, Worldguard Areashop and some other plugins will be started succesfully. Thanks for your support.
