### ISSUE TITLE
ADD SUPPORT FOR WorldGuard 6.2.0 please!

### ISSUE THREAD

**Issue by AmazedMender16** [NLthijs48/AreaShop#253]
#### Current behavior

http://pastebin.com/W4zv0Tw6
error says enough
plugin doesnt work

#### New behavior

http://pastebin.com/W4zv0Tw6
error says enough

#### Steps to reproduce (for bugs)

1. starting server

#### Your environment

* Server platform (Bukkit, Spigot, etc.): SPIGOT
* Server version: 1.11
* AreaShop version: 2.3.2
* WorldEdit version: 6.2
* WorldGuard version: 6.2
* Vault version: 1.5.6-b49

**Comment by NLthijs48** [comment]
This was already fixed in the development builds of AreaShop, but I released an update of AreaShop now which you can download to solve the problem.
