### ISSUE TITLE
Automatically upload EN.yml file to Transifex

### ISSUE THREAD

**Issue by NLthijs48** [NLthijs48/AreaShop#254]
1. On [the Jenkins build server](http://wiefferink.me:8080/) run the converter on `EN.yml`
2. Let the converter output the result to a directory in the web root (publicly visible on https://wiefferink.me).
3. Set Transifex to automatically update `EN.yml` with the file that is made available on https://wiefferink.me

**Comment by jewome62** [comment]
You can make this into transifex : https://docs.transifex.com/projects/updating-content

**Comment by NLthijs48** [comment]
@jewome62 Indeed, that is what step 3 entails, I need to convert the language file from my format to the format that Transifex needs first though, that is the harder part.

**Comment by NLthijs48** [comment]
Done, the following happens:

1. Code is pushed to Github
1. Jenkins starts building a development build of AreaShop
1. If the Maven build succeeds Jenkins runs the the following programs:
    1. Download all current translations from Transifex and same them in the folder of the Jenkins build (as backup)
    1. Transform the EN.yml file to the format that can be uploaded to Transifex.
    1. Upload the EN.yml file to Transifex, which add all new strings and remove old ones.
This process makes it save to update, since I always have a backup of the files in case that the translations on Transifex are wiped for some reason. Also, if any of the 3 sub-steps fail, it will not continue with the next one and the build will fail on Jenkins (I still need to setup email so that Jenkins emails me when a build fails though).

The next step is automate the 'release update' process, which also involves downloading the latest translations.

**Comment by NLthijs48** [comment]
By the way, I'm planning on integrating the tools that I made into InteractiveMessenger, so that others can also use them.
