### ISSUE TITLE
Permissions For AreaShop??

### ISSUE THREAD

**Issue by Lopiku** [NLthijs48/AreaShop#256]
#### Current behavior

I have no clue how to remove some certain permssions, from what the normal C group can use.

#### New behavior

I should have to give them permission, without them having it.

#### Steps to reproduce (for bugs)

1. This isn't a bug just me that cannot give certain permssions.
2. 
3. 
4. 

#### Your environment

* Server platform (Bukkit, Spigot, etc.):  Bukkit
* Server version: 1.8.8
* AreaShop version: Newest
* WorldEdit version: Newest
* WorldGuard version: Newest
* Vault version: Newest

**Comment by NLthijs48** [comment]
The permissions players get by default are listed on [this page](https://github.com/NLthijs48/AreaShop/wiki/Commands-and-Permissions), if you want to remove some of them you need to do that with your permissions plugin. Often permission plugin allow you to place a minus before the permission to remove it.

If you indicate what you want to prevent players from doing and show me your current permissions file then I can help you in more detail.

**Comment by NLthijs48** [comment]
I'm assuming your problem has been solved.
