### ISSUE TITLE
AreaShop Sign disapear 

### ISSUE THREAD

**Issue by jewome62** [NLthijs48/AreaShop#267]
## A image is more fast than words

http://imgur.com/csPMjsS

## Your environment (for bugs)

    Server platform Spigot
    Server version: 1.11.0
    AreaShop version: Build 109 on Jenkins
    WorldEdit version: 6.1.5
    WorldGuard version: 6.1.3 SNAPSHOT
    Vault version: 1.5.6

## Your config files (for bugs)

https://jewome62.eu/owncloud/s/b5hS9rLhXFHUvJe

**Comment by jewome62** [comment]
Same Bug with last dev build (112)

**Comment by NLthijs48** [comment]
An error slipt in that caused setting a profile setting in default.yml to a string to malfunction. Setting it to a string should look up the profile in config.yml, which now works again (I broke this in build 109). Updating to the latest development build should fix the problem.

Thanks for reporting this issue, even though I would not recommend running these development builds on your production server, I'm really happy I find out about this bug before releasing a new version. This would have broken the configuration of the majority of users!

**Comment by jewome62** [comment]
Hi,

Thanks for fast answer.
Is not problem to use lastest build version in my server, it's a small server and player don't use every day areashop
And we use last version of minecraft. Often we use last build for some lib ( protocollib, npc, etc ) because the compatible releases are not available in same time of minecraft release.

I take small donation for your fast and good job

**Comment by NLthijs48** [comment]
Thanks for your donation :) I did not check my email yet before answering you.

If you ever have problems or questions just let me know again, also thank you for proper bug reports, a lot of people fail to fill in the required information. With your report I could immediately go ingame and try to replicate the problem, which I really like.

**Comment by Benjamin0609** [comment]
Hey sorry im not so good at english how do i fix this problem i have a server on a server called superawesome the same thing happends to me. help!

**Comment by NLthijs48** [comment]
@Benjamin0609 Please open a [separate issue](https://github.com/NLthijs48/AreaShop/issues/new/choose) and provide your `/plugins/AreaShop` folder to me and I'll take a look.
