### ISSUE TITLE
Question about how much rents can be done on a single protection.

### ISSUE THREAD

**Issue by ClockTime** [NLthijs48/AreaShop#274]
I want to ask if it's possible to remove a protection from being rented after a certain amount of rents?
I wanted to make a protection which can be rented only once, and then an admin cleans the place and gives the items to the previous owner and releases the area for rent again.

For example:
Player A rents protection1.
protection1 becomes unable to be rented by anyone again after the duration of Player A has expired.
Admin returns the items to Player A and releases protection1 for rent again.

**Comment by NLthijs48** [comment]
You could simply use  `enableRestore` in `default.yml` to restore the region immediately after the rent is over, then an admin is not required at all. If you still want to stop renting the region again then you could add a command in the `eventCommandProfile` section of `default.yml`, for example setting the price of the region to 9999999 after unrent or setting the owner of the region to `unavailable` at unrent.

Let me know if that solves your situation.

**Comment by NLthijs48** [comment]
I assume your problem has been fixed, closing the issue.
