### ISSUE TITLE
feature request - copy command / mortgage

### ISSUE THREAD

**Issue by kiritss** [NLthijs48/AreaShop#275]
1. as copy (current region) (other region) - Basically copy all aspects of other region like price, days (if rent), landlord, etc. Just a short cut when regioning apartments and what not.

2. Mortgage feature - Allow players to basically buy houses with gradual payments (basically rent in a way, but gradual way to make payments to actually buy the region). If failed to pay mortgage, house would be automatically sold again.

**Comment by NLthijs48** [comment]
1. Why would you want to do this? You could either set the settings you want in `default.yml` to apply to all regions, or add regions to a group with `/as groupadd <group> [region]` and set the settings for that group using `groups.yml`.
2.  I might soon introduce a way to make the rent price variable, which might also allow for setting it to zero after it has been paid a certain number of times, which would be the same as mortgage. I don't think the mortgage feature in itself would be used much, so I rather go for a flexible pricing system instead (which supports mortgage and a bunch of other payment plans). I updated this issue #23 to note the possibility of mortgage so I suggest we close this one.

**Comment by NLthijs48** [comment]
I assume your issue is solved, closing the issue
