### ISSUE TITLE
region notification 

### ISSUE THREAD

**Issue by sharkybushbaby** [NLthijs48/AreaShop#281]
Is it possible to remove the on screen notification of who owns a place or if a place it available.

Gets a bit spammy walking past a row of houses. 

Thanks for your time

**Comment by NLthijs48** [comment]
Yes: https://github.com/NLthijs48/AreaShop/wiki/Frequently-Asked-Questions#how-to-disable-the-greeting-messages-that-areashop-regions-have

**Comment by sharkybushbaby** [comment]
Thank you. 

** feels stupid ***
