### ISSUE TITLE
The "multiple regions around the sign" message only shows one

### ISSUE THREAD

**Issue by Chinimala** [NLthijs48/AreaShop#285]
#### Current behavior
When I put an [as] sign on a block in several regions, and I don't write the region name, the plugin says for example : "Found multiple regions around the sign, specify region on the second line (2 of the regions that were found : region1)."
It always only show one region.

#### New behavior
The message should tell 2 regions names.

#### Steps to reproduce (for bugs)

1. Create 2 regions (named region1 and region2 for example) at the same place
2. Type "/as add buy region1" and "/as add buy region2"
3. Place a sign with [as] on the first line
4. Read the message

#### Your environment (for bugs)
I'm using Craftbukkit 1.11.2
* AreaShop version: 2.4.0#125
* WorldEdit version: 6.1.5
* WorldGuard version: 6.1.3-SNAPSHOT

#### Your config files (for bugs)
I discovered the bug in french, but it was still the same with the EN default file.

**Comment by NLthijs48** [comment]
Thanks for the report, I fixed the bug in the messaging framework, next version of AreaShop the problem is solved :)
