### ISSUE TITLE
Provide a way to automatically extend renting

### ISSUE THREAD

**Issue by NLthijs48** [NLthijs48/AreaShop#29]
This would make it safer for users to have a rental, and then they don't have to worry about it running out.

**Implementation:**
When a region is about to be unrented first check if automatic extending is on, if it is then just extend, if the user cannot extend anymore then actually unrent.
Add a setting in default.yml (and therefore groups and individual regions) to turn off the option to use this. Maybe also add an option to set the default setting for this option (so that it can be turned on by default).

_Suggested by Kofeyy_

**Comment by M9GLiquid** [comment]
With this add a config option to turn on/off the possibility to pay in advance :)
So that you could have so that the people pay per day and/or in advance :)

**Comment by csorrows** [comment]
This could actually be a solution to my feature request #85 so that it will auto extend and charge without expiring and losing their stuff. Then they could clear the region and unrent when they are ready.

**Comment by NLthijs48** [comment]
This has been implemented already: `rent.autoExtend` in `default.yml`
