### ISSUE TITLE
/as addfriend NewPlayerName     not working.

### ISSUE THREAD

**Issue by BabelSolea** [NLthijs48/AreaShop#297]
#### Current behavior

/as addfriend Name (in region)
/as addfriend Name RegionName

not working on new players.
that feedback in chat message "addfriend-notVisited"
but player currently online and stay near

with OP permissions is possible to add player from that command
but not if ure default player and owner of region.

no errors in log.log

i have 690 regions (3 players city's)

before launch on bungee all was fine with that command (and all plugin)

#### New behavior

idk... to that command work correctly on not OP players =)

#### Steps to reproduce (for bugs)

1. start latest spigot and bungee (with lobby no AS + main server with AS)
2. create region
3. buy region
4. join to main server new player (who join first time)
5. try add player in region as friend from /as addfriend NewPlayerName or /as addfriend NewPlayerName RegionName
6. do ure see chat-message "addfriend-notVisited" ?

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): 
using:
latest plugin build from spigotmc page
latest spigot on 1.11.2
latest bungee
latest vault
latest worldguard

#### Your config files (for bugs)

added zip with my AS folder

i hope that possible to fix fast) we on my server all loving your's plugin!!! <3
[AreaShop.zip](https://github.com/NLthijs48/AreaShop/files/871494/AreaShop.zip)

**Comment by BabelSolea** [comment]
**upd**

waste some time and tried reload plugin few times that error gone (but i dont know what make that, have not 100% case how that work)

i think was needed some time to plugin see new player (but i dont know how plugin do that to know what time need to plugin see new players)

**Comment by NLthijs48** [comment]
The problem is that the player you are trying to add as friend is online for the first time, which by mistake gets rejected as 'he never played on this server'. I did fix this at some point, but I only did for players that have the 'areashop.addfriendall' permission (OPs normally) and forgot to do it for normal players. I have corrected this now.

**Comment by BabelSolea** [comment]
ah thanks!!! pls look my new issue, i think ure can fast help me with situation )))
