### ISSUE TITLE
Players can't open chests.

### ISSUE THREAD

**Issue by AmaranthineEon** [NLthijs48/AreaShop#298]
#### Current behavior
I set up the plugin as directed. From checking the region flag before and after a player rents the area, everything seems to work correctly as they are added to the region as a member. They can build, break blocks, but can't seem to interact even though the flag is there (can't open chests, open enchantment tables) I even added the chest-access flag but still, no dice. I feel like it maybe another problem besides the plugin but I'm not sure? Please help.

http://prnt.sc/epbmxx

#### New behavior
nothing

#### Steps to reproduce (for bugs)
1.  Player clicks rent sign.
2.  Player place down chest in rent area.
3.  Player tries to open chest.
4.  "Hey! Sorry, but you can't open that here." pops up in chat for the player.

#### Your environment (for bugs)
* Server platform (Bukkit, Spigot, etc.):  Spigot
* Server version: 1.11.2
* AreaShop version: 2.4.0

* WorldEdit version: 6.1.5
* WorldGuard version: 6.2
* Vault version: 

#### Your config files (for bugs)

[config.txt](https://github.com/NLthijs48/AreaShop/files/874519/config.txt)

[default.txt](https://github.com/NLthijs48/AreaShop/files/874520/default.txt)

**Comment by AmaranthineEon** [comment]
Fixed, even though I set the larger region (spawn) to priority -1, it apparently still affected the inside region (which i had set to priority 10). I removed the build and interact flags from the larger region and it solved the problem.

**Comment by NLthijs48** [comment]
Nice that you found it out already, if you have any other problems with AreaShop let me know.
