### ISSUE TITLE
Empty signs

### ISSUE THREAD

**Issue by oriol20** [NLthijs48/AreaShop#301]
#### Current behavior
The signs go blank after creating them. No Spigot version problem since I'm on Bukkit. The user can rent the region, it's just the sign that doesn't have text.

#### New behavior
Signs should show text.

#### Your environment (for bugs)
* Server platform (Bukkit, Spigot, etc.): Bukkit
* Server version: 1.10.2
* AreaShop version: 2.4.0
* WorldEdit version: 6.1.3
* WorldGuard version: 6.1.2
* Vault version: 1.5.6

**Comment by electro2560** [comment]
Could you please provide a zip of your plugin folder?

**Comment by NLthijs48** [comment]
Did you change anything in the default.yml file, especially the `signProfile` section? Without your config files I cannot investigate this problem, so I will need those.

**Comment by oriol20** [comment]
I'm downloading the entire plugin folder, it may take an entire day... My Internet connection is bullshit. I didn't change anything in the default.yml, but now I don't think is a problem of the plugin itself since I'm having the same problem with Hotels plugin. Maybe some kind of conflict with the Bukkit version or the Bukkit itself? Is just signs go blank, in the case of AreaShop just after creating and with Hotels when clicked for rent (in that case the region is successfully rented, but unable to be rented again).

**Comment by NLthijs48** [comment]
The AreaShop files are really small, so if that already takes a day I really feel sorry for you...

I see that you use Bukkit 1.10, I think there is a version of 1.10 that has broken signs, so you could try updating to the latest 1.10 build. You can build the latest with [BuildTools](https://www.spigotmc.org/wiki/buildtools/#1-10).

**Comment by oriol20** [comment]
Nono! I'm downloading the hole plugin folder as requested by electro2560. It's just I don't have SSH connection right now and it goes file by file... I'll try that this weekend if I find a gap and I'll let you know. Thanks!

**Comment by NLthijs48** [comment]
I only need the `/plugins/AreaShop` folder, should be a lot easier to download :)

**Comment by oriol20** [comment]
Here it goes, thanks!

https://mega.nz/#!3hcw1DiQ!UTJwsDbk-D64lq9e-aVygsAlv7aOx6lcLDpoLUf-LZk

**Comment by NLthijs48** [comment]
Currently your regions folder is empty, which would mean you do not have any AreaShop regions, but I guess you just deleted your test region or something like that? I don't see any problems with your configuration files, so updating Bukkit is my only advice currently.

**Comment by oriol20** [comment]
Yes, there are no regions at the moment because I deleted them. I'll try that on the weekend. Thanks!

**Comment by NLthijs48** [comment]
I assume your problem has been resolved, closing the issue
