### ISSUE TITLE
Add Time delay for /as tp

### ISSUE THREAD

**Issue by Noahslife** [NLthijs48/AreaShop#304]
#### Current behavior
Works fine

#### New behavior
add tp delay to /as tp
for example
player executes: /as tp apt1
wait 7 seconds 
tp player to apt1

**Comment by NLthijs48** [comment]
I have already denied this idea before, see #60 for my reasoning. If you have new compelling arguments to add this to AreaShop itself let me know, but otherwise I'll stick with my standpoint as discussed in #60.
