### ISSUE TITLE
Make players wait a certain amount of time to teleport

### ISSUE THREAD

**Issue by PrisonNightmare** [NLthijs48/AreaShop#305]
#### Current behavior

/as tp (region) automatically teleports the player to the shop

#### New behavior

There should be an option where you can make the player have to stand still for a certain amount of time before they actually teleport to a shop, this will prevent them quickly escaping a PvP battle and have to wait before they can actually escape.

**Comment by EvilOlaf** [comment]
Duplicate https://github.com/NLthijs48/AreaShop/issues/304

**Comment by NLthijs48** [comment]
I'll answer the same as on #304:

I have already denied this idea before, see #60 for my reasoning. If you have new compelling arguments to add this to AreaShop itself let me know, but otherwise I'll stick with my standpoint as discussed in #60.
