### ISSUE TITLE
1.11.2 Problem open chest?

### ISSUE THREAD

**Issue by Makhart** [NLthijs48/AreaShop#306]
• spigot
• Game version 1.11.2
• AreaShop 2.4.0 release (button download) and tested on AS latest build jenkins
• WorldEdit 6.1.5;4651611
• WorldGuard 6.1.3-SNAPSHOT;c904242
• Vault 1.5.6-b49

CONFIG AreaShop basic or:
    ALL: # Flags that should always be applied
    forrent:
      chest-access: 'deny'
      use: 'deny'
      owners: ''
    rented:
      chest-access: 'allow'
      use: 'allow'
      owners: '%uuid%'

What's happening? When I buy second it only works first ...

http://reinhart.esy.es/pinageison/2017-05-03_17-27-34.gif

**Comment by NLthijs48** [comment]
> `chest-access: 'deny'`

This flag literally means nobody can open chests, change it to the flag below and it should work:
```yaml
chest-access: 'deny g:non_members'
```

You might need to do the same with the `use` flag.

**Comment by Makhart** [comment]
Still don't work.
"last bought" region by AS don't work.

http://reinhart.esy.es/pinageison/2017-05-03_20-59-56.gif

`  flagProfile:
    ALL: # Flags that should always be applied
    forrent:
      chest-access: 'deny g:non_members'
      use: 'deny g:non_members'
      owners: ''
    rented:
      chest-access: 'allow g:non_members'
      use: 'allow g:non_members'
      owners: '%uuid%'`

**Comment by Makhart** [comment]
Can You help me?

**Comment by NLthijs48** [comment]
Are you sure you do not have multiple regions at the same location? Because if the player is only a member/owner of one of them then they will be denied access. Could you send me the complete `/plugins/AreaShop` folder? I would like to see all configuration files to make sure they are correct.

**Comment by NLthijs48** [comment]
I assume your problem has been resolved, closing the issue
