### ISSUE TITLE
untranslatable string in info region

### ISSUE THREAD

**Issue by BabelSolea** [NLthijs48/AreaShop#308]
untranslatable string in info about region:
![image](https://cloud.githubusercontent.com/assets/23665302/26026999/edd5dbf4-380e-11e7-9836-bba7d6469332.png)

please add translate string for this.

**Comment by NLthijs48** [comment]
They are in the language file already:
```yaml
info-regionRestoringRent: "[darkgreen][bold]►[reset] Restoring is enabled [gray](region will reset at unrent)."
info-regionRestoringBuy: "[darkgreen][bold]►[reset] Restoring is enabled [gray](region will reset at sell)."
```

I never send messages in AreaShop without using the message library, so every user-facing message is translatable by default :)

Let me know if you managed to change the message.

**Comment by BabelSolea** [comment]
ok i found it in EN lang, didnt found in RU, they have very different strings (RU lang have less string to translate)

i added it in my custom RUru.yml and that work true, thanks!!!

**Comment by BabelSolea** [comment]
update:

how long ure will adding fast asynh world edit support?

cuz i using that plugin anyway to prevent laggs from world editing, so when used FAWE and any plugin what support WE but not support FAWE - that make that bug:

- edit some location with only WE
- any entity enter to that location
- that entity invisible (bug)
- entity leave that location - all fine - visible =)

**Comment by BabelSolea** [comment]
so now when i lauch schemevent command - players in that regions is invisible - they dont see self and other players doth see them.

**Comment by NLthijs48** [comment]
The Russian translation is not 100% complete, so there are indeed missing messages in the `RU.yml` file, those will fall back to the `EN.yml` messages.

FastAsyncWorldEdit should work fine, I think that plugin replaces the schematic copy functionality of WorldEdit, so then it should automatically be used by AreaShop. I have no idea what causes the invisible entities, but AreaShop for sure does not change anything about that. Looks like you need to look into FAWE for that, maybe check if you have the latest version of that and Spigot.
