### ISSUE TITLE
trying to set up a shopingcenter

### ISSUE THREAD

**Issue by thefroing** [NLthijs48/AreaShop#312]
when ive set up an area where people can buy plots and build there own shop, but they cant buy from eachother

**Comment by NLthijs48** [comment]
What kind of shop did you setup? Which plugin do you use for it? Does it use sign, chests or something else to sell items? Do you get a message from WorldGuard when you try to buy from another player or something else? Could you show me what happens?

**Comment by NLthijs48** [comment]
Since you did not provide any more information I assume your issue is solved, closing the issue.
