### ISSUE TITLE
Placed signs disapear

### ISSUE THREAD

**Issue by gerardvanschip** [NLthijs48/AreaShop#314]
#### Current behavior
When placing a sign I get a message saying it was placed but there is nothing there. I can repeatedly place signs and they all show up in the shop config file yet nothing shows in the world.

#### New behavior
Sign should show up like it did in all previous versions.

#### Steps to reproduce (for bugs)
1. place sign
2. write the stuff
3. no sign

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.11.2 snapshot, I build a new version once a week, this one is 5 days old
* AreaShop version: 2.4.0
* WorldEdit version: 6.1.7 snapshot
* WorldGuard version: 6.2.1 snapshot
* Vault version: 1.5.9 b-49

**Comment by NLthijs48** [comment]
Can you show me your `config.yml` and `default.yml` files from the `/plugins/AreaShop` folder? The only way a sign should disappear is if you set line1, line2, line3 and line4 to an empty line in the `signProfile` section of the `default.yml` file.

**Comment by NLthijs48** [comment]
Since you did not provide any more information I cannot investigate the issue, if you still have this problem please provide the information I need.
