### ISSUE TITLE
Multiple Regions with One Sign

### ISSUE THREAD

**Issue by navidmx** [NLthijs48/AreaShop#317]
Support for multiple regions with one sign would be awesome.

Maybe there could be a command, such as this:
/ascombine (group name) (region-1) (region-2) (...)

For example, if I had a large mansion with two wings of different shapes I wanted to combine, I could do /ascombine mansion mansion-left mansion-right.

Then, on a sign just put "mansion" in place of the region name, and players would rent both with one command. There is just a bit of error checking you'd have to do:
1. Check to make sure there isn't an existing region of the group name when a player uses /ascombine. If there is, return an error.
2. Make sure that if a region is placed into a group, it can not be purchased separately.

**Comment by NLthijs48** [comment]
I don't think we need a solution for this problem in AreaShop, if you would use `/region setparent mansion-left mansion-right` it should already work. The child region will get all flags from the parent, so it will also belong to the buyer.

Let me know if that works, I would like to add this to the FAQ on the wiki.

**Comment by navidmx** [comment]
So part of it works, and part of it doesn't.
When I purchase the parent region, I also have access to the child region, as I should. When I enter the child region, it reports the owner of the parent region as it should.

However, I have restoring enabled, and when the rent is over, all the blocks in the parent region revert but the blocks in the child region do not. I haven't tested out flags and such yet though I imagine those would be fine. But block reverting is important for me, so this isn't an option yet, but thanks!

Also, any idea if reverting entities such as paintings/item frames will be possible in the future?

**Comment by NLthijs48** [comment]
That is true, if you also need the restoring then the workaround I [describe here](https://github.com/NLthijs48/AreaShop/issues/131#issuecomment-198104641) should work for now. That is also the issue that tracks adding proper support to link regions, which I have planned. I'll mark this one as duplicate and keep that one open.

Entities do get saved into the schematic files, which means they also get placed back when the region resets, but when a region resets the entities placed by the player are not getting removed (so item frames and paintings). I have got [an issue](https://github.com/NLthijs48/AreaShop/issues/28) open for this problem, it is not super easy to fix though.
