### ISSUE TITLE
As rent permission

### ISSUE THREAD

**Issue by christophe6** [NLthijs48/AreaShop#318]
#### Current behavior

I want to create a rank and allow only certain players to rent/buy regions, but the permissions are given by default to players. How can I prevent that?

**Comment by EvilOlaf** [comment]
Negate the permission nodes you do not want players to have.

**Comment by christophe6** [comment]
Where can I negate them?

**Comment by NLthijs48** [comment]
Most permissions plugins allow you to add a permission like `-areashop.rent` to remove it, so just add a minus character in front.

**Comment by christophe6** [comment]
That fixed it! Thank you for your fast reply!
