### ISSUE TITLE
friends can't do anything in newer regions

### ISSUE THREAD

**Issue by ZoefyC** [NLthijs48/AreaShop#320]
#### Current behavior
It's kind of an odd problem. Somehow players that have been added as friends can't do anything (like opening chests, breaking blocks etc.) - but only in regions that are new. Old regions (1 year old) work just fine.

I checked the /rg i, friends are listed as members. So that shouldn't be a problem. Those players get a WorldGuard message telling them they "can't do that". 

![2017-06-08_14 28 40](https://user-images.githubusercontent.com/18103076/26928981-5c8a8c7c-4c58-11e7-8096-ddc1b78d4808.png)

#### Your environment (for bugs)
* Server platform (Bukkit, Spigot, etc.):  Spigot
* Server version: 1.11.2 (3fb9445-6e3cec8)
* AreaShop version: dev build 154
* WorldEdit version: build #3682
* WorldGuard version: build #1704
* Vault version: 1.5.6

#### Your config files (for bugs)

[AreaShop.zip](https://github.com/NLthijs48/AreaShop/files/1060978/AreaShop.zip)

**Comment by ZoefyC** [comment]
Oh wow, I totally didn't see that... Sorry! And thanks a lot :) As to why I was doing that, I was trying to make it so members show up with their names instead of their uuid on dynmap - and must have totally forgot about that. Everything works fine now. Thanks again!

**Comment by NLthijs48** [comment]
Good that it is solved, if DynMap is showing UUID's then I think DynMap-WorldGuard should be changed to translate UUIDs to names, adding people by name to WorldGuard regions is not recommended because if players change their name they will lose the region.
