### ISSUE TITLE
I am in the finished Chinese language, but each time the reload plugin,the zh.yml will become English Language

### ISSUE THREAD

**Issue by BenLiHao** [NLthijs48/AreaShop#322]
I put all the language files into Chinese, and I reload the plug-in, the contents of the file will all become English.

**Comment by BenLiHao** [comment]
I solved myself, the question now is, I put all the English into Chinese language, and how I sent to you, I hope you put zh.yml shared to everyone.

**Comment by NLthijs48** [comment]
I assume you now created a new file instead of directly changing an existing file?

If you send me the file with translations I will upload it to Transifex and include it into the next update.
Thanks for translation AreaShop to Chinese!

**Comment by BenLiHao** [comment]
thank you very much，I will improve the language file and send it to you.

**Comment by NLthijs48** [comment]
The translation by @BenLiHao has been uploaded to Transifex and will be included in the next update.
