### ISSUE TITLE
forsale bug

### ISSUE THREAD

**Issue by skippyaut** [NLthijs48/AreaShop#324]
changed:
rightClickPlayer:
        - 'areashop buy %region%'

to:
shiftRightClickConsole:
        - 'areashop message %clicker% %lang:confirm-buy|%region%|%'

but buying region in rightclick without confirm is still possible

    forsale:
      line1: '&2&l[Zu Verkaufen]'
      line2: '%region%'
      line3: '%price%'
      line4:
      shiftRightClickConsole:
        - 'areashop message %clicker% %lang:confirm-buy|%region%|%' # Alternative to first ask for confirmation (remove rightClickPlayer section)
      leftClickPlayer:
        - 'areashop info region %region%'

and "Click to buy" message + hover is not translateable (DE.yml) always shows english

- Areashop 2.4.0
- spigot 1.12

**Comment by skippyaut** [comment]
Same issue with forrent regions

**Comment by NLthijs48** [comment]
This bug has been fixed, for now you can leave an empty `rightClickPlayer: []` section to disable the direct buy command, in the next version of AreaShop your current config will work (you could download a development build [here](http://wiefferink.me:8080/job/AreaShop/)).

I think not all of the messages are in the DE.yml, to fix this you can copy the file to `skippyaut.yml`, set `language` in the config.yml file to `skyppyaut`. After this find the non-translated message in `EN.yml` and copy it to your new language file and translate it there.

You can also join the Transifex German translation team to help keeping the German language up-to-date, see [this page](https://github.com/NLthijs48/AreaShop/wiki/Language-support#translating-on-transifex).
