### ISSUE TITLE
Help me, the group.yml

### ISSUE THREAD

**Issue by rodnicho** [NLthijs48/AreaShop#329]
Hello everyone,

I would like to know more about the group.yml file

1) Can I say that a building is on behalf of a player?
2) Esque if I put a me like landlord, esque I will receive the pennies of purchase of rents?
3) [...] (there are too many questions to quote)
I have done all the wiki that are possible to read and understand but uncle answered all my questions

**Comment by NLthijs48** [comment]
1. Do you mean that a certain player should get the money from rents/buys? That is possible by setting the `landlord` option.
2. Yes

If you have more questions let me know.

**Comment by rodnicho** [comment]
Hello,

For the group.yml file:
I add a rental unit in the "Test" group,
When the player rents the money out of the trash,
Is it possible that an "owner" can get this money back?

I have no other question in just moment, its vien and its part :/

**Comment by NLthijs48** [comment]
If you set the landlord the money paid to rent the region will go to the landlord, that is what you want right? How do you mean get the money back? If there is a landlord AreaShop will take the money from the landlord at unrental and give it back to the renter.

If you need something else please try to explain it again to me in more detail, it is hard for me to understand your problem.

**Comment by NLthijs48** [comment]
I assume your problem has been solved.
