### ISSUE TITLE
Offline resell

### ISSUE THREAD

**Issue by M4rtyn4** [NLthijs48/AreaShop#332]
Hello,
I'm sorry, maybe its just me being blind but I can't find option to change time for offline player resell, not sure is it enabled at all. Would you be able to help me with this one please?
M4rtyn4

**Comment by NLthijs48** [comment]
Do you mean that a region owner should lose its region after being offline for X time? You can enable this feature in the `default.yml` file using `inactiveTimeUntilUnrent` and `inactiveTimeUntilSell`.

Let me know if that works for you.

**Comment by M4rtyn4** [comment]
Yes! Thank you.
