### ISSUE TITLE
Schematic Help

### ISSUE THREAD

**Issue by olivervincent** [NLthijs48/AreaShop#333]
#### Current behavior

Hello. I tryed to make a region when is rented, load a schematic to it.
I cant figure out to do it, i checked the default config and enabled the scematic option.
And tryed the /as schemevent command. 
I did also read this> https://github.com/NLthijs48/AreaShop/wiki/Region-blocks-save-restore

I just cant figure it out.

I hope someone can help :)

**Comment by olivervincent** [comment]
I have did also read this> https://github.com/NLthijs48/AreaShop/wiki/Region-blocks-save-restore

**Comment by NLthijs48** [comment]
I answered your question on Spigot: https://www.spigotmc.org/threads/areashop.43135/page-38#post-2528213

Please attach your `plugins/AreaShop` folder to this issue if you are still having trouble, then I'll check your configuration.

**Comment by NLthijs48** [comment]
I assume your problem is solved, closing the issue
