### ISSUE TITLE
limitGroups doesn't work

### ISSUE THREAD

**Issue by Behoston** [NLthijs48/AreaShop#335]
#### Current behavior
As normal user I can rent any regions from any group

#### New behavior
Limit should works.

#### Steps to reproduce (for bugs)
1. Just use my config  
2. try to rent one region from mieszkanie and one from pole

#### Your environment (for bugs)
* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 7228328-11323bf (MC: 1.12)
* AreaShop version: 2.4.0
* WorldEdit version: 6.1.7;dd00bb1 (With FAWE)
* WorldGuard version: 6.2.1;84bc322
* Vault version: 1.5.6-b49

#### Your config files (for bugs)
[AreaShop.zip](https://github.com/NLthijs48/AreaShop/files/1144305/AreaShop.zip)

**Comment by NLthijs48** [comment]
mieszkanie seems to be setup correctly, pole does not work because you have written 'grups' in the config.yml file in the limitGroups section. 

Did you give all your players the areashop.limits.pole and areashop.limits.mieszkanie permissions? Because without those the limits will not be active.

**Comment by Behoston** [comment]
so by default there is no limitation for renting? If I give `areashop.limits.<group>` then user have limitation on renting?

**Comment by NLthijs48** [comment]
The `areashop.limits.default` permissions is assigned to everyone by default, so only your `default` group will work currently. You have added a `groups` part to this limit group, so regions that are not in this group will be completely unrestricted, until you give everyone the `areashop.limits.pola` permission, which limits the regions bought in that group.

Let me know if after assigning that permission it works correctly.

PS: normally the `default` group limits people to either 1 buy or 1 rental region, but you have changed that one.

**Comment by Behoston** [comment]
THX
