### ISSUE TITLE
teleport

### ISSUE THREAD

**Issue by Davno** [NLthijs48/AreaShop#337]
Hey, how can i turn off the teleport feature?
I dont like this so i would like to deactivate this feature . 

pls help me

kinds regard 

Davno ;=)

**Comment by NLthijs48** [comment]
Give players a negative permission for all permissions that have (true) behind them listed below the `/as tp`: https://github.com/NLthijs48/AreaShop/wiki/Commands-and-Permissions#as-tp-region.

**Comment by Davno** [comment]
Thank you for your fast repley, i love your plugin and its already installed on my server blockarius :D 

Thank you again :D 

greets from austria :D

**Comment by NLthijs48** [comment]
Great to hear that, if you ever have other questions just let me know.
