### ISSUE TITLE
AreaShop Shop Reset suggestion

### ISSUE THREAD

**Issue by NAHVUS** [NLthijs48/AreaShop#339]
#### Current behavior
When player loses rent their shop stays like if they were still renting it

#### New behavior
Shop resets to when it was first set up

#### Steps to reproduce (for bugs)
1. Rent shop 
2. Place stuff in it
3. Unrent it or lose your rent
4. Stuff stays there

#### Your environment (for bugs)
git-Spigot-b78586d-753a8e7 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

* Server platform (Bukkit, Spigot, etc.): Spigot 1.12
* Server version: 1.12
* AreaShop version: 2.4.0
* WorldEdit version: 6.1.7;dd00bb1
* WorldGuard version: 6.2.1;84bc322
* Vault version: 1.5.6-b49

#### Your config files (for bugs)

[AreaShop.zip](https://github.com/NLthijs48/AreaShop/files/1163887/AreaShop.zip)

**Comment by EvilOlaf** [comment]
https://github.com/NLthijs48/AreaShop/wiki/Region-blocks-save-restore

**Comment by NLthijs48** [comment]
I assume your problem is solved, closing the issue
