### ISSUE TITLE
Change Teleport Command

### ISSUE THREAD

**Issue by TechGaming1** [NLthijs48/AreaShop#341]
RIght Now the Areashop plugin Is making players type /as tp (region name)
And They Are Complaining That its Such a Long Command

Could you Please Add it So i can set the /as tp command to /home
So Players Can type /home and it will teleport them to The Region they Own?

Is There anything You Can add or Suggest to me To fix this issue
Thanks.

**Comment by NLthijs48** [comment]
Using [commands.yml](https://bukkit.gamepedia.com/Commands.yml) you can create an alias for the command:
```yaml
aliases:
    home:
    - "areashop tp $1-"
```

After issue #39 is implemented the region argument will also be optional, making it even easier.

**Comment by NLthijs48** [comment]
I assume your problem is solved, closing the issue
