### ISSUE TITLE
Horse issue

### ISSUE THREAD

**Issue by Akarus95** [NLthijs48/AreaShop#343]
Hello,

I got a problem with the horses, if someone that doesn't own a region and get off his horse he can't ride up on the horse. We can't push the horse and if we punch him he doesn't move, he's like stuck on the floor. He has to wait the owner of the region and sometimes this owner has to disconnect/reconnect or go to the nether. Sometimes it works sometimes not. Do you have any way to fix this ?

Thanks,
Estro

**Comment by NLthijs48** [comment]
AreaShop cannot do anything about this. This is kinda a WorldGuard issue, but I understand why they have not done anything with horses. Horses don't have an owner as for example a tamed wolf has, so from the perspective of WorldGuard the owners of horse are the people that can use things in the region.

There might be a plugin that keeps tracks of who owns a horse and allows you to teleport it or something like this, I did not search for that yet though.

**Comment by NLthijs48** [comment]
I assume your problem is solved, closing the issue
