### ISSUE TITLE
Price per block

### ISSUE THREAD

**Issue by DarkShimy00** [NLthijs48/AreaShop#346]
Hi!

A nice feature that was present in _RegionForSale_ was the price-per-block option. It would be very useful to be able to set a price per block (m^2 and m^3).

Thanks!

**Comment by NLthijs48** [comment]
You can use variables in the `price` options of regions, which allows you to set a price per square or cubic block. I have added the details to the [FAQ](https://github.com/NLthijs48/AreaShop/wiki/Frequently-Asked-Questions#how-can-i-use-a-price-per-square-meter-m2-or-per-block-m3).

If you need more advanced pricing you can even use JavaScript expressions, for you case you don't need that though.

**Comment by Argorion** [comment]
Is it possible to get an example ? line 187 default.yml

rent:
  # The default price of a rental region.
  price: 50 

If I change it to    price: '5*%width%*%depth%*%height%'   nothing happens.
I get back a string I believe. but I need an integer.

helpful for me would be a complete configfile

**Comment by NLthijs48** [comment]
You missed the multiplication signs between the variables, should be like this:
```yaml
price: '5*%width%*%depth%*%height%'
```
This exact example is also in the FAQ. I don't see how it is useful to add the other stuff from the config to this example, you just need to change the price line.

**Comment by Argorion** [comment]
it was an error in message format here, sorry.

in YML I wrote it correct.

I can't understand this :-(

**Comment by Argorion** [comment]
I'm using 1.12 and Worldguard 6.2.1

**Comment by NLthijs48** [comment]
I'm sorry but I forgot that you need the development build of AreaShop, you can get it [here](http://wiefferink.me:8080/job/AreaShop/).

Let me know if it works after installing that.

**Comment by Argorion** [comment]
Cool. That's it. Thank you very much.
