### ISSUE TITLE
Players cannot use modded items, place modded blocks, chests inside areas

### ISSUE THREAD

**Issue by Eufranio** [NLthijs48/AreaShop#347]
Players cannot place modded blocks, use modded items, place chests, break blocks with modded items and etc inside a region he own. 

#### New behavior
He should be able to break/place inside areas that he own, like his shop or something.

#### Steps to reproduce (for bugs)
1. Created a big region named shopping
2. Created a small region named loja-1 inside shopping
3. A player rented it.
4. The player can NOT build, place, break, open, inside his own region. Region info: http://prntscr.com/g7cctc

#### Your environment (for bugs)
* Server platform (Bukkit, Spigot, etc.): Thermos
* Server version: 1.7.10, build 58
* AreaShop version: 2.4.0
* WorldEdit version: Bukkit 6.1.5, Forge 6.1.1
* WorldGuard version: 6.1
* Vault version: 1.5.6-b49

#### Your config files (for bugs)
[AreaShop.zip](https://github.com/NLthijs48/AreaShop/files/1218790/AreaShop.zip)

**Comment by NLthijs48** [comment]
What does `region info` for the big shopping region show? And what does `region info __global__` show? You might have something like `build: deny` on them preventing players from placing blocks etc. The flags on the region you are using with AreaShop look good.

If you manually create a region and add an owner/member, does it work or not?

I never tested AreaShop with Thermos myself, but I believe others are using it without problems. As long as WorldGuard does work, AreaShop should also work on Thermos.

**Comment by Eufranio** [comment]
`region info` from the shopping area: http://prntscr.com/g7cjnj
`/region info __global__`: http://prntscr.com/g7cjwq
I've created a new region, added the player as owner and it did work. So, I went to the loja-1 region and manually added the player, it did NOT work. I'm not sure why tbh...

**Comment by NLthijs48** [comment]
Flags of the other regions seem good. One option is to remove flags from the AreaShop region one by one until it works.

You can also try updating WorldGuard and WorldEdit to the latest versions, might make a difference.

**Comment by Eufranio** [comment]
Removing the `passthrough` flag from the region lets the player place/break/open blocks, but ONLY vanilla blocks. Modded blocks/items/anything, when right clicked, get cancelled and denied. So, if I have a pickaxe from a mod, it won't let me right click/left click blocks using it.

**Comment by Eufranio** [comment]
I believe it's a ForgeRestrictor issue, since it handles non-modded item actions, and the item is being confiscated from the inventory. Thanks for the support!

**Comment by NLthijs48** [comment]
Okey that might indeed be it if vanilla items work correctly.

If you have other questions about AreaShop let me know.
