### ISSUE TITLE
Issue with renting and unrenting

### ISSUE THREAD

**Issue by Hyger** [NLthijs48/AreaShop#349]
#### Current behavior

When attempting to rent or unrent a shop i'm getting the following errors.
-When renting: https://pastebin.com/pxg9mB9F
-When unrenting: https://pastebin.com/3peCCLEh

It's been a few versions since we last updated plugins (took about a year or so off) but, outside of that nothing strange has been done. Can confirm no issues when using older versions, although it would take me a minute to get their info. I haven't tried remaking the shops/regions yet, hoping I wont have to do all of that again if its a simple fix.

Thanks for your time, any help is greatly appreciated.

#### Steps to reproduce (for bugs)

1. When shop is setup and attempting to be rented (via sign)(first pastebin)
2. When shop is setup and attempting to be unrented (via sign) (second pastebin)
3. When shop is setup and attempting to be unrented (via command) (second pastebin)

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.12.1-R0.1-SNAPSHOT
* AreaShop version: 2.4.0
* WorldEdit version: 6.1.8-SNAPSHOT
* WorldGuard version: 6.2.2-SNAPSHOT
* Vault version: 1.6.1

#### Your config files (for bugs)

[AreaShop.zip](https://github.com/NLthijs48/AreaShop/files/1219463/AreaShop.zip)

**Comment by NLthijs48** [comment]
You have removed the `default` schematic profile in the `config.yml` file, while `default.yml` still tries to use the `default` schematic profile. This is what causes the error. Either add back this profile in the config or update to the [development build](http://wiefferink.me:8080/job/AreaShop/), which has fixed this issue.

**Comment by Hyger** [comment]
Thanks! I'll give it a try.

**Comment by NLthijs48** [comment]
I assume your issue is solved, closing the issue
