### ISSUE TITLE
Error while trying to rent an area

### ISSUE THREAD

**Issue by Blackyvk** [NLthijs48/AreaShop#35]
http://hastebin.com/jahigisigu.coffee

lastest commit

it fixes after setting landlord again with /as setlandlord... will report later after a server restart.

**Comment by Blackyvk** [comment]
Yes it broke after server restart, I even recreated all the config files and tested in a new region, same error. I went back to the build i had when you fixed it first and works fine again.

**Comment by NLthijs48** [comment]
The linked patch should solve this problem, also improved the handling of missing player files for region owners. Let me know if this version works as expected.

**Comment by Blackyvk** [comment]
Seems to be working fine for now, thanks again!

**Comment by NLthijs48** [comment]
Nice, I have just published V2.2.0 of AreaShop on BukkitDev, Spigot and GitHub so you can also use that version now.
