### ISSUE TITLE
Error on enableRestore 

### ISSUE THREAD

**Issue by erik1988** [NLthijs48/AreaShop#351]
Sorry of uploading a picture of the error but this error caused my log file to be 8GB.

https://ibb.co/kzRoPv

I think this happened because I switched  enableRestore to true. I guess since people had already rented regions before I turned it on it may have caused an error, that eventually spammed by console and lead to 4 fps. 

All I wanted to do is to clear the region completely when the rent goes out, since the regions have different sizes I dont know what to do.

**Comment by NLthijs48** [comment]
I think you simply need to update WorldEdit, this is an error of some internals of WorldEdit. Let me know if that fixes it, because AreaShop cannot do anything about this.

**Comment by NLthijs48** [comment]
I assume your issue is solved, closing the issue
