### ISSUE TITLE
Schematics error in 1.12.1

### ISSUE THREAD

**Issue by Prowco** [NLthijs48/AreaShop#352]
#### Current behavior

I follow all your steps
Define a region test1
Select a region test1
//copy
//schem save mcedit test1
move the schematic test1 from world edit file to area shop schematic files
put the region test1 for rent
set restore test1 true test1 
and then reload the server all follow your steps
but when i unrent the region errors start in console
this is the errors i get https://pastebin.com/SdaHyFi1
can you help me please?

#### Steps to reproduce (for bugs)

1. 
2. 
3. 
4. 

#### Your environment (for bugs)
 2.4.0

* Server platform (Bukkit, Spigot, etc.): PaperSpigot
* Server version:  1.12.1
* AreaShop version: 2.4.0
* WorldEdit version: 6.3
* WorldGuard version: dont remember lastest but works fine
* Vault version:

**Comment by NLthijs48** [comment]
You changed the schematic profile for the `test1` region to `test1`. This means that the region will look in the `config.yml` file for the `test1` schematic profile, which does not exist and causes this error.

Simply use `as setrestore test1 true default` and after that use `as schemevent test1 created`, which will save the schematic for it by itself, there is no need to save schematics manually.

Let me know if you got it working by following this.

**Comment by Prowco** [comment]
and another question, is some way for restore at the same time the parent regions? bc the house have a irregular form so

**Comment by Prowco** [comment]
i try your solution as setrestonre test1 true default and after that as schemevent test1 created, but when i use the second comand as schemevent test1 created i get this error https://pastebin.com/hBkGZbXg

**Comment by NLthijs48** [comment]
Still the same problem, upgrade to the [development build](http://wiefferink.me:8080/job/AreaShop/) of Areashop and you will at least not get any errors, your setup will still be wrong though. If you want to fix that please send me your `plugins/AreaShop` folder (you can zip/rar it and attach it to this issue).

**Comment by Prowco** [comment]
http://www.mediafire.com/file/4mttq17goyoscck/Area.zip

**Comment by Prowco** [comment]
Ok now look i try you Development Build and i select the region then /region define test1 then i put the sign for rent outside then i put as setrestore test1 true default and last i put as schemevent test1 created and all works perfect BUT when my rent expire the apartment continue with all the blocks i put, i want when the rent expire the apartment clear and remove all the blocks and make the aparment empty you understand what i mean?

**Comment by NLthijs48** [comment]
Instead of `as setrestore test1 true default` use `as setrestore test1 true`. Setting the profile without having a profile with that name in the `config.yml` file will simply disable schematics.

**Comment by NLthijs48** [comment]
I assume your issue is solved, closing the issue
