### ISSUE TITLE
Rents won't expire automatically.

### ISSUE THREAD

**Issue by TerracePalmMC** [NLthijs48/AreaShop#353]
#### Current behavior
We use AreaShop for jail cells, but they don't expire automatically. Using /unrent <name> works.

#### New behavior
Cells should expire after their renting period has expired.

#### Steps to reproduce (for bugs)
1. Rent any cell.
2. Wait or change the time on your computer.
3. ???
4. Nothing happens.

#### Your environment (for bugs)
* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.8.8-R0.1-SNAPSHOT
* AreaShop version: 2.4.0
* WorldEdit version: 6.1.5
* WorldGuard version: 6.1.3
* Vault version: 1.5.6-b49

#### Your config files (for bugs)
[AreaShop.zip](https://github.com/NLthijs48/AreaShop/files/1261059/AreaShop.zip)

**Comment by NLthijs48** [comment]
You need to add back the [English time indicators](https://github.com/NLthijs48/AreaShop/blob/master/AreaShop/src/main/resources/config.yml#L57) or install the [development build](http://wiefferink.me:8080/job/AreaShop/) of AreaShop. If you want to do the first option, you can keep your Spanish? indicators, simply add both to the lists.

**Comment by TerracePalmMC** [comment]
That's what I started suspecting right after I looked at the region YML files right before uploading the ZIP.
I used the development build, let's see if that works. Oh and yes, they are Spanish time indicators, except for one little typo that somehow got in there and is now fixed.
