### ISSUE TITLE
Variables for the config.yml settings  (issue)

### ISSUE THREAD

**Issue by skippyaut** [NLthijs48/AreaShop#354]
This Variable shows not the current month! It shows one month behind.

%month% | The current month in the year.

-skippyaut-

**Comment by NLthijs48** [comment]
Good catch, fixed it!

In a few minutes you can find a development build [here](http://wiefferink.me:8080/job/AreaShop/) that includes the fix (build 175 is building now)

**Comment by skippyaut** [comment]
Nice thanks!

Awesome support

:)
