### ISSUE TITLE
[request] Dynamic shop pricing based on size of WG region.

### ISSUE THREAD

**Issue by FrozenBeard** [NLthijs48/AreaShop#357]
I generate my costs of my shops based on the size of the region (blocks), This could easily be automated, having a config option with some math expression in it to auto generate costs would be amazing. we have a base cost given in groups, it would be awesome to have something like

```
costGenerator: '%regionBlocks%/2+10'
```
So then its totally customizable!

**Comment by NLthijs48** [comment]
In the next AreaShop version (development build for this can be found [here](http://wiefferink.me:8080/job/AreaShop/)) this is already possible, see [this FAQ item](https://github.com/NLthijs48/AreaShop/wiki/Frequently-Asked-Questions#how-can-i-use-a-price-per-square-meter-m2-or-per-block-m3). 

This feature allows exactly what you want, even offering full Javascript if you want to calculate a complicated price.

Let me know if you miss anything with this feature, otherwise it looks like we can close this issue 😃

**Comment by FrozenBeard** [comment]
Holy smokes! Now that, is awesome news haha! its even already in the same format as I requested, thats so amazing. So I can use this now in the dev build?  My javascript sucks, so you have any examples?

**Comment by NLthijs48** [comment]
If you explain what kind of pricing you want I can write something for you. Basically any code or expression can be used, the expression on the last line will be the price.

**Comment by FrozenBeard** [comment]
I think I figured it out with a spreadsheet, %width%*%depth%*%height% does give you all the blocks in that region right? (My maths is terrible!) if so then **4*%width%*%depth%*%height%/100** should be near enough for me, can we use floats? I might be able to make small adjustments then to that 4*, 4.1 etc.

**Comment by NLthijs48** [comment]
You need a multiplication sign `*` between the width, depth and height variables, so you would get something like this:
`4*%width%*%depth%*%height%/100`

You can use floating point numbers, so you can indeed use `4.1`

**Comment by FrozenBeard** [comment]
oh yeah! Half asleep when I wrote that, So to update all my shops in a group, I update the Jar, then I can change the price in my groups.yml for all shops. Will this be auto updated when I boot the server? or will I need to run a command to update their prices?

**Comment by FrozenBeard** [comment]
Alright, so how does this work for Polygon WG Regions? There is no Width/Height as there all random shapes, I just realized this as my entire set of shops is all like this and the maths didn't match my spreadsheet when I tested this out.


Also the only method I found to update the shops to what I set in the group, was to;
1) as del, delete the shop
2) re-create it
3) re-add it to the group! (Why did it delete it from the group!?)
4) Re-create my signs

Why cant there be a command to update all items in a group to what I have set in that group? /as updategroup shops, updates all shops to the data in the group file.

I have over 80 shops, This is a massively tedious job for something that could be a command!

**Comment by NLthijs48** [comment]
> Will this be auto updated when I boot the server?

Yes, restarting the server or using `/as reload` loads all config files again. The problem you are facing though is that you have previously set a price for each region individually. This means that the file of the region `/plugins/AreaShop/regions/<regionName>.yml` contains a price, which causes that AreaShop always uses that price. See [this page](https://github.com/NLthijs48/AreaShop/wiki/The-config-system) (especially the image) to see how AreaShop decides which source to use for a setting.

So to fix this problem you need to remove the `price:` lines from the region files, which currently needs to be done one-by-one. I recommend using [TextCrawler](https://www.digitalvolcano.co.uk/textcrawler.html) and running a search and replace on all region files, which saves you some time.

Make sure that when using signs with AreaShop you only specify the region name, no price or duration. Then the region will just use the price from `default.yml` or from the groups if you later add those.

I created issue #359 for adding a command to perform these kind of bulk modifications, it takes some time to implement though.

> Alright, so how does this work for Polygon WG Regions? There is no Width/Height as there all random shapes, I just realized this as my entire set of shops is all like this and the maths didn't match my spreadsheet when I tested this out.

The width, height and depth variables will be based on the outer bounding box of the polygon regions, so your price will be a bit too high. I added the `%volume%` variable to fix this, the variable properly gives you the number of blocks in a polygon region (calculated by WorldGuard). Development builds that include this new variable can be found [here](http://wiefferink.me:8080/job/AreaShop/).


Let me know if your setup works now 😄

**Comment by NLthijs48** [comment]
A fix for the `%volume%` variable is rolling out: 33ddb8ae888c530be55244184a074dfc6e618663 😃

**Comment by NLthijs48** [comment]
Closing the issue, if you have other questions let me know
