### ISSUE TITLE
Error on build 202

### ISSUE THREAD

**Issue by M1SM4TCH** [NLthijs48/AreaShop#368]
#### Current behavior
On start server with AreaShop b198 that error don't happen, but with b202 happens.
https://hastebin.com/ejobomulet.vbs

#### Steps to reproduce (for bugs)
1. Use AreaShop b202 and ShopChest 1.12.3
2. Done

#### Your environment (for bugs)
* Server platform (Bukkit, Spigot, etc.):-PaperSpigot
* Server version: 1.8.8
* AreaShop version: Devbuild 202
* WorldEdit version: 6.1.7.3
* WorldGuard version: 6.2
* Vault version: 1.6.1

#### Your config files (for bugs)
[AreaShop.zip](https://github.com/NLthijs48/AreaShop/files/1504851/AreaShop.zip)

**Comment by NLthijs48** [comment]
Fixed in 6b59176048212cad756c86e66f21bfa8b5b0ce8d, the next development build should work again.

Thanks for reporting this issue!
