### ISSUE TITLE
Support for removing QuickShop shops

### ISSUE THREAD

**Issue by NLthijs48** [NLthijs48/AreaShop#37]
A way to automatically remove QuickShop things at region unrent/sell. Plugin page: [QuickShop (BukkitDev)](http://dev.bukkit.org/bukkit-plugins/quickshop-notlikeme/).

**Implementation:**
Depends on an integration/event API within AreaShop, would also allow for #19.

*Suggested by felixchat62 ([BukkitDev comment 850](http://dev.bukkit.org/bukkit-plugins/regionbuyandrent/?comment=850))*

**Comment by c0wg0d** [comment]
I just added "qs clean" as a command that runs after an unrent event.  Works great.

**Comment by NLthijs48** [comment]
Although the description says this:
> /qs clean - Removes any existing shop that has 0 stock.

**Comment by NLthijs48** [comment]
Merged into #19
