### ISSUE TITLE
Customizable metric suffix characters

### ISSUE THREAD

**Issue by esquerbatua** [NLthijs48/AreaShop#373]
#### Current behavior
Money shows like: 10, 3M, 10G

#### New behavior
Money format values, like: 1, 10k, 10M, 1B, 1T, etc

Is there any way to have formated values for the money?

#### Environment
* Server platform: Spigot
* Server version: 1.8.8
* AreaShop version: 2.4.0

**Comment by NLthijs48** [comment]
There is a setting `metricSuffixesAbove` in the `config.yml` file, if you put that to `1` AreaShop will also use `10k`. The used letters are as specified in the [standard on Wikipedia](https://en.wikipedia.org/wiki/Metric_prefix).

Let me know if that solves your problem.

**Comment by esquerbatua** [comment]
I tried to reload the plugin and I will try to restart the server. If doesn't work I will send you the folder.

**Comment by esquerbatua** [comment]
Doesn't work with the restart. Here have the folder.

[AreaShop_.zip](https://github.com/NLthijs48/AreaShop/files/1573201/AreaShop_.zip)

**Comment by NLthijs48** [comment]
`metricSuffixesAbove: 1000000.0`

You did not change the setting to `1`, so currently AreaShop will only use the letters for numbers above 1000000.

**Comment by esquerbatua** [comment]
Sorry I made the changes in my main server after I send you the folder, don't work with 1 either.

**Comment by NLthijs48** [comment]
It immediately works for me, so there must be something wrong with your setup.

Where are you checking the price of the region and expect it to use the letters? Because maybe it is not displaying a formatted price at that location, and only a raw number.

![screenshot_3](https://user-images.githubusercontent.com/6951068/34302702-61d5dd60-e732-11e7-940d-46b8bc112ff9.png)

**Comment by esquerbatua** [comment]
try with a quantity of 10000000000

**Comment by NLthijs48** [comment]
Also works:

![screenshot_4](https://user-images.githubusercontent.com/6951068/34303277-f0f5f99c-e734-11e7-91a1-95e39453d666.png)

**Comment by esquerbatua** [comment]
> Current behavior
> Money shows like: 10, 3M, 10G
> 
> New behavior
> Money format values, like: 1, 10k, 10M, 1B, 1T, etc
> 
> Is there any way to have formated values for the money?
> 
> Environment
> Server platform: Spigot
> Server version: 1.8.8
> AreaShop version: 2.4.0

**Comment by NLthijs48** [comment]
Now I get what you want to do, you simply want to change the letter that is used LOL.

I'll create some settings to do this.

**Comment by esquerbatua** [comment]
Okey, a lot of thanks!
And sorry, my english is so bad and I'm not the best explaining me.

**Comment by NLthijs48** [comment]
Settings could be like this:
```yaml
# Use metric suffixes if the price is above this number (use 1.00M instead of 1000000.00 etc.), use -1 to disable.
# Indications are used as defined on: http://en.wikipedia.org/wiki/Metric_prefix, implemented from 'k' to 'Y'.
metricSuffixesAbove: 1000000.0
# Symbols to use for the metric suffixes
metricSymbols:
  1000: "k"
  1000000: "M"
  1000000000: "G"
  1000000000000: "T"
  1000000000000000: "P"
  1000000000000000000: "E"
  1000000000000000000000: "Z"
  1000000000000000000000000: "Y"
```

There is a technical problem with configuation defaults of sections in config.yml not working though, which would break this feature for old users. Working on a fix soon.

**Comment by esquerbatua** [comment]
Okey, thanks for your time and a lot of thanks!

**Comment by NLthijs48** [comment]
This has been added to the development build now

**Comment by esquerbatua** [comment]
A lot of thanks and sorry by the late response.
