### ISSUE TITLE
Compatibility Issues with WorldGuard

### ISSUE THREAD

**Issue by juanpimq** [NLthijs48/AreaShop#375]
#### Current behavior

It should work with WorldGuard
![error_area_shop](https://user-images.githubusercontent.com/34761681/34286310-601e2d20-e6a5-11e7-8b8c-04f637c9fb89.png)

#### Steps to reproduce (for bugs)

1. //Pos1 //Pos2
2. //Expand vert
3. //region define "region name"
4. then trying to add a rent sign

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): 
* Server version: spigot-1.12.1
* AreaShop version: 2.4.0
* WorldEdit version: v6.1.8-SNAPSHOT;cd4729f
* WorldGuard version: v6.2.1;84bc322
* Vault version: v1.6.1

#### Your config files (for bugs)

[config.yml.zip](https://github.com/NLthijs48/AreaShop/files/1581464/config.yml.zip)
#

**Comment by EvilOlaf** [comment]
Did you try to add this region to AS before trying to create the sign?
Use `as add rent` or `as add buy`. After successfully added retry creating the sign.

**Comment by NLthijs48** [comment]
This message shows up if AreaShop cannot get the region from WorldGuard using the name you specified on the second line of the sign. 

What did you type on the sign? Did you use the `[as]` tag or the `[asrent]` tag? Is the region is new and not yet added to AreaShop, the `[asrent]` tag should be used. If you want to add a sign to an existing AreaShop region, use the `[as]` tag.

**Comment by juanpimq** [comment]
![error](https://user-images.githubusercontent.com/34761681/34303793-a4c7684a-e6fc-11e7-9a08-cc6256bb42af.png)
![sign](https://user-images.githubusercontent.com/34761681/34303794-a4f47e98-e6fc-11e7-9496-0474a04c5a68.png)

**Comment by NLthijs48** [comment]
When you have already added the region with `/as add` you need to use a sign with `[as]` as the first line, this will add the sign to the existing region.

**Comment by juanpimq** [comment]
[UPDATE]: So I looked at my console and I had an error with LWC plugin. I looked more into it and that error was causing WoldGuard and other plugins to malfunction. That's why I wasn't able to add regions with and method. So I reinstalled LWC and now everything works fine.
