### ISSUE TITLE
Landlord doesn't receive funds

### ISSUE THREAD

**Issue by HariBearGB** [NLthijs48/AreaShop#378]
#### Current behavior
When somebody clicks to rent a region the landlord does not receive the money.

#### New behavior
The landlord should be receiving payment.

#### Steps to reproduce (for bugs)
It's the base AreaShop plugin, nothing added,

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.12.2
* AreaShop version: 2.4.0
* WorldEdit version: 6.1.8
* WorldGuard version: 6.2.1 
* Vault version: 1.5.6

#### Your config files (for bugs)
[AreaShop.zip](https://github.com/NLthijs48/AreaShop/files/1595143/AreaShop.zip)

**Comment by NLthijs48** [comment]
There is a single region in your zip file called `rocheapt2`, and for this region there is no landlord. Did you add a landlord by using `/as setlandlord <player> [region]`?

**Comment by HariBearGB** [comment]
Thanks that worked! Is there a way to automate this process?

**Comment by NLthijs48** [comment]
You could add a landlord to all regions by adding it to `default.yml` in the landlord settings. Or you could add a bunch of regions to a region group (`/as groupadd`) and add the landlord to that group.

Let me know if you need more information.
