### ISSUE TITLE
Chest-access for only the owner of the region.

### ISSUE THREAD

**Issue by TheUniqueGamer** [NLthijs48/AreaShop#38]
Can you please help me set up this?  Me and a Buddy have been trying to get it going. we have a spawn and want to put a mall (shops) in it. We have tried everything and still dont know what to do.We have watched the videos and still aren't sure what we are doing wrong. We have a world guard region called Spawn. And each shop is regioned off and signs are set, and i have set the priority to -1 and the shops to 0 or 1 and. But I cant open chests, can place blocks and break things, but you cant break or open chests. (as the owner of the shop, when renting the area) 

 Please Help. ~Thanks

**Comment by NLthijs48** [comment]
Did you change anything in the 'flagProfiles' section of the AreaShop config.yml file? Did you add any flags to the shop region yourself? (in particular a chest-access flag). Normally everyone should be able to use chests, unless disabled. So I think that you might have disabled chest usage. For the correct flag for chest-access, see [this page](http://dev.bukkit.org/bukkit-plugins/regionbuyandrent/pages/faq/#w-__-how-to-prevent-players-from-opening-chests-in-regions).

Let me know if that fixes your problem.

**Comment by TheUniqueGamer** [comment]
THANKS SO MUCH! Got everything working now!!!!!!!!!!! :D

**Comment by NLthijs48** [comment]
Nice, let me know if you have any other question.
