### ISSUE TITLE
Automatic schematic pasting for each shop upon unrenting

### ISSUE THREAD

**Issue by PassTheMayo** [NLthijs48/AreaShop#380]
#### Current behavior

When someone rents a shop, and then un-rents it, it is only possible to revert to one schematic design for all shops.

#### New behavior

Be able to define a different schematic for each different shop, so if each shop is different, then it will correctly load the original design back into the area. Here is why I need this to be a thing:
![image](https://user-images.githubusercontent.com/16949253/34644628-a0bc2308-f2ff-11e7-8f16-7972b6eb9372.png)
Each of the houses above have different styles, and are rotated differently. As of now, only one schematic can be used for each house, and that will totally mess up how we use our shops.

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): PaperSpigot
* Server version: git-Paper-1286 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
* AreaShop version: 2.4.0
* WorldEdit version: 6.1.8-SNAPSHOT;cd4729f
* WorldGuard version: 6.2.1;84bc322
* Vault version: 1.5.6-b49

**Comment by PassTheMayo** [comment]
Never mind, I figured out that you can use `/as setrestore` instead.

**Comment by NLthijs48** [comment]
If you simply set `enableRestore` in `default.yml` to `true` AreaShop will save a schematic for each house when a player rents the region, and restores it when the rent runs out. So in that case each house uses its own schematic. If you want to share some schematics, the `flagProfile` section in `default.yml` can be changed to let regions use specific file names for their schematics. These settings can also be changed for groups of regions with `groups.yml` and for individual regions.

**Comment by PassTheMayo** [comment]
Ok, thanks!
