### ISSUE TITLE
When rent time expires, region doesn't unrent

### ISSUE THREAD

**Issue by CheckeRr** [NLthijs48/AreaShop#382]
When I rent the region to 10:24 it doesn't unrent when time expires

In default config is the same situation

* Server platform (Bukkit, Spigot, etc.):  Paperspigot
* Server version: 1.12.2
* AreaShop version: 2.4.0
* WorldEdit version:  newest
* WorldGuard version:  newest
* Vault version:  newest

**Comment by NLthijs48** [comment]
Did you change the time identifiers in the `config.yml` file? Reverting them to English or installing the [development build](http://wiefferink.me:8080/job/AreaShop/) should fix this problem in that case.

If that is not the problem, could you send me your config files? An archive of `/plugins/AreaShop` would be easiest.

**Comment by CheckeRr** [comment]
I fix it. I download development build and all works fine.
