### ISSUE TITLE
Placeholder %uuid% doesn't work when selling region

### ISSUE THREAD

**Issue by Behoston** [NLthijs48/AreaShop#383]
#### Current behavior
I have saved regions
```
dzialka_44-raw.schematic
dzialka_44-%uuid%.schematic
```

#### New behavior
I want to save player ID with region name to restore later (restoring works fine, but can't find file with proper UUID)
```dzialka_44-raw.schematic
dzialka_44-0000-0000-0000-0000-0000.schematic
```

#### Steps to reproduce (for bugs)
Use this config:
```  enableRestore: true
  schematicProfile:
    created:
      save: '%region%-raw'
      restore: ''
    deleted:
      save: ''
      restore: '%region%-raw'
    rented:
      save: '%region%-raw'
      restore: '%uuid%-%region%'
    unrented:
      save: '%uuid%-%region%'
      restore: '%region%-raw'
    bought:
      save: '%region%-raw'
      restore: '%region%-%uuid%'
    sold:
      save: '%region%-%uuid%'
      restore: '%region%-raw'
    resell:
      save: ''
      restore: ''
```

#### Your environment (for bugs)
* Server platform (Bukkit, Spigot, etc.):  Paper
* Server version: 1.12.2 (always latest)
* AreaShop version: dev build 218

**Comment by NLthijs48** [comment]
Thanks for your report, this indeed was inconsistent. For rental regions the `%uuid%` variable was already available for schematic save/restore when a region was unrented, but for buy regions the buyer was removed from the region before triggering the schematics.

I have fixed the issue, the [latest development build](http://wiefferink.me:8080/job/AreaShop/) should work for you now.
