### ISSUE TITLE
Regions not resetting

### ISSUE THREAD

**Issue by Ironic8b498** [NLthijs48/AreaShop#386]
#### Current behavior

I when I create a region the Schematic is not created, at end of rent the region is not reset.
When I delete the Areashop folder and restart server I get same old config

#### New behavior

I when I create a region the Schematic is created, at end of rent the region is reset.
When I delete the Areashop folder and restart server I get a default config to setup

#### Steps to reproduce (for bugs)

1. 
2. 
3. 
4. 

#### Your environment (for bugs)

 

* Server platform (Bukkit, Spigot, etc.): 
* Server version:  Spigot 1.12.2
* AreaShop version: AreaShop-#219 or AreaShop-2.4.0 I tried with both
* WorldEdit version: worldedit-bukkit-6.1.9-SNAPSHOT-dist-#3730
* WorldGuard version: worldguard-legacy-6.2.2-SNAPSHOT-dist-#1712
* Vault version: Vault-1.5.6

#### Your config files (for bugs)

https://www.dropbox.com/s/5f18cor6f0uohqr/latest.zip?dl=0

**Comment by NLthijs48** [comment]
Found it, debug tells schematics are not enabled:
`[07:52:34] [Server thread/INFO]: [AreaShop] Debug: Schematic operations for Room_103 not enabled, skipped`
And in your default.yml you have `enableRestore: true` at line 11, but at line 137 there is `enableRestore: false`, which overrides (YAML will use the last value). So setting that to `true` should fix the problem. Looks like you copied the settings from the latest AreaShop into your old config, accidentally duplicating this setting.

Let me know if that solves the problem!

**Comment by Ironic8b498** [comment]
well that solved the problem of restoring after rent expires, now to fix the rent I was testing with, it will not not let me create a new rent. It was before I changed enableRestore:  to true. Also I have tried to fix my configs after you said I had an older config, after deleting the folder and starting the server it gave me back the same files

**Comment by Ironic8b498** [comment]
I fixed it by shutting down server and then deleting the folder and rebuilding the default and config files and replacing region and schematic files. I might of deleted folder and then rebooted server this morning.

**Comment by NLthijs48** [comment]
`it will not not let me create a new rent` why not? What kind of message did you get?

Seems quite impossible that AreaShop would give you the same old config.yml and default.yml if you have installed a newer version.

Good that it is working now though, I'll close the issue.
