### ISSUE TITLE
Updated to build #223 and the AS Signs stopped working.

### ISSUE THREAD

**Issue by FrozenBeard** [NLthijs48/AreaShop#393]
Simple, I updated to dev build 223 on my main serer and my signs stopped working.

**Comment by NLthijs48** [comment]
I need a bit more information, on my test server them seem fine.

1. Does clicking them work?
1. Does `/as info region <region>` show `Connected signs: ...`? 
1. Does adding a new sign work properly?
1. Is there anything special in the log file when starting the server or when trying to use the signs?

Could you also send me your `/plugins/AreaShop` folder? I could test it with your configuration files if I have that.

You could also open a chat at https://99messages.com/areashop to solve this quicker (the next couple of hours I'm available).

**Comment by FrozenBeard** [comment]
They randomly started working again, I have no idea how, I updated spigot again? maybe that was it?

**Comment by NLthijs48** [comment]
Okey, it might have been a Spigot issue. If you experience problems again, open a new issue or send me a message at https://99messages.com/areashop
