### ISSUE TITLE
Unrenting without refunding

### ISSUE THREAD

**Issue by RoboMWM** [NLthijs48/AreaShop#396]
Is it possible to unrent regions without refunding the owner? Either via administratively or on player unrent will work just fine - I want rent/extensions to be final, so players don't just hold them forever and/or rent and unrent regions willy nilly.

(I have disabled unrenting via permissions, but it still refunds on administrative use.)

**Comment by NLthijs48** [comment]
Set `moneyBack` in default.yml to `0` and there will be no refund. So you can still allow players to unrent, which will not give them any money back now.

**Comment by RoboMWM** [comment]
Thanks, didn't notice this. 👍
