### ISSUE TITLE
How to manual reset region?

### ISSUE THREAD

**Issue by Ziomkeee** [NLthijs48/AreaShop#398]
#### Current behavior

I do not know how to manually reset the region ..

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): 
* Server version: 
* AreaShop version: 2.4.0
* WorldEdit version: 6.1.8
* WorldGuard version: 6.2.1
* Vault version: 1.5.6

**Comment by NLthijs48** [comment]
Answered on Spigot: https://www.spigotmc.org/threads/areashop.43135/page-45#post-3009005
