### ISSUE TITLE
Block add friends for specific groups

### ISSUE THREAD

**Issue by dejakob1** [NLthijs48/AreaShop#405]
#### Current behavior

Hello, is it possible to block the "add friend" option to specific groups?
I don't want players to add friends to their farm plots.

#### Steps to reproduce (for bugs)

1. 
2. 
3. 
4. 

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): 
* Server version: 
* AreaShop version: 
* WorldEdit version: 
* WorldGuard version: 
* Vault version:

**Comment by dejakob1** [comment]
That would be lovely!
I have another question, I can open another ticket for it if you want.
I don't think it's possible but here's my setup:

A player can have:
1 farm (rent)
1 shop (rent)
1 house (buy)

But now we're converting our buyable houses to renting but because it's gonna be a very tedious process of players having to move out etc we're making the new added houses already rentable.
This has lead to players having 1 rentable house and 1 buyable. We told them this wasn't allowed but is there a way to limit this?

I was thinking this:
limitGroups:
  default:
    total: 3
    rents: 3
    buys: 1
  shops:
    total: 1
    rents: 1
    buys: 0
    groups:
    - 'shops'
  farmplots:
    total: 1
    rents: 1
    buys: 0
    groups:
    - 'farmplots'

Like this they can rent 3 plots and buy 1 but only have 3 plots in total. Is this possible?

**Comment by NLthijs48** [comment]
That is possible, you actually got the groups exactly like you should. Just assign those groups to all players with permissions and you are done.

Further documentation is on https://github.com/NLthijs48/AreaShop/wiki/Limitgroups-information-and-examples.
