### ISSUE TITLE
Players can still use buy signs without the permission.

### ISSUE THREAD

**Issue by hoffarthaustin** [NLthijs48/AreaShop#407]
Hello, How do i make it so they can't use buy signs or /as buy without the permission.. currently they can without it... I only want them to be able to rent.

**Comment by NLthijs48** [comment]
Regions are either rental or buy regions, so if you created a rental region there is no way for a player to buy it.

So it looks like you are misunderstanding something.

**Comment by hoffarthaustin** [comment]
I don’t have anything misunderstood. I have rent regions and buy regions which are separate. I only want players to be able to rent regions not buy them. Currently with only the Asrent permission they are still able to buy regions even without the Asbuy permission

**Comment by frizzbee30** [comment]
NLthijs48 is quite right, if you set a region to be a rent region, it cannot be bought, it will always force rental.

If you mean they can buy the 'buy' regions, without the permission node, it sounds like you have a perm config issue with your permissions plugin.  :)

**Comment by NLthijs48** [comment]
Permissions to buy/rent region are assigned by default, so to remove the permission you need to give player a negative permission for `areashop.buy` or `areashop.rent`.
