### ISSUE TITLE
/as tp permission issue

### ISSUE THREAD

**Issue by xNccPlay** [NLthijs48/AreaShop#420]
**Current behavior**
/as tp is working, while the permission is not granted

**Expected behavior**
Only the following permissions are added to the affected group:
areashop.addfriend
areashop.buy
areashop.delfriend
areashop.help
areashop.me
areashop.rent
areashop.resell
areashop.sellown
areashop.stopresell
areashop.unrentown

Permissions-Plugin: LuckPerms

**Your environment**

* Server platform (Bukkit, Spigot, etc.): Thermos (b58)
* Server version: 1.7.10
* AreaShop version: 2.2.2
* WorldEdit version: 6.1.7.3
* WorldGuard version: 6.1
* Vault version: 1.4.1

**Your config files**
[Configs.zip](https://github.com/NLthijs48/AreaShop/files/2321470/Configs.zip)

**Comment by NLthijs48** [comment]
AreaShop assigns a list of permissions by default, see all permission nodes with (true) behind them on this page: https://github.com/NLthijs48/AreaShop/wiki/Commands-and-Permissions

To disable teleporting you need to remove all teleport permissions using a negative permission node. Let me know if that works for you.

**Comment by xNccPlay** [comment]
Thank you for your reply, I changed the permissions like you told me and it seems to work :)
If I'm right, I don't need to grant permissions with "true" behind the node? Only OP nodes need to be assigned?

**Comment by NLthijs48** [comment]
Yes that is it
