### ISSUE TITLE
No permissions

### ISSUE THREAD

**Issue by Twiistrz** [NLthijs48/AreaShop#426]
**Current behavior**

![image](https://user-images.githubusercontent.com/25744238/45948106-552ced80-c029-11e8-9b01-a1c748eebef2.png)

already have the areashop.teleport permission still not working

**Expected behavior**

Teleport to a region

**Your environment**

* Server platform (Bukkit, Spigot, etc.): CraftBukkit version git-Spigot-642f6d2-ca6d2cf
* Server version: MC: 1.12.2
* AreaShop version: 2.4.0
* WorldEdit version: 6.1.8-SNAPSHOT;cd4729f
* WorldGuard version: 6.2.1;84bc322
* Vault version: 1.6.7-b${env.TRAVIS_BUILD_NUMBER}

**Your config files**

https://hastebin.com/peweyozico.makefile

**Comment by Roper89** [comment]
@Twiistrz
Permissions do not need to be added if you want teleport to work for your players.
By adding the "areashop.teleport" permission, you only forbid using the teleporter. :)

**Comment by Twiistrz** [comment]
Thanks i just add areashop.teleportAll and it now works
