### ISSUE TITLE
Skull Owner

### ISSUE THREAD

**Issue by SeDark** [NLthijs48/AreaShop#431]
I propose that above the block where the sign is displayed the head of the owner of the region, many other plugins have functions like these and gives a lot of play.

If implemented, I propose that you can choose when the head appears, for example when the user rents the region for 1 month.

**Comment by NLthijs48** [comment]
A feature like this has been suggested before, see #61, it would be a very low priority thing to implement. It is a bit complex to do correctly, and honestly I'm not sure how many people would use it.
