### ISSUE TITLE
FastAsyncWorldEdit support

### ISSUE THREAD

**Issue by mibby** [NLthijs48/AreaShop#436]
Would it be possible to extend support to WorldGuard 7 and FastAsyncWorldEdit for 1.13?

i.e. 
https://github.com/boy0001/AreaShop/commit/aaf9e553ad2078725a9a9589b56e780441aa87c1

https://github.com/pmme/AreaShop/commit/f548e9e1269cceb30215ee0f0827348dc6648c0a

**Comment by NLthijs48** [comment]
I would like to support FAWE, the approach taken in the linked commits is not what I want though. I would like to keep depending on the original WorldEdit and WorldGuard, while ensuring I use methods that are compatible with FAWE. Or if that does not work, create an additional integration that hooks into FAWE.

**Comment by NLthijs48** [comment]
2483cf16147dafb85cb7cd67051bf4f67c7891c9 should be a first step towards FAWE support, if someone already likes to try out the latest [developer build](http://wiefferink.me:8080/job/AreaShop/) to see if it works correctly, feel free.

Tomorrow I'll install FAWE on my test server to see if there are any other problems.

**Comment by EscolarProgramming** [comment]
So, after closing the other issue I'll write here :)
I've updated to the latest Dev-Build (#258) but also in this version the schem event doesn't work. If I run the command `/as schemevent h1e3l-001 rented` there's a chat message that the rented event is fired and neither in the console nor in the chat there are any errors, but it will not create a .schematic file and it doesn't reset the area after unrent. The debug doesn't show anything. 

Here's the log (with activated debug): https://pastebin.com/3aKEqYnQ
And my infos again: 
- SpiGot 1.13.1
- AreaShop Build #258
- WorldEdit 7.0.0
- WorldGuard 7.0.0
- Vault 1.7.1

**Comment by NLthijs48** [comment]
I tested AreaShop with FAWE and found an issue, it is a small thing that is different in the FAWE api compared to WorldEdit. I c[reated an issue at the repository of FAWE](https://github.com/boy0001/FastAsyncWorldedit/issues/1167) to see if we can solve it.

I'll let you know when I know more.

**Comment by NLthijs48** [comment]
FastAsyncWorldEdit should work now, install the latest development build to test it out: http://wiefferink.me:8080/job/AreaShop/
