### ISSUE TITLE
flushQueue becomes flushSession in WE7

### ISSUE THREAD

**Issue by pmme** [NLthijs48/AreaShop#447]
This is information that you may have a bug, or the problem may simply be due to my misunderstanding.

#### Current behavior
restoreRegionBlocks in WorldEditHandler7 calls editSession.flushQueue

#### New behavior
In making my own conversion to 1.13.1 on my own fork, I was required to change this to editSession.flushSession since the method name has changed in WE7.

I have not made a pull request since my branch removes all prior version dependencies, which I doubt you want.

I don't understand how you were able to compile while still having flushQueue but I'm guessing this could be a source of problems unless, as I said before, it's just my misunderstanding.

I'm a C++ coder, not Java, hence the extreme method I took to update to 1.13.1 and ensure I wasn't getting old dependencies.

#### My environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): Spigot
* Server version: 1.13.1
* AreaShop version: 2.4 my own branch
* WorldEdit version: 7.0.0-SNAPSHOT
* WorldGuard version: worldguard-legacy-7.0.0-beta01.jar
* Vault version: 1.6.7 with maven dependency for VaultAPI updated to 1.5

**Comment by pmme** [comment]
Thanks for the explanation. I had not realized setting the pom to "provided" and version "7.0.0-SNAPSHOT" would get a different version than beta01 so I was very confused how only I was seeing a change in method name.

**Comment by NLthijs48** [comment]
Fixed the issue, the [latest development build](http://wiefferink.me:8080/job/AreaShop/) can be used if you want to use the development build of WorldEdit.
