### ISSUE TITLE
TnT destroy outside region

### ISSUE THREAD

**Issue by Sprungente** [NLthijs48/AreaShop#450]
**Current behavior**
Tnt Protection doesn't work well 

**Expected behavior**
less blocks will be destroyed

**Steps to reproduce**

1. Place Tnt
2. Make BOOOM

**Your environment**

* Server platform (Bukkit, ::::::::::--->>Spigot<<---:::::::::::::, etc.): 
* Server version: 1.13.2 
* AreaShop version: 265
* WorldEdit version: 7.0 Beta
* WorldGuard version: 7.0 Beta
* Vault version: 1.7.2

**Beautiful sexy pictures**
https://picload.org/view/dcogccdl/2018-11-02_15.47.44.png.html

**Comment by NLthijs48** [comment]
AreaShop does not handle the actual protection of regions, WorldGuard does that part. So I would recommend updating WorldEdit and WorldGuard to their latest versions, and if it still happens create an issue at WorldGuard.
