### ISSUE TITLE
Schematic error

### ISSUE THREAD

**Issue by arkobat** [NLthijs48/AreaShop#455]
https://hastebin.com/leyumolezu.cs

**Steps to reproduce**

1.  Create regions
2.  Add to AS
3.  Watch the log

**Your environment**

* Server platform (Bukkit, Spigot, etc.): PaperSpigot
* Server version: 1.13.2
* AreaShop version: version: "2.5.0"
* WorldEdit version: version: "unspecified"
https://gyazo.com/c1b4389acb646af31de7b562403f5ae1
It's the latest, downloaded from FAWE. Should be 7.0.0

* WorldGuard version: 7.0.0
* Vault version: 1.6.7

**Comment by NLthijs48** [comment]
AreaShop does not yet support FAWE, I'm tracking the feature request in [this issue](https://github.com/NLthijs48/AreaShop/issues/436) and I'll close this one as duplicate.
