### ISSUE TITLE
Possibility to translate the month data in the %duration% variable.

### ISSUE THREAD

**Issue by TheoRetisch1** [NLthijs48/AreaShop#457]
Could you add a way to translate the month data in the %duration% variable? Or is it already possible to translate months into another language and I missed it? The possibility would make the text output ingame more consistent and professional.

**Comment by NLthijs48** [comment]
You can add the month names you want to use in `config.yml` to the `months` list (also keep the English ones), after you added them there you can use `/as setduration` with the new month names you have added (or use the new month name in the config files).

**Comment by TheoRetisch1** [comment]
Yeah, I already figured that out. It works and is cool :). But I meant months like January, February or March. These are called when the %until% variable in the language file is triggered. This may not seem very important, but since you can translate every other letter of your plugin I thought I'd ask you. Would just look nicer and more professional.

**Comment by NLthijs48** [comment]
Ah the lines used by `%until%` are in the language file already: https://github.com/NLthijs48/AreaShop/blob/master/AreaShop/src/main/resources/lang/EN.yml#L601-L608

**Comment by TheoRetisch1** [comment]
Thanks for the support and your efforts! Sorry, but I can only find the term "hour, month, second..." in the translation file. The variable %duration% provides a format to display the name of the month. If you output %duration% in the chat you get something like this: "04 January 2019 17:01". I want to be able to translate "January".

**Comment by NLthijs48** [comment]
Ah I was wrong about `%until%`, you cannot translate that one yet, see issue #377 for a feature request to fix that. What I said above is for the `%timeleft%` variable, which shows the time left on the region in the format you want. So if you switch the signs to use `%timeleft%` instead of `%untilshort%` you can actually translate the content.

**Comment by TheoRetisch1** [comment]
Thanks for the info! Since I used the varibale in the translation of rent-rented, rent-extended ... %until% is more informative. Since an open ticket already exists, this ticket can be closed :).
