### ISSUE TITLE
Error extending regions for offline player

### ISSUE THREAD

**Issue by TheoRetisch1** [NLthijs48/AreaShop#459]
If you activate the setting to automatically extends a rent when the time is up: `rent.autoExtend` in `default.yml` and if owner of the region is offline this error appears in the log: https://pastebin.com/H9UZVuxb.
The error keeps spamming until the server crashes (low tps) or until the disk is out of space. Hopefully you are able to fix this.

AreaShop: 2.5.0
LuckPerms: 4.3.39
Paper 1.12.2 #1593

**Comment by NLthijs48** [comment]
The issue you describe is the same one as discussed in [this issue](https://github.com/NLthijs48/AreaShop/issues/441), I'll see what I can do to prevent this in the future but for now the suggestion in your log of to enable `vault-unsafe-lookups` in the LuckPerms config seems like the way to go.

I'll close this as duplicate to keep the conversation at the other issue.
