### ISSUE TITLE
Negating settp perm does not remove /as settp from /as help menu

### ISSUE THREAD

**Issue by DragaoNimhe** [NLthijs48/AreaShop#477]
**Current behavior**

When areashop.setteleport is negated, /as settp still shows up on /as help menu, unlike other commands when their perms are negated. No visible errors in console.

**Expected behavior**

For /as settp to not be visible under /as help when areashop.setteleport is negated.

**Steps to reproduce**

1. Give the permission node -areashop.setteleport to a player
2. Have player run /as help
3. They should still be able to see /as settp listed, like in this example: https://puu.sh/CGWZI/f65ba71aac.png

**Your environment**

* Server platform (Bukkit, Spigot, etc.): paperclip-507
* Server version: 1.13.2
* AreaShop version: 2.6.0
* WorldEdit version: 7.0.0-SNAPSHOT
* WorldGuard version: 7.0.0-SNAPSHOT
* Vault version: 1.7.1

**Your config files**

[AreaShop.zip](https://github.com/NLthijs48/AreaShop/files/2826682/AreaShop.zip)

**Comment by NLthijs48** [comment]
Thanks for your bug report, this indeed does not work, I have fixed it in d7cdff0b2285bc335489654a5ba54bd8ba09ee77, if you download the [latest development build](http://wiefferink.me:8080/job/AreaShop/) it should work properly.
