### ISSUE TITLE
AreaShop greeting region messages

### ISSUE THREAD

**Issue by jordanwilliams1** [NLthijs48/AreaShop#484]
Hello, How Do I turn off the greeting messages when you walk into a region that can be rented/or that is already being rented?

I followed the faq but i couldn't find the "greetings" in my defualt.yml?

https://pastebin.com/A0J1h8Zr

**Comment by NLthijs48** [comment]
You still have an older version of the `default.yml` file, it should still be in the `config.yml` file for you.

Let me know if you found it.
