### ISSUE TITLE
Support for the latest FAWE version

### ISSUE THREAD

**Issue by TheoRetisch1** [NLthijs48/AreaShop#487]
FAWE is back, believe it or not. In its current state FAWE is again the most performant and innovative worldedit on the market. Significant bugs and dependencies have been fixed.  This includes above all the use of the latest and official worldguard  and worldedit API. Now many other plugins are working again with FAWE, but unfortunately AreaShop doesn't work anymore. A fix would be fantastic!

Error: https://pastebin.com/YMwUJME3
FAWE 1.13.2 version 1.0
Worldguard: 7.0.0-SNAPSHOT;1820-ea47e93
AreaShop: 2.6.0#285
Paper 1.13.2 - 597

**Comment by andris155** [comment]
Same problem.

**Comment by bloggy** [comment]
Same Problem here.

Hopefully you can fix this asap :-)

https://hastebin.com/ixodopucik.md

**Comment by TheoRetisch1** [comment]
The problem still exists after one month and meanwhile we really have a fully functional FAWE version. You can download Development builds here: http://ci.athion.net/job/FastAsyncWorldEdit-1.13/changes
It would be really cool if you could fix it as soon as possible. Quite some people are waiting for it :) #bump

**Comment by TheoRetisch1** [comment]
I close the problem, because I don't use AreaShop anymore and I can't update the ticket.
It almost looks like AreaShop is about to die. It hasn't been updated for months and is completely useless unless you want to use normal worldedit.
I recommend AdvancedRegionMarket  to everyone as a very good alternative in many respects: https://www.spigotmc.org/resources/advancedregionmarket.58732/
