### ISSUE TITLE
Areashop Block Break Problem

### ISSUE THREAD

**Issue by TacticalTrav** [NLthijs48/AreaShop#49]
If someone rents a region, they can build but not break any blocks... I've looked everywhere, I just need a quick solution.

            Thanks in advance!

**Comment by NLthijs48** [comment]
You probably have some flags set on the region. First stand in the region and use '/region info', if it show region information then make a screenshot and attach that here. If it shows a list of regions at that spot then use  '/region info <regionName>' for each of those and make screenshots of those and post them here. With that information I will probably be able to tell you the problem.

**Comment by TacticalTrav** [comment]
![2015-08-15_15 36 48](https://cloud.githubusercontent.com/assets/13805524/9291103/86427aa2-4363-11e5-8fd4-6b8179e009c5.png)

**Comment by NLthijs48** [comment]
Any other regions at the same place? The flags on this region are correct.

**Comment by TacticalTrav** [comment]
There is one big region to protect the area and one next to it... Would that effect anything?

**Comment by NLthijs48** [comment]
If those regions cover the same area, then yes. Settings the priority to 1 of the plot2 region might fix it, but I can't say that for sure without knowing how the other regions are configured.

**Comment by TacticalTrav** [comment]
I used myself to try it out but I still can't break... Even with the priority higher.

**Comment by NLthijs48** [comment]
Check which regions are also at that spot and send me the region information of those.

Do you have a server I can join? Because that might be easier.

**Comment by TacticalTrav** [comment]
The ip is: gravityplanet.beastmc.com

**Comment by NLthijs48** [comment]
Fixed it on the server.

**Comment by TacticalTrav** [comment]
wait, the stacking is weird

**Comment by TacticalTrav** [comment]
It puts "001" after the number...

**Comment by NLthijs48** [comment]
If you don't want the 00 prefix then you can change the 'stackRegionNumberLength' setting to 0 instead of the default of 3 (see config.yml). However most people like to have their regions like this because then the names are all the same length, and they sort correctly.

**Comment by rampage211** [comment]
What was the solution?

**Comment by NLthijs48** [comment]
@rampage211 fixing the region flags, for example removing any build, block-break and block-place flags from the non-AreaShop regions (WorldGuard regions by default only allow members/owners to build on it, so you do not need any of those flags)

**Comment by LasseKJ** [comment]
Can you explain it better?
