### ISSUE TITLE
(1.14.2) Throws error whenever a sign is placed anywhere

### ISSUE THREAD

**Issue by SurvivalQuest** [NLthijs48/AreaShop#507]
**Current behavior**
Whenever a sign is placed anywhere in the world, AreaShop throws an error.
"Could not pass event BlockPhysicsEvent to AreaShop v2.6.0#287"
Error: https://pastebin.com/FWkbAU13

**Steps to reproduce**
1. Place a sign anywhere in the world

**Your environment**

* Server platform (Bukkit, Spigot, etc.): Paperclip
* Server version: Paper version git-Paper-59 (MC: 1.14.2)
* AreaShop version: 2.6.0 b287
* WorldEdit version: 7.0.0-SNAPSHOT;4326-a3afd9d
* WorldGuard version: 7.0.0-SNAPSHOT;1902-903a831
* Vault version: 1.7.2-b107

**Comment by NLthijs48** [comment]
You can try the development build that is suitable for 1.14, you can download it here: http://jenkins.wiefferink.me/job/AreaShop/.

I'll release this as an official version soon.
