### ISSUE TITLE
Limit number of regions in a town

### ISSUE THREAD

**Issue by zigzag32** [NLthijs48/AreaShop#51]
Allow for more granular control on the limits, like allowing them to only own 1 lot per town.

**Comment by NLthijs48** [comment]
This is already possible by the current limits system, check the 'limitProfiles' section of the config.yml file. Next to that you can check some examples and information on [this page](http://dev.bukkit.org/bukkit-plugins/regionbuyandrent/pages/advanced-limit-groups-setup-example/).
