### ISSUE TITLE
A new placeholder 

### ISSUE THREAD

**Issue by ziemniok99** [NLthijs48/AreaShop#510]
**Describe the problem you are trying to solve with this feature request**
I really want a placeholder like %region_max_y%, %region_min_y% etc. This I because I have a plugin with shops and in this we have purge command so I can do in eventcommand sold do command /ushop purge in:%region_max_x%,%region_min_x%... 

**Describe the solution you'd like**
Add this placeholders

**Comment by NLthijs48** [comment]
Closing in favor of a proper integration with UltimateShops: https://github.com/NLthijs48/AreaShop/issues/493
