### ISSUE TITLE
Question areashop buyable for a rank/Team only 

### ISSUE THREAD

**Issue by Marcofurio30** [NLthijs48/AreaShop#513]
**Desired behavior**
I have 2 "teams" on the same map, i need that only one team can buy an areashop in a worldguard region, and the other team in an other worldguard region.
Is there a way do to this?

**Your environment**
* Server platform (Bukkit, Spigot, etc.): Paper
* Server version: 
* AreaShop version: 2.60
* WorldEdit version:  6.1.9
* WorldGuard version: 6.1.9
* Vault version: 1.7.2

**Comment by mrcoffee1026** [comment]
If you have coreprotect installed as well and the rentals are handled by signs and not directly by commands... you can lock those signs and then /cmodify g:team_one_group and /cmodify g:team_two_group to the respective signs (assuming those two permission groups are the names you gave the teams) to accomplish this.

**Comment by Marcofurio30** [comment]
I've installed CoreProtect but there is not /cmodify command ?
