### ISSUE TITLE
Landlord passing-on

### ISSUE THREAD

**Issue by M9GLiquid** [NLthijs48/AreaShop#52]
Hi there, Simple question I hope:
I have figured out that as a landlord of a region you collect the cash.

I want to make alot of smaller Inn's so I want to add so that when someone buys the inn they get landlords over the rented rooms inside the group/region.
As to collect from them.
I understand that I can do this manually but I'm asking this to see if there is a automatic way.
If someone buys my Inn. I'd like it to add landlord over to the rent regions inside that region (I also have it set as a group).
However I also want it so that if the player that once before bought it sells it, it would first remove him as landlord of all the regions then add the new person.

I thought I could do this with the landlords and then the groups but I cannot figure it out and havn't found any information regarding it (Am I missing anything).

**Comment by NLthijs48** [comment]
It is not so easy to do something like this, and sadly the group system will not be of much help to solve this. What you could do is using the `eventCommandProfiles` section in the `config.yml` file to solve this problem. For each Inn you can make a profile, and then add commands to set the landlord for the rooms inside the Inn. You need to add these commands to the `after` section of the `rented` subsection. A command would look something like this: `/areashop setlandlord %player% <regionName of room>`. You would need to add a command like that for each region (so just make a list of commands in that section). You need to create such an `eventCommandProfile` for each Inn, and assign the profile to an Inn from within the region file (<regionName>.yml for the Inn).

Let me know if that solves your problem, or if you have any questions (closing the issue, you can still comment though).
