### ISSUE TITLE
Link multiple regions to rent/buy sign

### ISSUE THREAD

**Issue by M9GLiquid** [NLthijs48/AreaShop#53]
Make it so that you can link mutliple regions to any region sign.

Such as if you have a sign for rent on region room_1 then you could do "/as linkregion room_2"
and then click the sign to be linked.

Then if someone goes to rent the room_1 they automatically get room_2 aswell. :)

regards,
Thomas

**Comment by NLthijs48** [comment]
You do not really need a new command to do this, you can already make a thing like this with the `eventCommandProfiles` section in the `config.yml` file. If you name your regions with a certain pattern, for example `room_1` and `room_1+` then you can easily make sure that a player will get both regions when using the signs of `room_1`. Simply place all base regions (so `room_1`, `room_2`, etc) in a region group with `/as groupadd`, then assign a eventCommandProfile to this group. In the eventCommandProfile you place the following command in the `after` section of the `rent` section: `/as setowner %player% %region%+`. That command will set the renter of the first region as owner of the second region (the one with the `+` behind the name). In the `before` section of the `unrent` section you place the following command: `/as unrent %region%+`, which will make sure that the plus region is removed when the rent is over.

Let me know if that solves your situation or if you have any other questions.
