### ISSUE TITLE
Signs facing north wont work

### ISSUE THREAD

**Issue by epic-gamer420** [NLthijs48/AreaShop#559]
Sign facing north wont work, we want to make buyable regions but signs dont work if they are facing north how do i fix this?
It work all the other ways and facing north on the ground also works, but not on walls.

* Server platform (Bukkit,): 
* Server version: 1.15.2
* AreaShop version: newest (14-06-2020)
* WorldEdit version: 7.1.0
* WorldGuard version: 7.0.2
* Vault version: newest (14-06-2020)

**Your config files**

**Comment by Syrkulous** [comment]
Please use this version! http://wiefferink.me:8080/job/AreaShop/299/
The spigot page is an outdated version.

Click where it says "AreaShop.jar"

**Comment by epic-gamer420** [comment]
thx m8 i will try it

**Comment by epic-gamer420** [comment]
it does not work we removed the old plugins and downloaded a new from your link but it seems that it is no good.

**Comment by Syrkulous** [comment]
You've done something wrong then. If you're using FAWE the plugin won't work correctly either.

**Comment by epic-gamer420** [comment]
M8 it worked thx soooo much there was one file from the old plugin that we missed.
+ 10 reputation points and + 10 karma.
