### ISSUE TITLE
error on /as addsign and in general just acting weird

### ISSUE THREAD

**Issue by realwakils** [NLthijs48/AreaShop#569]
**Current behavior**

when i do /as addsign REGIONNAME, it says internal error and nothing happens and it sends me this error message: https://pastebin.com/AEdsH8a5

**Expected behavior**

for the signs to be linked and no error

**Steps to reproduce**

1. i do /as addsign REGIONNAME that exists
2. in chat it says an intenral error occured....
3. the console sends me this error: https://pastebin.com/AEdsH8a5

**Your environment**

* Server platform (Bukkit, Spigot, etc.): Paper build 128
* Server version: 1.16.1
* AreaShop version: 2.6.0
* WorldEdit version: 7.2.0 beta 02
* WorldGuard version: 7.0.4 beta 1
* Vault version: 1.7.3-b131

**Your config files**

[MyConfig.zip](https://github.com/NLthijs48/AreaShop/files/5003277/MyConfig.zip)

**Comment by KalippSoo** [comment]
Idk if i could help you but me i use /as addsign (no region) try it

**Comment by KalippSoo** [comment]
just put a sign in the region put your cursor on the sign and do /as addsign

**Comment by realwakils** [comment]
Nope same thing. Also sometimes when placing signs it gives me an error message aswell.

**Comment by Syrkulous** [comment]
Use this version for 1.14-1.15.2 http://wiefferink.me:8080/job/AreaShop/299/
The spigot site is outdated.

**Comment by realwakils** [comment]
> Use this version for 1.14-1.15.2 http://wiefferink.me:8080/job/AreaShop/299/
> The spigot site is outdated.

Thanks. Question. Why don't they update on Spigot? I have to dig so deep, to find the proper version... that's ridiculous.

**Comment by realwakils** [comment]
Worked after I installed http://wiefferink.me:8080/job/AreaShop/300/. Actually I'm currently using Curtis73's fork: https://github.com/Curtis73/AreaShop/releasesy

**Comment by Syrkulous** [comment]
Curtis' fork was made for 1.16+, if it works it confirms I'm wrong, but I'm unsure. I don't think it would work correctly

**Comment by realwakils** [comment]
Well I use 1.16.1 Paper, and it works fine... For now.

**Comment by Syrkulous** [comment]
Apologies, I swear I read somewhere the user was in 1.15, might've been a different issue.
Glad your issue has been fixed
