### ISSUE TITLE
Reload resets changes at translation file

### ISSUE THREAD

**Issue by EvilOlaf** [NLthijs48/AreaShop#57]
I edited some phrases at the German lang file (also see pull request from a few minutes ago) and did `/as reload` and the changes have been reverted. Tried this a couple of times.

v2.2.0

**Comment by NLthijs48** [comment]
This is intended behavior and is also pointed out at the top of each language file. AreaShop will overwrite the build-in language files at each restart/reload to keep them up-to-date (new AreaShop versions may include more messages and changed messages). If you want to change something in a language file then you need to copy the file you want to base it on, give it a different name (for example `<serverName>.yml`), then make your changes, set the language in `config.yml` to the new file, use `/as reload`.

**Comment by EvilOlaf** [comment]
Nice. Works like a charm.
