### ISSUE TITLE
Intelij Maven dependency not found

### ISSUE THREAD

**Issue by Tomut0** [NLthijs48/AreaShop#581]
**Current behavior**
I used this [link](https://github.com/NLthijs48/AreaShop/wiki/Create-an-integration) to hook your plugin.
Pom.xml sent me out and said:
> Dependency 'me.wiefferink:areashop:2.4.0-SNAPSHOT' not found

Other dependencies works well, tried to invalidate cache, removing .m2 folder and so on.
Also tried to change version of dependency from 2.4.0 to 2.4.3.

**Desired behavior**
I want to hook your plugin as normal guy. 
Am I doing something wrong? 
![изображение](https://user-images.githubusercontent.com/42711312/111852257-489e5d00-8927-11eb-8a5c-8a75f5817a40.png)
![изображение](https://user-images.githubusercontent.com/42711312/111852241-3b816e00-8927-11eb-8ea4-b858d017b4ba.png)

**Comment by md5sha256** [comment]
Have you tried asking intellij to re-import/resolve dependencies?

**Comment by Tomut0** [comment]
> 
> 
> Have you tried asking intellij to re-import/resolve dependencies?

![изображение](https://user-images.githubusercontent.com/42711312/111900807-a032ea80-8a45-11eb-837a-fa882967fdf2.png)

Intelij don't suggest any ways to solve it.

**Comment by Loot1** [comment]
Same problem for me, this website : <url>https://maven.wiefferink.me</url> is down, I think i'ts the problem.

**Comment by Tomut0** [comment]
> Same problem for me, this website : https://maven.wiefferink.me is down, I think i'ts the problem.

AreaShop is seems abandoned, I recommend to use [AdvancedRegionMarket](https://www.spigotmc.org/resources/advancedregionmarket.58732/) instead.
