### ISSUE TITLE
Players cannot build in their property

### ISSUE THREAD

**Issue by EmpireCraftdarcking** [NLthijs48/AreaShop#64]
Hello,
I use the plugin areaShop but when my player buys land he owns are but can not build on their property

**Comment by NLthijs48** [comment]
Please check the following FAQ entry:

[Why can't the buyer/renter of the region build inside of it?](https://github.com/NLthijs48/AreaShop/wiki/Frequently-Asked-Questions#why-cant-the-buyerrenter-of-the-region-build-inside-of-it)

Let me know if that solves your problem.

**Comment by NLthijs48** [comment]
I'm assuming your issue has been fixed, closing the issue.
