### ISSUE TITLE
Automatic teleport

### ISSUE THREAD

**Issue by TheDevil666** [NLthijs48/AreaShop#68]
Hey, first sry for my english :) i´m from Germany
I want to ask whether there is a possibility that you will be automatically teleported to the purchase plot.

NG
TheDevil

**Comment by NLthijs48** [comment]
You can already make that happen with the `eventCommandProfiles` section in `config.yml`. If you add the following command to `after` of the `bought` section then they will be forced to teleport to that region: `sudo %player% as tp %region%`. This assumes you have Essentials installed which provides the `sudo` command (makes it possible to execute a command as if the player did it himself).

Let me know if that solves your problem.

**Comment by TheDevil666** [comment]
Thank you, it works after some tests :D 
The right comand is
    bought:
      before:
      after:
      - "sudo %player% as tp %region%"

**Comment by NLthijs48** [comment]
Nice, I'll close the issue.
