### ISSUE TITLE
How do I change the price of a shop rental?

### ISSUE THREAD

**Issue by c0wg0d** [NLthijs48/AreaShop#69]
Can I just edit the regionname.yml file in the plugin folder with the new price and then do /as reload or do I have to delete the region and set it up again?

**Comment by EvilOlaf** [comment]
None of this. Use `/as setprice`.

**Comment by c0wg0d** [comment]
I don't know how I missed that in the wiki.  Thank you.

**Comment by NLthijs48** [comment]
That was a quick fix :)

**Comment by EvilOlaf** [comment]
Ouh yeah
