### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by R0n1n66** [NLthijs48/AreaShop#70]
I am having a hard time getting areashops to work.  I have read everything i can watch as many videos i could find and still when i try to add a region i get a null error when i try the signs they dont do anything  when i do /as add buy shop5 and hit enter nothing happens.  I thought maybe it was a conflict with another plugin but i have removed them all and still nothing.  Any assistance would be awesome.

**Comment by EvilOlaf** [comment]
Hard to say without console output.

**Comment by NLthijs48** [comment]
I talked with a (co)-owner of you server about this problem, it is probably caused by Cauldron, but I'm not 100% sure about that. I have already setup a test server for Cauldron, but I cannot get a working Forge 1.7.10 client, and therefore are unable to investigate this further.

**Comment by Finally50** [comment]
I Got it to start trying to work. Does this information help to maybe narrow down the reason or cause of the plugin not working for us?

11:25:00 AM CONSOLE: [INFO] LaDaStorm issued server command: /as add
11:25:07 AM CONSOLE: [INFO] LaDaStorm issued server command: /as add rent player1
11:25:22 AM CONSOLE: [INFO] LaDaStorm issued server command: /as add region
11:25:33 AM CONSOLE: [INFO] LaDaStorm issued server command: /as add buy player1
11:25:41 AM CONSOLE: [INFO] LaDaStorm issued server command: /as info player1
11:25:53 AM CONSOLE: [INFO] LaDaStorm issued server command: /as info all player1
11:26:15 AM CONSOLE: ERROR]: Could not pass event PlayerInteractEvent to AreaShop v2.2.0

As well as you can see in the image:

http://imgur.com/cmnOUHC


The region registered as player1 is showing up when I do
 /as info all forrent 
And when I break the sign that was setup it says
" the sign has been removed from region player1" 

And when I request to tp to regions for rent. It tp's me to the sign.

Only no ability to rent the region still. 

The Sign dosen't change to [for rent] after placing sign with correct info needed. 
So it is not a sign that can be right clicked to rent the region.

And if you just stand in the region and do /as rent
"exception executing command 'as' in plugin AreaShop v2.2.0" 
comes up in the console
and
"An internal error occurre while attemtpting to perform this command" 
Displays in chat in red ingame

**Comment by NLthijs48** [comment]
The message in chat indicates there was an error with AreaShop, could you send me the log file of that error? You can simply try it again to trigger the error, and then download the 'latest.log' file from the 'logs' folder and upload the contents to [pastebin](www.pastebin.com).

**Comment by NLthijs48** [comment]
Assuming it has been fixed.
