### ISSUE TITLE
UnlimitedRenting

### ISSUE THREAD

**Issue by iOnixS** [NLthijs48/AreaShop#73]
Okay so i dont know if there is a way to cap the rent limit. My players (If they have the money) Can rent a region for 100 years. I really dont want this. If there is a way to stop this please tell me! Thanks, Adam.

**Comment by NLthijs48** [comment]
There is a setting [`maxRentTime`](https://github.com/NLthijs48/AreaShop/blob/25c56e8ecb7590739d5cadfb98b8d7fd063d258f/AreaShop/src/main/resources/default.yml#L55-L58) in `default.yml` to limit how many time a player can rent the region in advance (only when renting the region for another period stays under the limit, then the player is allowed to extend the rental). That should fix your problem, current really long rentals will stay, but they will not be able to extend it until the it drops below the limit.

**Comment by iOnixS** [comment]
That doesnt work. I set it to this http://pastebin.com/HPJaNeks But still nothing, any thoughts?

**Comment by NLthijs48** [comment]
What did you try after setting that to 3 days? How did you conclude that it does not work?

**Comment by iOnixS** [comment]
Just tried spam clicking the sign.

**Comment by NLthijs48** [comment]
Okey, try leftclicking the sign, does it display a line that says `In advance renting: 3 days at maximum.`? If you do not have such a line, then the setting is not correctly set. Also be aware that OPs can bypass the limit and rent it anyway, so be sure you let a normal player test it.

**Comment by iOnixS** [comment]
Wow! That worked perfrct, Thank you!

**Comment by NLthijs48** [comment]
Great!
