### ISSUE TITLE
Cool feature

### ISSUE THREAD

**Issue by iOnixS** [NLthijs48/AreaShop#74]
Ok i would like a feature added. When my players rankup they will lose their region. THey will do /rankup and AS Will do /as unrent. If this can be added please do it! Thanks, Adam.

**Comment by NLthijs48** [comment]
The planned command to wipe a player from AreaShop might be what you are looking for, assuming that your rankup plugin supports running any command you would like (most of them do). [#31: Add a command to completely wipe a player from AreaShop](https://github.com/NLthijs48/AreaShop/issues/31).
