### ISSUE TITLE
UnlimitedRenting

### ISSUE THREAD

**Issue by iOnixS** [NLthijs48/AreaShop#76]
Yeah, i just made this issue earlier but it got closed.. Okay so i dont know if there is a way to cap the rent limit. My players (If they have the money) Can rent a region for 100 years. I really dont want this. If there is a way to stop this please tell me! Thanks, Adam.
My reply is: That doesnt work. I set it to this http://pastebin.com/HPJaNeks But still nothing, any thoughts?

**Comment by NLthijs48** [comment]
You don't need to recreate the issue, commenting on the original issue works just fine :)

I'll close this one since we can just continue the conversation on the original issue: #73.
