### ISSUE TITLE
"This region is not available for renting"

### ISSUE THREAD

**Issue by iOnixS** [NLthijs48/AreaShop#77]
I dont know why it does this? I can rent it, then just not click it again?

**Comment by EvilOlaf** [comment]
When the region is already rented by someone else it is not available for renting anymore.

I don't get it.

**Comment by NLthijs48** [comment]
This message comes up if the region you specified as argument is not a rental region, for example because it is registered as a buy region, not registered in AreaShop at all or not even a region in WorldGuard. Check if the region argument that you give to the `/as rent [region]` command is correct.

**Comment by NLthijs48** [comment]
If you still have this problem then please attach the `<regionName>.yml` file of the `/plugins/AreaShop/regions/` folder, then I should be able to tell if something is wrong.

**Comment by iOnixS** [comment]
Its just when someone rents a region and they click the sign to top up the
rent and thats when it says it. And it is EVERY Region...

**Comment by NLthijs48** [comment]
Okey, then please send me your `config.yml`, `default.yml` and `groups.yml` files, it is probably some misconfiguration (attaching them within your email client does not work as far as I know, open the issue in the browser and drag the files to the input field).

**Comment by iOnixS** [comment]
There is the links to download it.
http://www.4shared.com/file/Xjbt1zwgce/config.html
http://www.4shared.com/file/-fbrE1Lace/default.html
http://www.4shared.com/file/ofTzD8xWce/groups.html

**Comment by NLthijs48** [comment]
I would like you to use a site that does not require a sketchy social media login, such as DropBox, Google Drive, or simply uploading the files in the input field in the GitHub website.

**Comment by iOnixS** [comment]
Sure, there you go.
https://drive.google.com/drive/u/0/folders/0BxG5mb7-JeMkaEMxUDBJY3pWVWs

**Comment by NLthijs48** [comment]
The link you shared is not a link that others can access, rightclick on the folder and then click `Get link` to get a working one.

**Comment by iOnixS** [comment]
Oops, sorry about that.
https://drive.google.com/open?id=0BxG5mb7-JeMkaEMxUDBJY3pWVWs

**Comment by NLthijs48** [comment]
Okey that works, I however see nothing weird in your config files. Can you send the <region>.yml file for a region that has trouble?

**Comment by iOnixS** [comment]
It is every region, i have over 180 regions...

**Comment by NLthijs48** [comment]
That does not matter, I would like to see one of the region files to see if something is wrong

**Comment by iOnixS** [comment]
Sorry for late reply, havent been on. Here it is.
https://drive.google.com/file/d/0BxG5mb7-JeMkaVFpRVRyQzcza00/view?usp=sharing

**Comment by iOnixS** [comment]
I was changing the config so that i could make a sign change, i removed the
%region% so thats why i couldnt remove it. I fixed it now, thanks for the
help.

**Comment by NLthijs48** [comment]
Ah nice, that would indeed explain it.
