### ISSUE TITLE
Rentsign for bought region

### ISSUE THREAD

**Issue by TheDevil666** [NLthijs48/AreaShop#79]
Hey,
is there a way to allow players set a rentsign for a region they own? If i try to set a rentsign Areashop tells me, that there is already a buysign for the region.
So i would like to set, that players can set a rentsign without removing the buysign from Areashop.

Sry for my english, i hope you understand my question :)

NG

**Comment by NLthijs48** [comment]
If a region is a buyregion then you cannot make a rent sign for it, a region is either a rental region or buy region, and not both at the same time.

If you want a player to be able to rent a region to others then you can register the region as a rental region, and then use `/as selandlord` to set the player as landlord. This means that that player will get all money made by renting the region.

The landlord permissions might be useful for you, to let players determine their own price and duration: [https://github.com/NLthijs48/AreaShop/wiki/Commands-and-Permissions#other-permissions](https://github.com/NLthijs48/AreaShop/wiki/Commands-and-Permissions#other-permissions)

**Comment by NLthijs48** [comment]
Assuming it has been fixed.
