### ISSUE TITLE
Suggestion: DynMap Integration

### ISSUE THREAD

**Issue by nicktrick92** [NLthijs48/AreaShop#80]
I would love this plugin if it would add DynMap integration like Simple Region Market had. I need to show regions that are up for sale live on my DynMap for my server!

Thanks,

-Nick

**Comment by EvilOlaf** [comment]
Well if you use dynmap-worldguard you have some kind a implementation of areashop as it shows the flags. Well it's optical not perfect though.

**Comment by NLthijs48** [comment]
I already had a couple of suggestions for this, and it is already noted down in #30, so I'll mark this as a duplicate for that one. That issue also links to the Dynmap-worldguard plugin that @EvilOlaf mentioned, which indeed functions as a basic display of the regions.

Although I'm also interested in getting this into AreaShop, this might take a while to implement.

**Comment by nicktrick92** [comment]
Oh, okay... Thanks for responding, I'll try the WorldGuard one!
