### ISSUE TITLE
setDuration won't work with "Seconds"

### ISSUE THREAD

**Issue by chloeprince** [NLthijs48/AreaShop#82]
No matter what I do, or try I can not set a sign to rent in Seconds mode with the latest version of the plug in.

**Comment by NLthijs48** [comment]
I could confirm the issue, the `/as setduration` command indeed did not accepts the modifiers to indicate seconds, AreaShop could correctly read the seconds modifiers when used in the config though. I have fixed the problem in the commit linked above, so this fix will be part of the next update.

A workaround could be opening the region.yml file and changing the duration manually. If you set a really low rental time you also might want to set the `delay` setting of the `expiration` section lower, currently AreaShop will only check every 59 seconds if regions should be unrented.
