### ISSUE TITLE
World Guard protection and Area Shop priority

### ISSUE THREAD

**Issue by Dragzie** [NLthijs48/AreaShop#83]
Ok, my problem is this. I use world guard to protect the whole spawn and in my spawn there is a market I build a few days ago, so then I did /rg setpriority spawn -1 and /rg setpriority market 5. When I rent a shop and deop myself just to test if it work the market, but it still say "Hey! Sorry, but you can't place that block here.". Please help :/

**Comment by NLthijs48** [comment]
Is the `market` region the region that is added to AreaShop or do you have other regions inside the `market` region as shops? If you have other regions then you need to set those regions to a priority higher as 5.

If that does not help then please attache the config.yml file here and show me the output (screenshot) of `/region info` for all regions that are at the spot of the region that you are trying with.
