### ISSUE TITLE
API: (cancellable) region events

### ISSUE THREAD

**Issue by NLthijs48** [NLthijs48/AreaShop#84]
All data is already quite easy to get from AreaShop (but might require some more documentation on the wiki), but currently there is no way to act upon important events, such as region selling. An API with region events that also supports cancelling the transaction would be nice to have for this case.

**Issues that depend on the API:**
#19: Support for removing LWC protections.
#37: Support for removing QuickShop shops.
#88: Support for removing Holodisplay shops

**Comment by minoneer** [comment]
As discussed in the last mail, here some input on the event system. Since a few lines of code can express more than pages of text, I did some quick implementations of three basic events. It's nowhere near complete, but it is a start. Feel free to use / improve / scratch whatever you deem appropriate.

https://github.com/NLthijs48/AreaShop/compare/master...minoneer:master

**Comment by NLthijs48** [comment]
That is a good start for the implementation, I have some remarks though.

First of all, the usage of these events can basically be split into 2 directions:

1. Using it to cancel the action when certain external conditions are met.
2. Using it to detect actions happening and act upon them.

Number one is already covered by your implementation, since this would allow you to cancel it. Number two is not covered, since even though the event might not be cancelled, the buy/rent might still not happen. This is because the RentRegion#rent() and BuyRegion#buy() methods still have a bunch of conditions in them (permissions, limits, money, etc.).

So it looks like 2 kind of events are required to be able to support both situations properly, one to be able to cancel the action from happening, and one to monitor the outcome.

Some implementation specific remarks:
* It might be nice to have a superclass for these events, then a couple of the common methods don't need to be repeated.
* RegionRentEvent is now also called when extending a rent, this might be explicitly indicated by a isExtending() method or split into a seperate event (technically you can check if it is an extend by checking if the region is already rented at the time of an event, but that is not great).
* Events for region creation (adding to AreaShop) and removal might also be a good thing to add.
* You are throwing the events in the command classes now, it might be better to do this in the buy() and rent() methods inside the region classes, since those could also be called directly by other plugins.

If you like to continue then of course do, otherwise I will probably pick this up soon myself.

**Comment by NLthijs48** [comment]
First implementation has been done, next I will transfer a bunch of AreaShop functions (sign updating, region flags updating, running event commands, etc) to the event system.

Any suggestions for improvement are appreciated of course.
