### ISSUE TITLE
Support for removing Holodisplay shops

### ISSUE THREAD

**Issue by NLthijs48** [NLthijs48/AreaShop#88]
Remove the shops created by [this plugin](https://www.spigotmc.org/resources/shop-a-simple-intuitive-shop-plugin.9628/) when a region is unrented.

*[Suggested by maxlehot1234](https://www.spigotmc.org/threads/areashop.43135/page-9#post-1084613)*

**Comment by maxlehot1234** [comment]
Thank you :) It can be very amazing if you can add an option in the config to enable/disable this option ;)

**Comment by NLthijs48** [comment]
Duplicate of #87, tracking it there instead.

**Comment by NLthijs48** [comment]
Merged this issue into #19.
