### ISSUE TITLE
Setting for grace period after unrent

### ISSUE THREAD

**Issue by slkjoy** [NLthijs48/AreaShop#89]
What is the setting for configuring the amount of time after unrent when no other player can rent that region? It seems the default is 1 hour and we want to change it to 24 hours.

**Comment by NLthijs48** [comment]
Changing this ticket to a feature request as described in my comment at [BukkitDev](http://dev.bukkit.org/bukkit-plugins/regionbuyandrent/#c895).

**Comment by NLthijs48** [comment]
Closing this issue, if the renter does not see the warning messages (showing up at login, configurable time before the end) then it is also not likely he is going to notice it in the grace period.
