### ISSUE TITLE
Translation Request

### ISSUE THREAD

**Issue by evernife** [NLthijs48/AreaShop#90]
Could you accept my requisiton for me to translate the plugin to Brazilian Portuguese?

**Comment by NLthijs48** [comment]
I have accepted it now, did not check my mail before. Let me know if you have any questions.

**Comment by evernife** [comment]
Can i put color codes in the translation?

**Comment by NLthijs48** [comment]
Putting color codes in the translation is possible, but on Transifex the translation needs to have the same color scheme as the English version. This is to keep the color style the same for all languages. If you want different colors on your server then you can change the language file in the AreaShop folder of your server.
