### ISSUE TITLE
Language file not working right

### ISSUE THREAD

**Issue by ScuroK** [NLthijs48/AreaShop#92]
The language files dont work correctly. im on version 2.2.1

For example when i do /as info player PLAYERNAME

I get a message like this:
%0% has not bought.... 

Can anyone help me?

**Comment by NLthijs48** [comment]
I have already [fixed](https://github.com/NLthijs48/AreaShop/commit/3e7c7ce76b281f01a36e1505c1da576decff5790) this a few days ago after a [comment of NoHopeLess](http://dev.bukkit.org/bukkit-plugins/regionbuyandrent/#c899) about the same problem.

You can download an updated AreaShop version at the [Jenkins](http://ci.frostcast.net/job/AreaShop/) server.
